// frontend/src/components/BentoTech.vue
<template>
  <BentoCard class="group relative overflow-hidden">
    <div class="relative">
      <!-- Header -->
      <div class="mx-3 flex items-center justify-between">
        <div
          class="flex h-10 w-10 items-center justify-center rounded-2xl transition-transform duration-300 group-hover:scale-110 group-hover:rounded-xl"
        >
          <svg
            xmlns="http://www.w3.org/2000/svg"
            class="text-ink size-6"
            viewBox="0 0 24 24"
            fill="none"
            stroke="currentColor"
            stroke-width="2"
            stroke-linecap="round"
            stroke-linejoin="round"
          >
            <polyline points="16 18 22 12 16 6" />
            <polyline points="8 6 2 12 8 18" />
          </svg>
        </div>
        <h3 class="text-muted text-xs font-bold tracking-wider uppercase">
          TechStack
        </h3>
      </div>

      <div class="mt-3 ml-3 flex flex-wrap gap-2">
        <span
          v-for="tech in techStack"
          :key="tech.name"
          :class="[
            'cursor-default rounded-md px-2.5 py-1 text-xs font-medium transition-colors',
            colorClasses[tech.color],
          ]"
        >
          {{ tech.name }}
        </span>
      </div>
    </div>
  </BentoCard>
</template>
<script setup lang="ts">
import BentoCard from './BentoCard.vue';

const techStack = [
  { name: 'Vue3', color: 'rose' },
  { name: 'React19', color: 'teal' },
  { name: 'Postgres@18', color: 'indigo' },
  { name: 'FastAPI', color: 'indigo' },
  { name: 'Redis8', color: 'teal' },
  { name: 'MongoDB', color: 'fuchsia' },
  { name: 'Golang', color: 'blue' },
];

const colorClasses: Record<string, string> = {
  green:
    'bg-success/15 text-success hover:bg-success/25 dark:bg-success/10 dark:text-success dark:hover:bg-success/20',
  rose: 'bg-destructive/15 text-destructive hover:bg-destructive/25 dark:bg-destructive/10 dark:text-destructive dark:hover:bg-destructive/20',
  teal: 'bg-chart-2/15 text-chart-2 hover:bg-chart-2/25 dark:bg-chart-2/10 dark:text-chart-2 dark:hover:bg-chart-2/20',
  indigo:
    'bg-chart-3/15 text-chart-3 hover:bg-chart-3/25 dark:bg-chart-3/10 dark:text-chart-3 dark:hover:bg-chart-3/20',
  cyan: 'bg-chart-1/15 text-chart-1 hover:bg-chart-1/25 dark:bg-chart-1/10 dark:text-chart-1 dark:hover:bg-chart-1/20',
  fuchsia:
    'bg-chart-5/15 text-chart-5 hover:bg-chart-5/25 dark:bg-chart-5/10 dark:text-chart-5 dark:hover:bg-chart-5/20',
  blue: 'bg-chart-4/15 text-chart-4 hover:bg-chart-4/25 dark:bg-chart-4/10 dark:text-chart-4 dark:hover:bg-chart-4/20',
};
</script>

// react-app/src/views/Home/components/BentoTech.tsx
import { BentoCard } from '@/components/bento/BentoCard';

export function BentoTech() {
  const techStack = [
    { name: 'Python', color: 'blue' },
    { name: 'TS', color: 'yellow' },
    { name: 'TaskIQ', color: 'green' },
    { name: 'Vue3', color: 'rose' },
    { name: 'Motion', color: 'teal' },
    { name: 'TailwindCSS', color: 'purple' },
    { name: 'PostgreSQL', color: 'indigo' },
    { name: 'SQLAlchemy', color: 'cyan' },
    { name: 'FastAPI', color: 'indigo' },
    { name: 'Redis', color: 'teal' },
    { name: 'MongoDB', color: 'fuchsia' },
    { name: 'React', color: 'blue' },
  ];

  const colorClasses: Record<string, string> = {
    blue: 'border-blue-200 bg-blue-100 text-blue-700 hover:bg-blue-200 dark:border-blue-800 dark:bg-blue-900/30 dark:text-blue-300 dark:hover:bg-blue-900/50',
    yellow:
      'border-yellow-200 bg-yellow-100 text-yellow-700 hover:bg-yellow-200 dark:border-yellow-800 dark:bg-yellow-900/30 dark:text-yellow-300 dark:hover:bg-yellow-900/50',
    green:
      'border-green-200 bg-green-100 text-green-700 hover:bg-green-200 dark:border-green-800 dark:bg-green-900/30 dark:text-green-300 dark:hover:bg-green-900/50',
    rose: 'border-rose-200 bg-rose-100 text-rose-700 hover:bg-rose-200 dark:border-rose-800 dark:bg-rose-900/30 dark:text-rose-300 dark:hover:bg-rose-900/50',
    teal: 'border-teal-200 bg-teal-100 text-teal-700 hover:bg-teal-200 dark:border-teal-800 dark:bg-teal-900/30 dark:text-teal-300 dark:hover:bg-teal-900/50',
    purple:
      'border-purple-200 bg-purple-100 text-purple-700 hover:bg-purple-200 dark:border-purple-800 dark:bg-purple-900/30 dark:text-purple-300 dark:hover:bg-purple-900/50',
    indigo:
      'border-indigo-200 bg-indigo-100 text-indigo-700 hover:bg-indigo-200 dark:border-indigo-800 dark:bg-indigo-900/30 dark:text-indigo-300 dark:hover:bg-indigo-900/50',
    cyan: 'border-cyan-200 bg-cyan-100 text-cyan-700 hover:bg-cyan-200 dark:border-cyan-800 dark:bg-cyan-900/30 dark:text-cyan-300 dark:hover:bg-cyan-900/50',
    fuchsia:
      'border-fuchsia-200 bg-fuchsia-100 text-fuchsia-700 hover:bg-fuchsia-200 dark:border-fuchsia-800 dark:bg-fuchsia-900/30 dark:text-fuchsia-300 dark:hover:bg-fuchsia-900/50',
  };

  return (
    <BentoCard>
      <div className="squircle p-2">
        <h3 className="mb-4 flex items-center gap-2 font-serif text-sm font-bold text-slate-800 dark:text-slate-200">
          <svg
            className="h-5 w-5 text-indigo-500"
            fill="none"
            viewBox="0 0 24 24"
            stroke="currentColor"
          >
            <path
              strokeLinecap="round"
              strokeLinejoin="round"
              strokeWidth="2"
              d="M8 9l3 3-3 3m5 0h3M5 20h14a2 2 0 002-2V6a2 2 0 00-2-2H5a2 2 0 00-2 2v12a2 2 0 002 2z"
            />
          </svg>
          Tech Stack
        </h3>
        <div className="flex flex-wrap gap-2">
          {techStack.map((tech) => (
            <span
              key={tech.name}
              className={`cursor-default rounded-full border px-3 py-1.5 text-xs font-semibold transition-colors ${colorClasses[tech.color]}`}
            >
              {tech.name}
            </span>
          ))}
        </div>
      </div>
    </BentoCard>
  );
}
