// frontend/src/views/entry/components/BentoClock.vue
<template>
  <BentoCard class="flex w-64 flex-col items-center justify-center">
    <p class="text-muted-foreground text-sm font-medium tracking-wider">
      {{ dateLabel }}
    </p>
    <p class="text-primary mt-2 font-mono text-6xl font-bold tracking-tight">
      {{ timeLabel }}
    </p>
    <p class="text-muted-foreground mt-1 text-sm">
      {{ weekdayLabel }}
    </p>
  </BentoCard>
</template>

<script setup lang="ts">
import BentoCard from "@/components/bento/BentoCard.vue";
import { useNow } from "@vueuse/core";
import dayjs from "dayjs";
import { computed } from "vue";

// Updates every 1000ms (1 second)
const now = useNow({ interval: 1000 });

const timeLabel = computed(() => dayjs(now.value).format("HH:mm"));
const dateLabel = computed(() => dayjs(now.value).format("YYYY-MM-DD"));
const weekdayLabel = computed(() => dayjs(now.value).format("dddd"));
</script>

// react-app/src/views/Home/components/BentoClock.tsx
import dayjs from 'dayjs';
import { useEffect, useState } from 'react';

export function BentoClock() {
  const [timeLabel, setTimeLabel] = useState<string>('--:--');
  const [dateLabel, setDateLabel] = useState<string>('');

  useEffect(() => {
    const updateTime = () => {
      const now = dayjs();
      setTimeLabel(now.format('HH:mm'));
      setDateLabel(now.format('YYYY-MM-DD'));
    };

    updateTime();
    const timerId = setInterval(updateTime, 1000);
    return () => clearInterval(timerId);
  }, []);

  return (
    <div className="flex items-center justify-between px-2">
      {/* 左侧：日期 */}
      <span className="text-muted-foreground text-sm font-medium">
        {dateLabel}
      </span>

      {/* 右侧：大数字时间 */}
      <span className="text-foreground font-serif text-2xl font-extrabold tracking-tight tabular-nums">
        {timeLabel}
      </span>
    </div>
  );
}
