// frontend/src/components/bento/BentoMap.vue
<template>
  <BentoCard :initial="{ scale: 0 }" :animate="{ scale: 1 }" class="min-w-0">
    <div class="flex min-w-0 flex-col items-center justify-center gap-2 sm:flex-row sm:gap-0">
      <div
        class="flex h-12 w-12 items-center justify-center rounded-full bg-blue-100 dark:bg-blue-900/40"
      >
        <IconGlobal class="size-6 text-blue-500 sm:mr-2" />
      </div>
      <RouterLink
        to="/fishing-map"
        class="max-w-full truncate font-serif text-sm text-gray-800 sm:text-xl dark:text-white"
        >MyFishingMAP</RouterLink
      >
    </div>
  </BentoCard>
</template>

<script setup lang="ts">
import IconGlobal from "../icons/IconGlobal.vue";
import BentoCard from "./BentoCard.vue";
</script>

// react-app/src/views/Home/components/BentoMap.tsx
import { BentoCard } from '@/components/bento/BentoCard';
import { Earth } from 'lucide-react';
import { Link } from 'react-router-dom';

export function BentoMap() {
  return (
    <Link to="/fishing-map" className="group block h-full">
      <BentoCard className="min-w-0 cursor-pointer">
        <div className="min-w-0 flex flex-col items-start justify-between gap-3">
          <div className="flex items-center gap-3">
            <div className="flex h-12 w-12 items-center justify-center rounded-full bg-blue-100 dark:bg-blue-900/40">
              <Earth className="size-6 text-blue-500" />
            </div>
            <span className="max-w-full truncate font-serif text-gray-800 dark:text-white">
              MyFishMap
            </span>
          </div>
          <div className="flex justify-start">
            <span className="text-xs text-blue-500 dark:text-blue-400">
              Open <span aria-hidden="true">→</span>
            </span>
          </div>
        </div>
      </BentoCard>
    </Link>
  );
}
