// frontend/src/views/entry/components/BentoMap.vue
<template>
  <BentoCard :initial="{ scale: 0 }" :animate="{ scale: 1 }" class="min-w-0">
    <div class="flex min-w-0 flex-col items-center justify-center gap-2 sm:flex-row sm:gap-0">
      <div class="flex h-12 w-12 items-center justify-center rounded-full bg-blue-100 dark:bg-blue-900/40">
        <FishingRod class="size-6 text-blue-500" />
      </div>
      <RouterLink
        to="/fishing-map"
        class="max-w-full truncate font-serif text-sm text-gray-800 sm:text-xl dark:text-white"
        >我的钓点</RouterLink
      >
    </div>
  </BentoCard>
</template>

<script setup lang="ts">
import BentoCard from "@/components/bento/BentoCard.vue";
import { FishingRod } from "lucide-vue-next";
</script>

// react-app/src/features/home/components/BentoMap.tsx
import { BentoCard } from '@/components/bento/BentoCard';
import { FishingRod } from 'lucide-react';
import { motion } from 'framer-motion';
import { Link } from 'react-router-dom';
import { SPRING } from '@/constants/springs';

export function BentoMap() {
  return (
    <Link to="/fishing-map" className="group block h-full">
      <BentoCard className="h-full min-w-0 cursor-pointer p-5">
        <motion.div
          className="flex h-full flex-col justify-between gap-3"
          whileTap={{ scale: 0.97 }}
          transition={SPRING.snappy}
        >
          <div className="flex items-center gap-3">
            <div className="bg-primary/10 text-primary ring-primary/20 flex size-10 items-center justify-center rounded-2xl ring-1">
              <FishingRod className="size-5" />
            </div>
            <div className="text-foreground font-serif font-medium whitespace-pre">
              我的钓点
            </div>
          </div>
          <div className="text-primary inline-flex items-center gap-1 text-xs font-semibold">
            Open <span aria-hidden="true">→</span>
          </div>
        </motion.div>
      </BentoCard>
    </Link>
  );
}
