// frontend/src/components/bento/BentoClock.vue
<template>
  <BentoCard class="flex flex-col items-center justify-center">
    <p class="text-sm font-medium tracking-wider text-slate-500">
      {{ dateLabel }}
    </p>
    <p class="mt-2 font-mono text-6xl font-bold tracking-tight text-slate-800">
      {{ timeLabel }}
    </p>
    <p class="mt-1 text-sm text-slate-400">
      {{ weekdayLabel }}
    </p>
  </BentoCard>
</template>

<script setup lang="ts">
import { computed } from "vue";
import { useNow } from "@vueuse/core";
import dayjs from "dayjs";
import BentoCard from "./BentoCard.vue";

// Updates every 1000ms (1 second)
const now = useNow({ interval: 1000 });

const timeLabel = computed(() => dayjs(now.value).format("HH:mm:ss"));
const dateLabel = computed(() => dayjs(now.value).format("YYYY-MM-DD"));
const weekdayLabel = computed(() => dayjs(now.value).format("dddd"));
</script>

// react-app/src/features/home/components/BentoClock.tsx
import dayjs from 'dayjs';
import { useEffect, useState } from 'react';

export function BentoClock() {
  const [timeLabel, setTimeLabel] = useState<string>('--:--');
  const [dateLabel, setDateLabel] = useState<string>('');

  useEffect(() => {
    const updateTime = () => {
      const now = dayjs();
      setTimeLabel(now.format('HH:mm'));
      setDateLabel(now.format('YYYY-MM-DD'));
    };

    updateTime();
    const timerId = setInterval(updateTime, 1000);
    return () => clearInterval(timerId);
  }, []);

  return (
    <div className="flex items-center justify-between px-2">
      {/* 左侧：日期 */}
      <span className="text-muted text-sm font-medium">{dateLabel}</span>

      {/* 右侧：大数字时间 */}
      <span className="text-ink font-serif text-2xl font-extrabold tracking-tight tabular-nums">
        {timeLabel}
      </span>
    </div>
  );
}
