// frontend/src/views/moments/components/MomentCard.vue
<template>
  <motion.article
    :initial="{ opacity: 0, y: 16 }"
    :whileInView="{ opacity: 1, y: 0 }"
    :viewport="{ once: true, margin: '-40px' }"
    :transition="{ type: 'spring', stiffness: 280, damping: 24 }"
    class="relative"
  >
    <div
      role="button"
      tabindex="0"
      :class="[
        'group relative block cursor-pointer overflow-hidden rounded-2xl border px-5 py-5 shadow-sm transition-all duration-300 ease-out focus-visible:outline-none',
        'hover:-translate-y-0.5 hover:shadow-md',
        'focus-visible:ring-ring focus-visible:ring-2 focus-visible:ring-offset-2',
        moment.is_pinned
          ? 'bg-warning/8 border-warning/30'
          : 'bg-background border-border/40 hover:border-primary/25',
      ]"
      @click="emit('open', moment.id)"
      @keydown.enter.prevent="emit('open', moment.id)"
      @keydown.space.prevent="emit('open', moment.id)"
    >
      <!-- 左侧撕纸虚线 -->
      <div
        aria-hidden="true"
        class="border-warning/40 absolute top-3 bottom-3 left-2 border-l border-dashed"
      />

      <!-- 置顶别针徽章 -->
      <span
        v-if="moment.is_pinned"
        class="bg-warning/15 text-warning absolute -top-2 left-3 inline-flex items-center gap-1 rounded-full px-2 py-0.5 text-[10px] font-semibold uppercase tracking-[0.18em] shadow-sm"
      >
        <PinIcon class="h-3 w-3" />
        <span>置顶</span>
      </span>

      <!-- admin 浮动操作（hover 出现，避免抢戏） -->
      <div
        v-if="isAdmin"
        class="absolute top-2 right-2 flex items-center gap-1 opacity-0 transition-opacity duration-200 group-hover:opacity-100 group-focus-within:opacity-100"
        @click.stop
      >
        <button
          type="button"
          class="text-muted-foreground hover:text-primary border-border/40 bg-background/95 inline-flex h-7 w-7 items-center justify-center rounded-full border shadow-sm transition-colors"
          :aria-label="`编辑 ${moment.id}`"
          @click="emit('edit', moment)"
        >
          <EditIcon class="h-3.5 w-3.5" />
        </button>
        <button
          type="button"
          class="text-muted-foreground hover:text-destructive border-border/40 bg-background/95 inline-flex h-7 w-7 items-center justify-center rounded-full border shadow-sm transition-colors"
          :aria-label="`删除 ${moment.id}`"
          @click="emit('delete', moment)"
        >
          <IconDel class="h-3.5 w-3.5" />
        </button>
      </div>

      <!-- 元数据行 -->
      <MomentMeta
        :moment="moment"
        :volume-label="volumeLabel"
        class="relative pl-3"
      />

      <!-- 内容预览（衬线 + 首字下沉） -->
      <p
        class="text-foreground/85 relative mt-2 line-clamp-3 pl-3 font-serif text-[15px] leading-loose"
        style="text-wrap: pretty"
      >
        <span class="moment-drop-cap text-foreground/95">
          {{ moment.content.charAt(0) }}
        </span>
        <span>{{ moment.content.slice(1) }}</span>
      </p>

      <!-- 标签 chip 行 -->
      <div
        v-if="moment.tags.length"
        class="text-muted-foreground relative mt-4 flex flex-wrap items-center gap-x-2 gap-y-1.5 pl-3 text-[11px]"
        @click.stop
      >
        <MomentTagChip v-for="tag in moment.tags" :key="tag" :name="tag" />
      </div>
    </div>
  </motion.article>
</template>

<script setup lang="ts">
import EditIcon from '@/components/icons/EditIcon.vue';
import IconDel from '@/components/icons/IconDel.vue';
import PinIcon from '@/components/icons/PinIcon.vue';
import type { Moment } from '@/types';
import { motion } from 'motion-v';
import MomentMeta from './MomentMeta.vue';
import MomentTagChip from './MomentTagChip.vue';

defineProps<{
  moment: Moment;
  /** 卷序号，例如 "卷十二"；可选 */
  volumeLabel?: string;
  isAdmin?: boolean;
}>();

const emit = defineEmits<{
  (e: 'open', id: string): void;
  (e: 'edit', moment: Moment): void;
  (e: 'delete', moment: Moment): void;
}>();
</script>

<style scoped>
/* 首字下沉：碎碎念卡的核心视觉差异点 */
.moment-drop-cap {
  font-family: serif;
  font-size: 2.4em;
  float: left;
  line-height: 0.9;
  margin: 0.05em 0.12em -0.05em 0;
  font-weight: 600;
}
</style>

// react-app/src/features/moments/components/MomentCard.tsx
import { PinIcon } from '@/components';
import type { Moment } from '@/types';
import { motion } from 'framer-motion';
import { EditIcon, IconDel } from './InlineIcons';
import { MomentMeta } from './MomentMeta';
import { MomentTagChip } from './MomentTagChip';

interface MomentCardProps {
  moment: Moment;
  volumeLabel?: string;
  isAdmin?: boolean;
  onOpen?: (id: string) => void;
  onEdit?: (moment: Moment) => void;
  onDelete?: (moment: Moment) => void;
}

export function MomentCard({
  moment,
  volumeLabel,
  isAdmin = false,
  onOpen,
  onEdit,
  onDelete,
}: MomentCardProps) {
  return (
    <motion.article
      initial={{ opacity: 0, y: 16 }}
      whileInView={{ opacity: 1, y: 0 }}
      viewport={{ once: true, margin: '-40px' }}
      transition={{ type: 'spring', stiffness: 280, damping: 24 }}
      className="relative"
    >
      <div
        role="button"
        tabIndex={0}
        className={[
          'group relative block cursor-pointer overflow-hidden rounded-2xl border px-5 py-5 shadow-sm transition-all duration-300 ease-out focus:outline-none',
          'hover:-translate-y-0.5 hover:shadow-md',
          'focus-visible:ring-ring focus-visible:ring-2 focus-visible:ring-offset-2',
          moment.is_pinned
            ? 'bg-warning/8 border-warning/30'
            : 'bg-background border-border/40 hover:border-primary/25',
        ].join(' ')}
        onClick={() => onOpen?.(moment.id)}
        onKeyDown={(e) => {
          if (e.key === 'Enter' || e.key === ' ') {
            e.preventDefault();
            onOpen?.(moment.id);
          }
        }}
      >
        <div
          aria-hidden="true"
          className="border-warning/40 absolute top-3 bottom-3 left-2 border-l border-dashed"
        />

        {moment.is_pinned && (
          <span className="bg-warning/15 text-warning absolute -top-2 left-3 inline-flex items-center gap-1 rounded-full px-2 py-0.5 text-[10px] font-semibold tracking-[0.18em] uppercase shadow-sm">
            <PinIcon className="h-3 w-3" />
            <span>置顶</span>
          </span>
        )}

        {isAdmin && (
          <div className="absolute top-2 right-2 flex items-center gap-1 opacity-0 transition-opacity duration-200 group-focus-within:opacity-100 group-hover:opacity-100">
            <button
              type="button"
              className="text-muted-foreground hover:text-primary border-border/40 bg-background/95 inline-flex h-7 w-7 items-center justify-center rounded-full border shadow-sm transition-colors"
              aria-label={`编辑 ${moment.id}`}
              onClick={(e) => {
                e.stopPropagation();
                onEdit?.(moment);
              }}
            >
              <EditIcon className="h-3.5 w-3.5" />
            </button>
            <button
              type="button"
              className="text-muted-foreground hover:text-destructive border-border/40 bg-background/95 inline-flex h-7 w-7 items-center justify-center rounded-full border shadow-sm transition-colors"
              aria-label={`删除 ${moment.id}`}
              onClick={(e) => {
                e.stopPropagation();
                onDelete?.(moment);
              }}
            >
              <IconDel className="h-3.5 w-3.5" />
            </button>
          </div>
        )}

        <div className="relative pl-3">
          <MomentMeta moment={moment} volumeLabel={volumeLabel} />
        </div>

        <p
          className="text-foreground/85 relative mt-2 line-clamp-3 pl-3 font-serif text-[15px] leading-loose"
          style={{ textWrap: 'pretty' }}
        >
          <span className="moment-drop-cap text-foreground/95">
            {moment.content.charAt(0)}
          </span>
          <span>{moment.content.slice(1)}</span>
        </p>

        {moment.tags.length > 0 && (
          <div
            className="text-muted-foreground relative mt-4 flex flex-wrap items-center gap-x-2 gap-y-1.5 pl-3 text-[11px]"
            onClick={(e) => e.stopPropagation()}
          >
            {moment.tags.map((tag) => (
              <MomentTagChip key={tag} name={tag} />
            ))}
          </div>
        )}
      </div>

      <style>{`
        .moment-drop-cap {
          font-family: serif;
          font-size: 2.4em;
          float: left;
          line-height: 0.9;
          margin: 0.05em 0.12em -0.05em 0;
          font-weight: 600;
        }
      `}</style>
    </motion.article>
  );
}
