// frontend/src/views/fishing/components/FishingAnalysisDrawer.vue
<script setup lang="ts">
/**
 * AI 智能分析侧边抽屉。
 *
 * 替换原本右下角 FAB + popover 浮层组合:
 * - 桌面/移动统一从右侧滑入,40 vw 宽度
 * - 点击 backdrop 或 ✕ 关闭
 * - 与 Map 的路线浮层在视觉上彻底分离 (一个底部、一个右侧)
 */
import WeatherAnalysis from '@/components/ai/WeatherAnalysis.vue';
import type { WeatherAnalysisPayload } from '@/views/fishing/types';
import { X } from '@lucide/vue';

defineProps<{
  open: boolean;
  payload: WeatherAnalysisPayload | null;
}>();

defineEmits<{
  (e: 'close'): void;
}>();
</script>

<template>
  <Teleport to="body">
    <Transition
      enter-active-class="transition-opacity duration-200 ease-out"
      enter-from-class="opacity-0"
      enter-to-class="opacity-100"
      leave-active-class="transition-opacity duration-150 ease-in"
      leave-from-class="opacity-100"
      leave-to-class="opacity-0"
    >
      <div
        v-if="open"
        class="bg-foreground/20 fixed inset-0 z-40 backdrop-blur-[2px]"
        @click="$emit('close')"
      />
    </Transition>

    <Transition
      enter-active-class="transition-transform duration-300 ease-out"
      enter-from-class="translate-x-full"
      enter-to-class="translate-x-0"
      leave-active-class="transition-transform duration-200 ease-in"
      leave-from-class="translate-x-0"
      leave-to-class="translate-x-full"
    >
      <aside
        v-if="open"
        class="bg-card border-border fixed top-0 right-0 z-50 flex h-screen w-[420px] max-w-[90vw] flex-col border-l shadow-2xl"
        role="dialog"
        aria-label="AI 分析"
      >
        <div
          class="border-border flex items-center justify-between border-b px-5 py-4"
        >
          <div>
            <h3 class="text-foreground font-family-averia text-lg">AI 分析</h3>
            <p class="text-muted-foreground mt-0.5 text-xs">
              基于当前天气与潮汐综合判断
            </p>
          </div>
          <button
            class="text-muted-foreground hover:bg-accent hover:text-accent-foreground inline-flex h-8 w-8 items-center justify-center rounded-full transition-colors"
            type="button"
            aria-label="关闭分析"
            @click="$emit('close')"
          >
            <X class="h-4 w-4" />
          </button>
        </div>

        <div class="flex flex-1 flex-col overflow-y-auto px-5 py-4">
          <WeatherAnalysis :weather_data="payload" :auto-analyze="open" />
        </div>
      </aside>
    </Transition>
  </Teleport>
</template>

// react-app/src/features/fishing/components/FishingAnalysisDrawer.tsx
/**
 * AI 分析 sheet —— 复用 BottomSheet (z-200, 盖在 DashboardSheet 之上)。
 *
 * 桌面端 (≥sm) 退化为右侧抽屉: 自定义 width + 顶部 paper 高光 + 右→左 ambient。
 * 移动端: BottomSheet 默认 bottom-sheet 形态。
 */
import { X } from 'lucide-react';

import { BottomSheet } from '@/components';
import { AIAnalysisWidget } from './AIAnalysisWidget';

interface FishingAnalysisDrawerProps {
  open: boolean;
  onClose: () => void;
  onGenerate: (modelId: string) => void;
}

export function FishingAnalysisDrawer({
  open,
  onClose,
  onGenerate,
}: FishingAnalysisDrawerProps) {
  // 桌面端 (≥sm) → 右侧抽屉样式
  if (typeof window !== 'undefined' && window.matchMedia('(min-width: 640px)').matches) {
    return (
      <BottomSheet
        open={open}
        onClose={onClose}
        maxH="100vh"
        lockScroll
        renderHeader={() => (
          <header className="shrink-0 px-5 pt-3 pb-4">
            <div className="border-border/60 flex items-center justify-between border-b px-0 pb-3">
              <div>
                <h1 className="text-ink font-family-averia text-lg">
                  AI 分析
                </h1>
                <p className="text-muted-foreground mt-0.5 text-xs">
                  基于当前天气与潮汐综合判断
                </p>
              </div>
              <button
                type="button"
                aria-label="关闭分析"
                onClick={onClose}
                className="text-muted-foreground hover:bg-muted hover:text-ink inline-flex h-9 w-9 items-center justify-center rounded-full transition-colors"
              >
                <X className="h-4 w-4" />
              </button>
            </div>
          </header>
        )}
      >
        {/* 桌面右侧抽屉样式 */}
        <style>{`
          [role="dialog"][aria-label="AI 分析"] {
            left: auto !important;
            right: 0 !important;
            top: 0 !important;
            bottom: 0 !important;
            width: 420px;
            max-width: 90vw;
            border-radius: 24px 0 0 24px !important;
            border-left: 1px solid var(--border-color, color-mix(in oklch, var(--ink) 12%, transparent));
            box-shadow:
              inset 1px 0 0 0 oklch(from var(--paper) l c h / 0.6),
              -1px 0 1px color-mix(in oklch, var(--ink) 6%, transparent),
              -8px 0 18px color-mix(in oklch, var(--ink) 8%, transparent),
              -24px 0 40px color-mix(in oklch, var(--ink) 6%, transparent);
          }
        `}</style>
        <div className="flex flex-1 flex-col overflow-y-auto px-5 py-4">
          <AIAnalysisWidget onGenerate={onGenerate} embedded hideFab />
        </div>
      </BottomSheet>
    );
  }

  // 移动端 → BottomSheet 默认 bottom sheet
  return (
    <BottomSheet
      open={open}
      onClose={onClose}
      maxH="70vh"
      lockScroll
      renderHeader={() => (
        <header className="shrink-0 px-5 pt-3 pb-4">
          <div className="border-border/60 flex items-center justify-between border-b px-0 pb-3">
            <div>
              <h2 className="text-ink text-base font-semibold">
                AI 分析
              </h2>
              <p className="text-muted-foreground mt-0.5 text-xs">
                基于当前天气与潮汐综合判断
              </p>
            </div>
            <button
              type="button"
              aria-label="关闭分析"
              onClick={onClose}
              className="text-muted-foreground hover:bg-muted hover:text-ink inline-flex h-9 w-9 items-center justify-center rounded-full transition-colors"
            >
              <X className="h-4 w-4" />
            </button>
          </div>
        </header>
      )}
    >
      <div className="flex flex-col gap-4 px-5 py-4">
        <AIAnalysisWidget onGenerate={onGenerate} embedded hideFab />
      </div>
    </BottomSheet>
  );
}
