// frontend/src/views/fishing/components/QuickFeedbackBanner.vue
<script setup lang="ts">
/**
 * Quick feedback banner —— "钓完了？告诉我们今天实际如何"。
 *
 * 放在 dashboard 顶部 (Map / Index 之上),没有 routeInfo 时显示。
 * 不再用 warning 色调,改成 muted + 主按钮,跟 dashboard 网格协调。
 */
defineProps<{
  visible: boolean;
  disabled?: boolean;
}>();

defineEmits<{
  (e: 'submit'): void;
}>();
</script>

<template>
  <Transition
    enter-active-class="transition-all duration-300 ease-out"
    enter-from-class="opacity-0 -translate-y-1"
    enter-to-class="opacity-100 translate-y-0"
    leave-active-class="transition-all duration-200 ease-in"
    leave-from-class="opacity-100 translate-y-0"
    leave-to-class="opacity-0 -translate-y-1"
  >
    <section
      v-if="visible"
      class="border-border bg-muted/30 flex flex-col items-start gap-3 rounded-2xl border p-4 sm:flex-row sm:items-center sm:justify-between sm:px-5"
    >
      <div>
        <p class="text-foreground font-family-averia text-base italic">
          钓完了？告诉我们今天实际如何
        </p>
        <p class="text-muted-foreground mt-0.5 text-sm">
          三个问题，三十秒——您的反馈会帮系统下次更准
        </p>
      </div>
      <button
        v-if="!disabled"
        class="bg-primary text-primary-foreground hover:bg-primary/90 rounded-lg px-4 py-2 text-sm font-medium whitespace-nowrap transition-colors"
        type="button"
        @click="$emit('submit')"
      >
        反馈今日指数
      </button>
    </section>
  </Transition>
</template>

// react-app/src/features/fishing/components/QuickFeedbackBanner.tsx
/**
 * Quick feedback banner —— "钓完了？告诉我们今天实际如何"。
 *
 * Apple HIG notification card: 凹进 page 一层的圆角容器, 不是顶部 border-t 切割。
 * 副标题 + 单 CTA, 不再叠警告色; 跟 dashboard 节奏保持一致。
 */
import { motion } from 'framer-motion';

interface QuickFeedbackBannerProps {
  visible: boolean;
  disabled?: boolean;
  onSubmit: () => void;
}

export function QuickFeedbackBanner({
  visible,
  disabled = false,
  onSubmit,
}: QuickFeedbackBannerProps) {
  if (!visible) return null;

  return (
    <motion.section
      initial={{ opacity: 0, y: -6 }}
      animate={{ opacity: 1, y: 0 }}
      exit={{ opacity: 0, y: -6 }}
      transition={{ duration: 0.28, ease: [0.22, 1, 0.36, 1] }}
      className="fm-grouped flex flex-col items-start gap-3 px-4 py-3 sm:flex-row sm:items-center sm:justify-between sm:px-5 sm:py-4"
      aria-label="反馈今日指数"
    >
      <div className="min-w-0 flex-1">
        <p className="text-ink font-family-averia text-base">
          钓完了？告诉我们今天实际如何
        </p>
        <p className="text-muted-foreground mt-0.5 text-xs">
          三个问题，三十秒 —— 您的反馈会帮系统下次更准
        </p>
      </div>
      <button
        type="button"
        disabled={disabled}
        onClick={onSubmit}
        className="bg-accent text-accent hover:bg-accent/90 disabled:bg-muted disabled:text-muted-foreground min-h-10 shrink-0 rounded-full px-4 py-2 text-sm font-medium whitespace-nowrap transition-colors disabled:cursor-not-allowed sm:min-h-11 sm:px-5"
      >
        反馈今日指数
      </button>
    </motion.section>
  );
}
