// frontend/src/features/fishing/components/TideCard.vue
<script setup lang="ts">
import { useChartColors, withAlpha } from '@/composables';
import {
  HARBOR_OPTIONS,
  useTidePanelStore,
} from '@/features/fishing/stores/tidePanel';
import DashboardCard from './DashboardCard.vue';
import dayjs from 'dayjs';
import { storeToRefs } from 'pinia';
import { computed, onMounted } from 'vue';
import VChart from 'vue-echarts';

const tidePanelStore = useTidePanelStore();
const {
  panelTideData,
  tideLoading,
  selectedHarbor: selectedHarborState,
  selectedDate: selectedDateState,
  panelTideSpotName,
} = storeToRefs(tidePanelStore);

const tideData = computed(() => panelTideData.value);
const loading = computed(() => tideLoading.value);
const tideSpotName = computed(() => panelTideSpotName.value);
const { palette } = useChartColors();

const selectedHarbor = computed({
  get: () => selectedHarborState.value,
  set: (value: string) => tidePanelStore.setSelectedHarbor(value),
});
const selectedDate = computed({
  get: () => selectedDateState.value,
  set: (value: string) => tidePanelStore.setSelectedDate(value),
});

const dateOptions = computed(() =>
  Array(8)
    .fill(null)
    .map((_, i) => {
      const d = dayjs().add(i, 'day');
      return {
        value: d.format('YYYYMMDD'),
        label: d.format('MM-DD'),
        weekday: d.format('dd'),
      };
    }),
);

const todayStr = computed(() => {
  const opt = dateOptions.value.find((o) => o.value === selectedDate.value);
  return opt ? `${opt.label} ${opt.weekday}` : dayjs().format('YYYY-MM-DD');
});

const highTide = computed(() => {
  if (!tideData.value) return null;
  const highs = tideData.value.tideTable.filter((t) => t.type === 'H');
  if (highs.length === 0) return null;
  const maxEntry = highs.reduce((acc, h) =>
    Number(h.height) > Number(acc.height) ? h : acc,
  );
  return {
    height: Number(maxEntry.height),
    time: dayjs(maxEntry.fxTime).format('HH:mm'),
    fxTime: maxEntry.fxTime,
  };
});

const lowTide = computed(() => {
  if (!tideData.value) return null;
  const lows = tideData.value.tideTable.filter((t) => t.type === 'L');
  if (lows.length === 0) return null;
  const minEntry = lows.reduce((acc, l) =>
    Number(l.height) < Number(acc.height) ? l : acc,
  );
  return {
    height: Number(minEntry.height),
    time: dayjs(minEntry.fxTime).format('HH:mm'),
    fxTime: minEntry.fxTime,
  };
});

/** 把 fxTime ISO 字符串映射到 tideHourly 数组中最近的 index,供 markPoint 用 */
function findHourlyIndex(targetFxTime: string | undefined): number {
  if (!tideData.value || !targetFxTime) return -1;
  const target = dayjs(targetFxTime).valueOf();
  let bestIdx = -1;
  let bestDelta = Infinity;
  tideData.value.tideHourly.forEach((pt, idx) => {
    const delta = Math.abs(dayjs(pt.fxTime).valueOf() - target);
    if (delta < bestDelta) {
      bestDelta = delta;
      bestIdx = idx;
    }
  });
  return bestIdx;
}

const tideOptions = computed(() => {
  if (!tideData.value) return {};
  const p = palette.value;

  const hourly = tideData.value.tideHourly;
  const now = dayjs();
  let currentTimeIndex = -1;
  hourly.forEach((point, index) => {
    const pointTime = dayjs(point.fxTime);
    if (pointTime.isBefore(now) || pointTime.isSame(now)) {
      currentTimeIndex = index;
    }
  });

  // markPoint data 数组:把当日的高潮 / 低潮标到曲线上
  const markPointData: Array<{
    name: string;
    value: string;
    coord: [number, number];
    itemStyle: { color: string };
  }> = [];
  if (highTide.value) {
    const idx = findHourlyIndex(highTide.value.fxTime);
    if (idx >= 0) {
      markPointData.push({
        name: `高潮 ${highTide.value.time}`,
        value: `${highTide.value.height.toFixed(2)}m`,
        coord: [idx, highTide.value.height],
        itemStyle: { color: p.warning },
      });
    }
  }
  if (lowTide.value) {
    const idx = findHourlyIndex(lowTide.value.fxTime);
    if (idx >= 0) {
      markPointData.push({
        name: `低潮 ${lowTide.value.time}`,
        value: `${lowTide.value.height.toFixed(2)}m`,
        coord: [idx, lowTide.value.height],
        itemStyle: { color: p.primary },
      });
    }
  }

  return {
    backgroundColor: 'transparent',
    // 关键:禁用 animation 避免 setOption 时 echarts interpolate1DArray 崩
    // (3-stop 渐变 + markPoint pin coord 都参与动画时容易出问题)
    animation: false,
    tooltip: {
      trigger: 'axis',
      backgroundColor: p.card,
      borderColor: p.border,
      borderWidth: 1,
      borderRadius: 10,
      padding: [10, 14],
      textStyle: { color: p.foreground, fontSize: 12 },
      formatter: (params: unknown) => {
        const arr = params as Array<{ axisValue: string; data: number }>;
        const param = arr[0];
        if (!param) return '';
        const timeStr = dayjs(param.axisValue).format('HH:mm');
        return `<div style="padding:2px 0;">
          <div style="font-weight:600;margin-bottom:4px;font-size:11px;color:${p.mutedForeground};">${timeStr}</div>
          <div>潮高 <span style="color:${p.primary};font-weight:700;margin-left:8px;">${param.data.toFixed(2)} m</span></div>
        </div>`;
      },
    },
    grid: { left: 8, right: 8, top: 28, bottom: 8, containLabel: true },
    xAxis: {
      type: 'category',
      data: hourly.map((point) => point.fxTime),
      axisLabel: {
        formatter: (value: string) => dayjs(value).format('HH:mm'),
        color: p.mutedForeground,
        fontSize: 10,
        interval: Math.max(0, Math.floor(hourly.length / 6) - 1),
      },
      axisLine: { lineStyle: { color: p.border } },
      axisTick: { show: false },
      splitLine: { show: false },
      boundaryGap: false,
    },
    yAxis: {
      type: 'value',
      splitNumber: 3,
      axisLabel: {
        color: p.mutedForeground,
        fontSize: 10,
        formatter: (v: number) => `${v}m`,
      },
      axisLine: { show: false },
      axisTick: { show: false },
      splitLine: {
        lineStyle: { color: p.border, type: 'dashed', opacity: 0.5 },
      },
    },
    series: [
      {
        name: '潮高',
        data: hourly.map((point) => Number(point.height)),
        type: 'line',
        smooth: 0.4,
        symbol: 'none',
        lineStyle: { color: p.primary, width: 2.5 },
        itemStyle: { color: p.primary },
        // hover 时 echarts 6 默认会把 series 切到 emphasis,把面积 + markPoint
        // 推到 blur 态(opacity 接近 0),整张图看似变白消失。显式禁用 emphasis
        // 并把 blur 锁回原透明度,确保 hover 时图形保持稳定
        emphasis: { disabled: true },
        blur: {
          areaStyle: { opacity: 1 },
          itemStyle: { opacity: 1 },
          lineStyle: { opacity: 1 },
        },
        areaStyle: {
          color: {
            type: 'linear',
            x: 0,
            y: 0,
            x2: 0,
            y2: 1,
            colorStops: [
              { offset: 0, color: withAlpha(p.primary, 0.18) },
              { offset: 0.7, color: withAlpha(p.primary, 0.04) },
              { offset: 1, color: withAlpha(p.primary, 0) },
            ],
          },
        },
        markLine:
          currentTimeIndex >= 0
            ? {
                symbol: ['none', 'none'],
                lineStyle: { color: p.warning, type: 'dashed', width: 1 },
                label: {
                  show: true,
                  formatter: '现在',
                  color: p.warning,
                  fontWeight: 600,
                  fontSize: 10,
                  position: 'insideEndTop',
                },
                data: [{ xAxis: currentTimeIndex }],
              }
            : undefined,
        markPoint: {
          symbol: 'circle',
          symbolSize: 9,
          data: markPointData,
          // dot 风格:实心圆 + 卡片色描边,hover 时的数据走 tooltip 不走 label,
          // 避免在曲线上叠一个大标签挡住波形
          itemStyle: {
            borderColor: p.card,
            borderWidth: 2,
          },
          label: { show: false },
        },
      },
    ],
  };
});

onMounted(() => {
  if (!panelTideData.value) {
    void tidePanelStore.fetchPanelTide(
      selectedHarborState.value,
      selectedDateState.value,
    );
  }
});
</script>

<template>
  <DashboardCard>
    <!-- Header -->
    <div class="mb-4 flex items-start justify-between gap-2">
      <div class="min-w-0">
        <h3 class="text-ink text-lg font-semibold tracking-tight">潮汐预报</h3>
        <p class="text-muted mt-0.5 truncate text-sm">
          {{ tideSpotName }} · {{ todayStr }}
        </p>
      </div>
      <div class="flex shrink-0 items-center gap-1.5">
        <select
          v-model="selectedHarbor"
          aria-label="选择港口"
          class="border-border bg-paper text-ink focus:ring-accent cursor-pointer rounded-lg border px-1.5 py-1 text-xs focus:ring-1 focus:outline-none"
        >
          <option
            v-for="opt in HARBOR_OPTIONS"
            :key="opt.code"
            :value="opt.code"
          >
            {{ opt.name }}
          </option>
        </select>
        <select
          v-model="selectedDate"
          aria-label="选择日期"
          class="border-border bg-paper text-ink focus:ring-accent cursor-pointer rounded-lg border px-1.5 py-1 text-xs focus:ring-1 focus:outline-none"
        >
          <option
            v-for="opt in dateOptions"
            :key="opt.value"
            :value="opt.value"
          >
            {{ opt.label }} {{ opt.weekday }}
          </option>
        </select>
      </div>
    </div>

    <!-- Loading -->
    <div
      v-if="loading"
      class="flex flex-1 flex-col items-center justify-center py-12"
    >
      <div
        class="border-border border-t-accent h-10 w-10 animate-spin rounded-full border-2"
      />
      <span class="text-muted mt-3 text-sm">获取潮汐数据...</span>
    </div>

    <!-- Chart -->
    <div v-else-if="tideData">
      <v-chart
        :option="tideOptions"
        style="width: 100%; height: 240px"
        autoresize
      />

      <div class="mt-3 grid grid-cols-2 gap-3">
        <div class="bg-warning/10 border-warning/20 rounded-xl border p-3">
          <div class="flex items-baseline justify-between gap-2">
            <p class="text-warning text-xs font-medium">最高潮</p>
            <p class="text-muted text-xs tabular-nums">
              {{ highTide?.time ?? '--:--' }}
            </p>
          </div>
          <p class="text-ink mt-1 text-base font-semibold tabular-nums">
            {{ highTide ? highTide.height.toFixed(2) : '--' }} m
          </p>
        </div>

        <div class="bg-accent/10 border-accent/20 rounded-xl border p-3">
          <div class="flex items-baseline justify-between gap-2">
            <p class="text-accent text-xs font-medium">最低潮</p>
            <p class="text-muted text-xs tabular-nums">
              {{ lowTide?.time ?? '--:--' }}
            </p>
          </div>
          <p class="text-ink mt-1 text-base font-semibold tabular-nums">
            {{ lowTide ? lowTide.height.toFixed(2) : '--' }} m
          </p>
        </div>
      </div>
    </div>

    <!-- 空态 -->
    <div v-else class="flex flex-1 flex-col items-center justify-center py-8">
      <div
        class="bg-muted mb-3 flex h-12 w-12 items-center justify-center rounded-2xl"
      >
        <svg
          xmlns="http://www.w3.org/2000/svg"
          class="text-muted h-6 w-6"
          fill="none"
          viewBox="0 0 24 24"
          stroke="currentColor"
        >
          <path
            stroke-linecap="round"
            stroke-linejoin="round"
            stroke-width="2"
            d="M13 16h-1v-4h-1m1-4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z"
          />
        </svg>
      </div>
      <p class="text-ink text-sm">暂无潮汐数据</p>
    </div>
  </DashboardCard>
</template>

// react-app/src/features/fishing/components/TideCard.tsx
import { useEffect, useMemo } from 'react';

import dayjs from 'dayjs';

import { HARBOR_OPTIONS, useFishingMapStore } from '@/features/fishing/stores/fishingMapStore';
import { useChartTheme, withAlpha } from '../hooks/useChartTheme';
import type { TideTableItem } from '../types';
import { SkeletonCard } from './SkeletonCard';
import { TideChart } from './TideChart';

/**
 * TideCard — Apple HIG 信息架构:
 *   港口 SegmentedControl (5 项, 一行内可选)
 *   日期 scroll chips (8 日, 横向滚动)
 *   潮汐曲线 (ECharts, theme-aware)
 *   高潮 / 低潮 inset-grouped 双列
 */
export function TideCard() {
  const {
    panelTideData: tideData,
    tideLoading: loading,
    selectedHarbor,
    selectedDate,
    setSelectedHarbor,
    setSelectedDate,
    fetchPanelTide,
  } = useFishingMapStore();

  const theme = useChartTheme();

  useEffect(() => {
    fetchPanelTide();
  }, [selectedHarbor, selectedDate, fetchPanelTide]);

  // 今日 ~ +7天
  const dateOptions = Array(8)
    .fill(null)
    .map((_, i) => {
      const d = dayjs().add(i, 'day');
      return {
        value: d.format('YYYYMMDD'),
        label: d.format('MM-DD'),
        weekday: d.format('dd'),
      };
    });

  const highTide = useMemo<TideTableItem | null>(() => {
    if (!tideData?.tideTable?.length) return null;
    const highs = tideData.tideTable.filter((item) => item.type === 'H');
    if (!highs.length) return null;
    return highs.reduce((prev, curr) =>
      Number(curr.height) > Number(prev.height) ? curr : prev,
    );
  }, [tideData]);

  const lowTide = useMemo<TideTableItem | null>(() => {
    if (!tideData?.tideTable?.length) return null;
    const lows = tideData.tideTable.filter((item) => item.type === 'L');
    if (!lows.length) return null;
    return lows.reduce((prev, curr) =>
      Number(curr.height) < Number(prev.height) ? curr : prev,
    );
  }, [tideData]);

  const tideChartOption = useMemo(() => {
    // 始终返回 well-formed option (即便没有数据),
    // 避免 zrender 在动画插值时撞到 undefined 数组 (graphic.js:4601 interpolate1DArray)
    if (!tideData) {
      return {
        animation: false,
        series: [],
      };
    }

    const now = dayjs();
    let currentTimeIndex = -1;
    tideData.tideHourly.forEach((point, index) => {
      const pointTime = dayjs(point.fxTime);
      if (pointTime.isBefore(now) || pointTime.isSame(now)) {
        currentTimeIndex = index;
      }
    });

    return {
      animation: false,
      tooltip: {
        trigger: 'axis',
        backgroundColor: theme.paper,
        borderColor: theme.border,
        borderWidth: 1,
        borderRadius: 12,
        padding: [10, 14],
        textStyle: { color: theme.ink, fontSize: 13 },
        formatter: (params: unknown[]) => {
          const param = params[0] as { axisValue: string; data: number };
          return `<div style="padding:2px 0;">
          <div style="font-weight:600;margin-bottom:4px;">${param.axisValue}</div>
          <div>潮高: <span style="color:${theme.tide};font-weight:bold;">${param.data.toFixed(2)} m</span></div>
        </div>`;
        },
      },
      grid: { left: '4%', right: '4%', bottom: '12%', top: '10%' },
      xAxis: {
        type: 'category',
        data: tideData.tideHourly.map((point) =>
          dayjs(point.fxTime).format('HH:mm'),
        ),
        axisLabel: {
          color: theme.muted,
          fontSize: 11,
          formatter: (value: string) => value.slice(11, 16),
          interval: Math.max(1, Math.floor(tideData.tideHourly.length / 5)),
        },
        axisLine: { lineStyle: { color: theme.border } },
        axisTick: { show: false },
      },
      yAxis: {
        type: 'value',
        axisLabel: {
          color: theme.muted,
          fontSize: 11,
          formatter: (value: number) => `${value}m`,
        },
        axisLine: { show: false },
        axisTick: { show: false },
        splitLine: {
          lineStyle: { color: withAlpha(theme.border, 0.6), type: 'dashed' },
        },
      },
      series: [
        {
          data: tideData.tideHourly.map((point) => Number(point.height)),
          type: 'line',
          smooth: 0.4,
          symbol: 'none',
          lineStyle: { color: theme.tide, width: 2.5 },
          areaStyle: {
            color: {
              type: 'linear',
              x: 0,
              y: 0,
              x2: 0,
              y2: 1,
              colorStops: [
                { offset: 0, color: withAlpha(theme.tide, 0.24) },
                { offset: 0.7, color: withAlpha(theme.tide, 0.05) },
                { offset: 1, color: withAlpha(theme.tide, 0) },
              ],
            },
          },
          markLine:
            currentTimeIndex >= 0
              ? {
                  symbol: ['none', 'none'],
                  lineStyle: {
                    color: theme.warning,
                    type: 'dashed',
                    width: 1.5,
                  },
                  label: {
                    show: true,
                    formatter: '现在',
                    color: theme.warning,
                    fontWeight: '600',
                    fontSize: 12,
                  },
                  data: [{ xAxis: currentTimeIndex }],
                }
              : undefined,
        },
      ],
      textStyle: { color: theme.ink },
    };
  }, [theme, tideData]);

  return (
    <article className="px-1 pt-2 pb-6" aria-label="潮汐预报">
      <div className="mb-3">
        <h3 className="text-ink text-sm font-semibold">潮汐预报</h3>
      </div>

      {/* Harbor — Apple HIG Segmented Control (5 项, 一行) */}
      <div className="fm-segmented mb-2 w-full overflow-x-auto" role="tablist">
        {HARBOR_OPTIONS.map((opt) => {
          const isActive = selectedHarbor === opt.code;
          return (
            <button
              key={opt.code}
              type="button"
              role="tab"
              aria-selected={isActive}
              onClick={() => setSelectedHarbor(opt.code)}
              className={`min-h-8 flex-1 shrink-0 rounded-md px-3 text-xs font-medium transition-all duration-200 ease-out ${
                isActive
                  ? 'bg-paper text-ink shadow-sm'
                  : 'text-muted-foreground hover:text-ink'
              }`}
            >
              {opt.name}
            </button>
          );
        })}
      </div>

      {/* Date — Apple HIG scroll chips (8 日, 横向滚动) */}
      <div className="fm-hscroll -mx-1 mb-4 flex gap-1.5 px-1">
        {dateOptions.map((opt) => {
          const isActive = selectedDate === opt.value;
          return (
            <button
              key={opt.value}
              type="button"
              onClick={() => setSelectedDate(opt.value)}
              className={`min-h-9 shrink-0 rounded-full px-3 text-xs font-medium transition-colors ${
                isActive
                  ? 'bg-accent text-accent'
                  : 'bg-muted text-ink hover:bg-muted/70'
              }`}
            >
              {opt.label} {opt.weekday}
            </button>
          );
        })}
      </div>

      {loading ? (
        <div className="min-h-[260px]">
          <SkeletonCard hasChart hasBottomRow />
        </div>
      ) : tideData ? (
        <div className="min-h-[260px] space-y-4">
          <div className="h-[200px]">
            <TideChart option={tideChartOption} />
          </div>
          {/* High / low tide — Apple HIG inset-grouped 双列 */}
          <div className="fm-grouped grid grid-cols-2 gap-px bg-border/40">
            <div className="bg-paper flex flex-col gap-1 px-4 py-3">
              <span className="text-muted-foreground text-xs font-medium">
                最高潮
                <span className="text-ink ml-1.5 tabular-nums">
                  {highTide ? dayjs(highTide.fxTime).format('HH:mm') : '--'}
                </span>
              </span>
              <span className="text-ink text-sm font-semibold tabular-nums">
                {highTide ? Number(highTide.height).toFixed(2) : '--'} m
              </span>
            </div>
            <div className="bg-paper flex flex-col gap-1 px-4 py-3">
              <span className="text-muted-foreground text-xs font-medium">
                最低潮
                <span className="text-ink ml-1.5 tabular-nums">
                  {lowTide ? dayjs(lowTide.fxTime).format('HH:mm') : '--'}
                </span>
              </span>
              <span className="text-ink text-sm font-semibold tabular-nums">
                {lowTide ? Number(lowTide.height).toFixed(2) : '--'} m
              </span>
            </div>
          </div>
        </div>
      ) : (
        <div className="min-h-[260px]">
          <p className="text-muted-foreground text-sm">暂无潮汐数据</p>
        </div>
      )}
    </article>
  );
}
