// react-app/src/components/ui/BackToTop.tsx
import { AnimatePresence, motion } from 'framer-motion';
import { useEffect, useRef, useState } from 'react';

interface BackToTopProps {
  className?: string;
}

export function BackToTop({ className }: BackToTopProps) {
  const [isVisible, setIsVisible] = useState(false);
  const [progress, setProgress] = useState(0); // 0..1
  const rafRef = useRef<number | null>(null);

  const backToTop = () => {
    window.scrollTo({ top: 0, behavior: 'smooth' });
  };

  const updateScroll = () => {
    const scrollTop = window.scrollY;
    const docHeight =
      document.documentElement.scrollHeight - window.innerHeight;
    const pct = docHeight > 0 ? Math.min(1, scrollTop / docHeight) : 0;
    // console.log(
    //   `scrollTop: ${scrollTop}, docHeight: ${docHeight}, pct: ${pct}`,
    // );
    setProgress(pct);
    setIsVisible(scrollTop > 300);
  };

  // 使用 requestAnimationFrame 节流，确保每帧只更新一次
  const onScroll = () => {
    if (rafRef.current !== null) return;
    rafRef.current = requestAnimationFrame(() => {
      updateScroll();
      rafRef.current = null;
    });
  };

  useEffect(() => {
    // eslint-disable-next-line react-hooks/set-state-in-effect
    updateScroll();
    window.addEventListener('scroll', onScroll, { passive: true });
    window.addEventListener('resize', onScroll);
    return () => {
      window.removeEventListener('scroll', onScroll);
      window.removeEventListener('resize', onScroll);
    };
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  const radius = 26;
  const circumference = 2 * Math.PI * radius;
  const offset = circumference * (1 - progress);

  return (
    <>
      <AnimatePresence>
        {isVisible && (
          <motion.button
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            exit={{ opacity: 0, y: 20 }}
            transition={{ duration: 0.3, ease: 'easeInOut' }}
            onClick={backToTop}
            aria-label="回到顶部"
            title="回到顶部"
            className={`group z-50 flex h-14 w-14 transform-gpu cursor-pointer items-center justify-center overflow-hidden rounded-full shadow-lg backdrop-blur-sm transition-all duration-300 hover:scale-110 hover:shadow-2xl focus:outline-none ${className || 'fixed bottom-[calc(3rem+env(safe-area-inset-bottom,0px))] left-1/2 -translate-x-1/2'}`}
          >
            {/* 背景进度环 */}
            <svg
              className="text-primary absolute inset-0 h-full w-full -rotate-90"
              viewBox="0 0 56 56"
              aria-hidden
            >
              {/* 背景圆环 */}
              <circle
                cx={28}
                cy={28}
                r={radius}
                fill="none"
                stroke="currentColor"
                strokeWidth={2}
                className="text-muted-foreground"
                opacity={0.3}
              />
              {/* 进度圆环 */}
              <circle
                cx={28}
                cy={28}
                r={radius}
                fill="none"
                stroke="currentColor"
                strokeWidth={2}
                strokeLinecap="round"
                strokeDasharray={circumference}
                strokeDashoffset={offset}
                style={{ transition: 'none' }}
              />
            </svg>

            {/* 箭头图标 */}
            <svg
              xmlns="http://www.w3.org/2000/svg"
              className="text-foreground h-6 w-6 transform-gpu transition-transform duration-300"
              fill="none"
              viewBox="0 0 24 24"
              stroke="currentColor"
              strokeWidth={2}
              aria-hidden
            >
              <path
                strokeLinecap="round"
                strokeLinejoin="round"
                d="M5 10l7-7m0 0l7 7m-7-7v18"
              />
            </svg>

            {/* Tooltip */}
            <span className="bg-background text-card-foreground absolute right-full mr-3 rounded-lg px-3 py-1 text-sm whitespace-nowrap opacity-0 transition-opacity duration-200 group-hover:opacity-100">
              回到顶部
              <span className="border-l-card absolute top-1/2 right-0 translate-x-1/2 -translate-y-1/2 border-4 border-transparent"></span>
            </span>
          </motion.button>
        )}
      </AnimatePresence>
    </>
  );
}

// frontend/src/components/BackToTop.vue
<script setup lang="ts">
import { onMounted, onUnmounted, ref } from "vue";

const isVisible = ref(false);
const isHovered = ref(false);
const scrollProgress = ref(0);

const checkScroll = () => {
  // 显示按钮当滚动超过 300px
  isVisible.value = window.scrollY > 300;

  // 计算滚动进度 (0-100)
  const docHeight = document.documentElement.scrollHeight - window.innerHeight;
  scrollProgress.value = docHeight > 0 ? (window.scrollY / docHeight) * 100 : 0;
};

const scrollToTop = () => {
  window.scrollTo({
    top: 0,
    behavior: "smooth",
  });
};

onMounted(() => {
  window.addEventListener("scroll", checkScroll, { passive: true });
  checkScroll();
});

onUnmounted(() => {
  window.removeEventListener("scroll", checkScroll);
});
</script>

<template>
  <transition
    enter-active-class="transition-all transform-gpu duration-300 ease-out"
    enter-from-class="opacity-0 translate-y-10 scale-75"
    enter-to-class="opacity-100 translate-y-0 scale-100"
    leave-active-class="transition-all transform-gpu duration-200 ease-in"
    leave-from-class="opacity-100 translate-y-0 scale-100"
    leave-to-class="opacity-0 translate-y-10 scale-75"
  >
    <button
      v-show="isVisible"
      @click="scrollToTop"
      @mouseenter="isHovered = true"
      @mouseleave="isHovered = false"
      class="animate-bounce-up fixed bottom-16 left-1/2 z-50 flex h-14 w-14 -translate-x-1/2 transform-gpu cursor-pointer items-center justify-center overflow-hidden rounded-full shadow-lg backdrop-blur-sm transition-all duration-300 hover:scale-110 hover:shadow-2xl focus:outline-none"
      :class="[
        isHovered
          ? 'bg-blue-600/30 text-white dark:bg-blue-500/10'
          : 'bg-gray-50/30 text-gray-700 dark:bg-gray-800/10 dark:text-gray-200',
      ]"
      aria-label="回到顶部"
    >
      <!-- 背景进度环 -->
      <svg
        class="absolute inset-0 h-full w-full -rotate-90"
        viewBox="0 0 56 56"
      >
        <!-- 背景圆环 -->
        <circle
          cx="28"
          cy="28"
          r="26"
          fill="none"
          stroke="currentColor"
          stroke-width="2"
          class="text-gray-200 dark:text-gray-700"
          opacity="0.3"
        />
        <!-- 进度圆环 -->
        <circle
          cx="28"
          cy="28"
          r="26"
          fill="none"
          stroke="currentColor"
          stroke-width="2"
          stroke-linecap="round"
          :stroke-dasharray="163.36"
          :stroke-dashoffset="163.36 - (scrollProgress / 100) * 163.36"
          class="transition-all duration-100"
          :class="isHovered ? 'text-white' : 'text-blue-600 dark:text-blue-400'"
        />
      </svg>

      <!-- 箭头图标 -->
      <svg
        xmlns="http://www.w3.org/2000/svg"
        class="h-6 w-6 transform-gpu text-gray-600 transition-transform duration-300 dark:text-gray-300"
        :class="{ '-translate-y-1': isHovered }"
        fill="none"
        viewBox="0 0 24 24"
        stroke="currentColor"
        stroke-width="2"
      >
        <path
          stroke-linecap="round"
          stroke-linejoin="round"
          d="M5 10l7-7m0 0l7 7m-7-7v18"
        />
      </svg>

      <!-- Tooltip -->
      <span
        class="absolute right-full mr-3 rounded-lg bg-gray-900 px-3 py-1 text-sm whitespace-nowrap text-white opacity-0 transition-opacity duration-200 dark:bg-gray-700"
        :class="{ 'opacity-100': isHovered }"
      >
        回到顶部
        <!-- 小箭头 -->
        <span
          class="absolute top-1/2 right-0 translate-x-1/2 -translate-y-1/2 border-4 border-transparent border-l-gray-900 dark:border-l-gray-700"
        ></span>
      </span>
    </button>
  </transition>
</template>
