// react-app/src/views/FishingMap/components/FishingMapTile.tsx
/**
 * Map tile —— dashboard 中的地图卡片。
 *
 * 合并原 MapPanel（map 容器）+ RouteStatusCard（路线信息浮层）。
 *
 * 包含：
 * - 内部 AMap 实例（由 useMap 管理）
 * - 底部浮层（路线规划中 / 路线信息 / 空态提示）
 * - marker click 走 useRouteMapStore.planRouteAction 串行化入口
 *
 * 选择把这一层从 view 抽出来的原因：view 里 80+ 行都在拼装 map + overlay，
 * 拆出来 view 才能专注做 grid 编排。
 */
import { AnimatePresence, motion } from 'framer-motion';
import { Loader2 } from 'lucide-react';
import { useRef } from 'react';

import { useRouteMapStore } from '@/stores/routeMapStore';

import { useMap } from '../hooks/useMap';
import { fishingMapService } from '../service';
import { formatDistance, formatDuration } from '../utils';

interface FishingMapTileProps {
  /**
   * 父组件若需要 ref 控制 map（如 forwardRef），可传 ref。
   * 不传则内部自管 —— 这是默认场景。
   */
  containerRef?: React.RefObject<HTMLDivElement | null>;
}

export function FishingMapTile({ containerRef: externalRef }: FishingMapTileProps) {
  const internalRef = useRef<HTMLDivElement | null>(null);
  const containerRef = externalRef ?? internalRef;

  const serviceRef = useRef(fishingMapService());
  const planRouteAction = useRouteMapStore((s) => s.planRouteAction);

  const getSecurityJsCode = (): Promise<string> =>
    serviceRef.current.getSecurityJsCode();

  /**
   * marker click 回调：useMap 内部已经调过 planRoute，
   * 这里再把 planRoute 包进 store 的串行化入口（错误通知 + routeSeq 守卫）。
   *
   * 注意：useMap.handleMarkerClick 已经把 userPosition 通过 onMarkerClick 上抛，
   * 我们只需要消费 index + userPosition 即可。
   */
  const handleMarkerClick = async (
    index: number,
    userPosition: [number, number],
  ): Promise<void> => {
    void userPosition; // userPosition 由 useMap 内部使用；这里只关心 marker index
    // 触发 planRouteAction 进入串行化轨道，spot.position 由 useMap 内部抓取
    await planRouteAction({
      spotIndex: index,
      runner: async () => {
        // useMap.handleMarkerClick 已经在 useEffect 初始化时把 marker click
        // 绑到 setIsPlanningRoute + planRoute 流程。这里返回一个 stub 让 store
        // 知道流程已启动；实际写入由 useMap 通过 setRouteInfo 完成。
        return { distance: 0, time: 0 };
      },
      fallbackError: '路线规划失败，请检查网络连接或定位权限',
    });
  };

  const { isMapReady, clearRoute } = useMap(
    containerRef,
    getSecurityJsCode,
    handleMarkerClick,
  );

  return (
    <div className="border-border/70 bg-card relative overflow-hidden rounded-2xl border shadow-md">
      <div
        ref={containerRef}
        className="h-[46dvh] w-full rounded-2xl"
        aria-label="fishing map"
      />
      {!isMapReady && (
        <div className="text-muted-foreground absolute inset-0 flex items-center justify-center text-xs">
          地图加载中…
        </div>
      )}
      <AnimatePresence>
        <MapOverlay onClearRoute={clearRoute} />
      </AnimatePresence>
    </div>
  );
}

function MapOverlay({ onClearRoute }: { onClearRoute: () => void }) {
  // 从 store 拿最新值（不再解构 prop，避免 useMap 的 useEffect 不重新订阅）
  const isPlanning = useRouteMapStore((s) => s.isPlanningRoute);
  const routeInfo = useRouteMapStore((s) => s.routeInfo);

  if (!isPlanning && !routeInfo) {
    return (
      <motion.div
        key="hint"
        initial={{ opacity: 0, y: 4 }}
        animate={{ opacity: 1, y: 0 }}
        exit={{ opacity: 0, y: 4 }}
        transition={{ duration: 0.24, ease: [0.22, 1, 0.36, 1] }}
        className="text-muted-foreground/90 bg-card/80 pointer-events-none absolute right-4 bottom-4 left-4 rounded-full px-4 py-1.5 text-center text-xs backdrop-blur-md"
      >
        点击地图标记，自动规划路线
      </motion.div>
    );
  }

  if (isPlanning) {
    return (
      <motion.div
        key="planning"
        initial={{ opacity: 0, y: 8 }}
        animate={{ opacity: 1, y: 0 }}
        exit={{ opacity: 0, y: 8 }}
        transition={{ duration: 0.24, ease: [0.22, 1, 0.36, 1] }}
        className="bg-card/90 border-border pointer-events-auto absolute right-4 bottom-4 left-4 rounded-2xl border p-4 shadow-lg backdrop-blur-md"
      >
        <div className="text-muted-foreground flex items-center gap-3">
          <Loader2 className="h-4 w-4 animate-spin" />
          <span className="text-sm">正在规划路线…</span>
        </div>
      </motion.div>
    );
  }

  if (!routeInfo) return null;

  return (
    <motion.div
      key="route"
      initial={{ opacity: 0, y: 8 }}
      animate={{ opacity: 1, y: 0 }}
      exit={{ opacity: 0, y: 8 }}
      transition={{ duration: 0.24, ease: [0.22, 1, 0.36, 1] }}
      className="bg-card/90 border-border pointer-events-auto absolute right-4 bottom-4 left-4 rounded-2xl border p-4 shadow-lg backdrop-blur-md"
    >
      <div className="flex items-center justify-between gap-3">
        <div className="min-w-0 space-y-1">
          <p className="text-muted-foreground text-[10px] tracking-[0.2em] uppercase">
            路线信息
          </p>
          <p className="text-foreground font-family-averia text-2xl leading-none tabular-nums">
            <span>{formatDistance(routeInfo.distance)}</span>
            <span className="text-muted-foreground mx-2 text-base">·</span>
            <span>{formatDuration(routeInfo.time)}</span>
          </p>
        </div>
        <button
          type="button"
          onClick={onClearRoute}
          className="bg-destructive text-primary-foreground hover:bg-destructive/90 rounded-lg px-3 py-2 text-xs font-medium transition-colors"
        >
          清除路线
        </button>
      </div>
    </motion.div>
  );
}

// frontend/src/views/fishing/components/FishingMapTile.vue
<script setup lang="ts">
/**
 * Map tile —— dashboard 中的地图卡片。
 *
 * 包含:
 * - 内部 MapContainer
 * - 底部浮层 (路线规划中 / 路线信息 / 空态提示)
 * - 通过 defineExpose 向上转发 MapContainer 的实例方法
 *   (planRoute / clearRoute / getCurrentPosition) —— 跟 useFishingRoute 的
 *   FishingMapInstance 接口对齐
 *
 * 选择把这一层从 view 抽出来的原因: view 里 80+ 行都在拼装 map + overlay,
 * 拆出来 view 才能专注做 grid 编排。
 */
import MapContainer from '@/components/basic/MapContainer.vue';
import {
  formatDistance,
  formatDuration,
  type FishingMapInstance,
  type RouteInfo,
} from '@/composables/useFishingRoute';
import { DEFAULT_MAP_CENTER } from '@/stores/fishingMap';
import type { AMapMarker } from '@/types/maptype';
import { Loader2 } from '@lucide/vue';
import { useTemplateRef } from 'vue';

interface Props {
  markers: AMapMarker[];
  isPlanning: boolean;
  routeInfo: RouteInfo | null;
  center?: [number, number];
  zoom?: number;
}

withDefaults(defineProps<Props>(), {
  center: () => DEFAULT_MAP_CENTER,
  zoom: 13,
});

const emit = defineEmits<{
  (e: 'marker-click', index: number): void;
  (e: 'map-ready'): void;
  (e: 'clear-route'): void;
}>();

const innerRef = useTemplateRef<FishingMapInstance>('innerRef');

/** 向父转发 MapContainer 实例方法,保持 useFishingRoute 那一套 ref 调用方式 */
defineExpose<FishingMapInstance>({
  planRoute: (start, end) => {
    if (!innerRef.value) {
      return Promise.reject(new Error('地图未就绪'));
    }
    return innerRef.value.planRoute(start, end);
  },
  clearRoute: () => innerRef.value?.clearRoute(),
  getCurrentPosition: () => {
    if (!innerRef.value) {
      return Promise.reject(new Error('地图未就绪'));
    }
    return innerRef.value.getCurrentPosition();
  },
});
</script>

<template>
  <div class="relative h-full w-full">
    <MapContainer
      ref="innerRef"
      :center="center"
      :zoom="zoom"
      :markers="markers"
      :show-tool-bar="true"
      :show-scale="true"
      :show-geolocation="true"
      @marker-click="(i: number) => emit('marker-click', i)"
      @map-ready="emit('map-ready')"
    />

    <Transition
      enter-active-class="transition-all duration-300 ease-out"
      enter-from-class="opacity-0 translate-y-2"
      enter-to-class="opacity-100 translate-y-0"
      leave-active-class="transition-all duration-200 ease-in"
      leave-from-class="opacity-100 translate-y-0"
      leave-to-class="opacity-0 translate-y-2"
    >
      <div
        v-if="isPlanning || routeInfo"
        class="bg-card/90 border-border absolute right-4 bottom-4 left-4 rounded-2xl border p-4 shadow-lg backdrop-blur-md"
      >
        <div
          v-if="isPlanning"
          class="text-muted-foreground flex items-center gap-3"
        >
          <Loader2 class="h-4 w-4 animate-spin" />
          <span class="text-sm">正在规划路线...</span>
        </div>
        <div
          v-else-if="routeInfo"
          class="flex items-center justify-between gap-4"
        >
          <div class="space-y-1.5">
            <p class="text-muted-foreground text-xs tracking-[0.2em] uppercase">
              路线信息
            </p>
            <p
              class="text-foreground font-family-averia text-2xl leading-none tabular-nums sm:text-3xl"
            >
              <span>{{ formatDistance(routeInfo.distance) }}</span>
              <span class="text-muted-foreground mx-2 text-base">·</span>
              <span>{{ formatDuration(routeInfo.time) }}</span>
            </p>
          </div>
          <button
            class="bg-destructive text-primary-foreground hover:bg-destructive/90 rounded-lg px-4 py-2 text-sm font-medium transition-colors"
            type="button"
            @click="emit('clear-route')"
          >
            清除路线
          </button>
        </div>
      </div>
    </Transition>

    <p
      v-if="!isPlanning && !routeInfo"
      class="text-muted-foreground/90 bg-card/70 absolute bottom-4 left-1/2 -translate-x-1/2 rounded-full px-4 py-1.5 text-xs backdrop-blur-md"
    >
      点击地图标记，自动规划路线
    </p>
  </div>
</template>
