// frontend/src/views/fishing/components/FishingDashboardHeader.vue
<script setup lang="ts">
/**
 * Dashboard 顶部 sticky header。
 *
 * 替换原 view 里散落的 header + 右下角 FAB:
 * - 标题 + kanocifer slug
 * - 右侧 AI 分析按钮 (替代右下 FAB,统一浮层入口)
 */
import { Bot } from '@lucide/vue';

defineProps<{
  analysisOpen: boolean;
  analysisHasData: boolean;
}>();

defineEmits<{
  (e: 'toggle-analysis'): void;
}>();
</script>

<template>
  <header
    class="border-border/40 bg-card/80 sticky top-0 z-30 border-b backdrop-blur-sm"
  >
    <div
      class="mx-auto flex max-w-screen-2xl items-center justify-between px-4 py-3 sm:px-6"
    >
      <div class="flex items-baseline gap-3">
        <h1 class="text-foreground font-family-averia text-lg">钓鱼地图</h1>
        <span
          class="text-muted-foreground hidden text-xs tracking-[0.2em] uppercase sm:inline"
        >
          kanocifer
        </span>
      </div>

      <button
        class="border-border bg-card hover:bg-accent text-foreground inline-flex items-center gap-2 rounded-full border px-3 py-1.5 text-sm transition-colors"
        :class="analysisOpen ? 'border-primary text-primary bg-primary/5' : ''"
        type="button"
        :aria-pressed="analysisOpen"
        @click="$emit('toggle-analysis')"
      >
        <span class="relative inline-flex">
          <Bot class="h-4 w-4" aria-hidden="true" />
          <span
            v-if="analysisHasData && !analysisOpen"
            class="bg-success ring-card absolute -top-1 -right-1 inline-flex h-2 w-2 rounded-full ring-2"
            aria-hidden="true"
          />
        </span>
        <span class="hidden sm:inline">AI 分析</span>
      </button>
    </div>
  </header>
</template>

// react-app/src/views/FishingMap/components/FishingDashboardHeader.tsx
/**
 * Dashboard 顶部 sticky header。
 *
 * 替换原 FishingMapHeader + AIAnalysisWidget 里的 FAB：
 * - 标题 + kanocifer slug
 * - 右侧 AI 分析按钮（替代 FAB，统一浮层入口）
 * - 移动端只显 Bot 图标 + 红点；sm 及以上追加 "AI 分析" 文字
 */
import { Bot } from 'lucide-react';

interface FishingDashboardHeaderProps {
  analysisOpen: boolean;
  analysisHasData: boolean;
  onToggleAnalysis: () => void;
}

export function FishingDashboardHeader({
  analysisOpen,
  analysisHasData,
  onToggleAnalysis,
}: FishingDashboardHeaderProps) {
  return (
    <header className="border-border/40 bg-card/80 sticky top-0 z-30 border-b backdrop-blur-sm">
      <div className="flex items-center justify-between px-4 py-3 sm:px-5">
        <div className="flex items-baseline gap-3">
          <h1 className="text-foreground font-family-dongfang text-lg font-semibold sm:text-xl">
            钓鱼地图
          </h1>
          <span className="text-muted-foreground hidden text-[10px] tracking-[0.25em] uppercase sm:inline">
            kanocifer
          </span>
        </div>

        <button
          type="button"
          aria-pressed={analysisOpen}
          aria-label={analysisOpen ? '关闭 AI 分析' : '打开 AI 分析'}
          onClick={onToggleAnalysis}
          className={`border-border bg-card hover:bg-accent text-foreground inline-flex items-center gap-2 rounded-full border px-3 py-1.5 text-sm transition-colors ${
            analysisOpen ? 'border-primary text-primary bg-primary/5' : ''
          }`}
        >
          <span className="relative inline-flex">
            <Bot className="h-4 w-4" aria-hidden="true" />
            {analysisHasData && !analysisOpen && (
              <span className="bg-success ring-card absolute -top-1 -right-1 inline-flex h-2 w-2 rounded-full ring-2" />
            )}
          </span>
          <span className="hidden sm:inline">AI 分析</span>
        </button>
      </div>
    </header>
  );
}
