// frontend/src/views/fishing/components/FishingFeedbackForm.vue
<script setup lang="ts">
import { fishingService } from '@/service/fishingService';
import { useNotificationStore } from '@/stores/notification';
import type {
  FishingFeedbackData,
  FishingFeedbackLevel,
  FishingFeedbackPayload,
} from '@/views/fishing/types';
import dayjs from 'dayjs';
import { ref } from 'vue';

interface Props {
  isOpen: boolean;
  fishingData: FishingFeedbackData;
  locationId: string;
  locationName: string;
}

const props = defineProps<Props>();

const emit = defineEmits<{
  (e: 'success'): void;
  (e: 'cancel'): void;
}>();

const FEEDBACK_OPTIONS: { value: FishingFeedbackLevel; label: string }[] = [
  { value: '爆护', label: '爆护' },
  { value: '好', label: '好' },
  { value: '一般', label: '一般' },
  { value: '差', label: '差' },
  { value: '空军', label: '空军' },
];

const notifier = useNotificationStore();
const loading = ref(false);
const selectedFeedback = ref<FishingFeedbackLevel | null>(null);

const handleSubmit = async () => {
  if (!selectedFeedback.value) {
    notifier.error('请选择钓鱼体验');
    return;
  }

  loading.value = true;

  try {
    const payload: FishingFeedbackPayload = {
      location_id: props.locationId,
      location_name: props.locationName,
      fishing_time: dayjs().toISOString(),
      feedback: selectedFeedback.value,
      temperature: props.fishingData.temperature,
      humidity: props.fishingData.humidity,
      pressure: props.fishingData.pressure,
      wind_speed: props.fishingData.wind_speed,
      precipitation: props.fishingData.precipitation,
      indices: props.fishingData.indices,
      tide_level: props.fishingData.tide_level,
      tide_type: props.fishingData.tide_type,
      tide_range: props.fishingData.tide_range,
      hours_to_next_tide: props.fishingData.hours_to_next_tide,
    };
    await fishingService.submitFishingFeedback(payload);

    notifier.success('反馈已提交，感谢您的分享！');
    selectedFeedback.value = null;
    emit('success');
  } catch (err) {
    const message = err instanceof Error ? err.message : '提交反馈失败，请重试';
    notifier.error(message);
  } finally {
    loading.value = false;
  }
};
</script>

<template>
  <teleport to="body">
    <transition name="modal-fade">
      <div
        v-if="isOpen"
        class="fixed inset-0 z-50 flex items-center justify-center bg-black/50 p-4"
      >
        <div class="bg-card mx-4 w-full max-w-md rounded-2xl p-6 shadow-xl">
          <h3 class="text-foreground mb-4 text-lg font-semibold">
            钓鱼反馈
            <span class="text-muted-foreground ml-2 text-sm font-normal"
              >你的反馈会帮助我们改进</span
            >
          </h3>

          <div class="bg-muted mb-4 rounded-lg p-3 text-sm">
            <p class="text-muted-foreground">地点: {{ locationName }}</p>
            <p class="text-muted-foreground">
              当前指数: {{ fishingData.fishing_index }} ({{
                fishingData.level
              }})
            </p>
          </div>

          <div class="space-y-4">
            <div>
              <label class="text-foreground mb-2 block text-sm font-medium"
                >您的钓鱼体验</label
              >
              <div class="grid grid-cols-3 gap-2">
                <button
                  v-for="option in FEEDBACK_OPTIONS"
                  :key="option.value"
                  type="button"
                  class="rounded-lg px-3 py-2 text-sm font-medium transition-colors"
                  :class="
                    selectedFeedback === option.value
                      ? 'bg-primary text-primary-foreground'
                      : 'bg-muted text-foreground hover:bg-accent'
                  "
                  @click="selectedFeedback = option.value"
                >
                  {{ option.label }}
                </button>
              </div>
            </div>

            <div class="flex gap-3 pt-2">
              <button
                type="button"
                class="border-border text-foreground hover:bg-accent flex-1 rounded-lg border px-4 py-2 text-sm font-medium"
                :disabled="loading"
                @click="$emit('cancel')"
              >
                取消
              </button>
              <button
                type="button"
                class="bg-primary text-primary-foreground hover:bg-primary/90 flex-1 rounded-lg px-4 py-2 text-sm font-medium disabled:cursor-not-allowed disabled:opacity-50"
                :disabled="!selectedFeedback || loading"
                @click="handleSubmit"
              >
                {{ loading ? '提交中...' : '确认提交' }}
              </button>
            </div>
          </div>
        </div>
      </div>
    </transition>
  </teleport>
</template>

// react-app/src/views/FishingMap/components/FishingFeedbackForm.tsx
import { useCallback, useMemo, useState } from 'react';

import { useNotificationStore } from '@/stores/notificationState';

import { fishingMapService } from '../service';
import type { FishingFeedbackData, FishingLevel } from '../types';

interface FishingFeedbackFormProps {
  fishingData: FishingFeedbackData;
  locationId: string;
  locationName: string;
  onSuccess?: () => void;
  onCancel?: () => void;
}

const FEEDBACK_OPTIONS: { value: FishingLevel; label: string }[] = [
  { value: '爆护', label: '爆护' },
  { value: '极好', label: '极好' },
  { value: '好', label: '好' },
  { value: '一般', label: '一般' },
  { value: '差', label: '差' },
  { value: '空军', label: '空军' },
];

export function FishingFeedbackForm({
  fishingData,
  locationId,
  locationName,
  onSuccess,
  onCancel,
}: FishingFeedbackFormProps) {
  const notifyError = useNotificationStore((state) => state.error);
  const notifySuccess = useNotificationStore((state) => state.success);
  const service = useMemo(() => fishingMapService(), []);

  const [loading, setLoading] = useState(false);
  const [selectedFeedback, setSelectedFeedback] = useState<FishingLevel | null>(
    null,
  );

  const handleSubmit = useCallback(
    async (e: React.FormEvent) => {
      e.preventDefault();

      if (!selectedFeedback) {
        notifyError('请选择钓鱼体验');
        return;
      }

      setLoading(true);

      try {
        await service.submitFishingFeedback({
          location_id: locationId,
          location_name: locationName,
          fishing_time: new Date().toISOString(),
          feedback: selectedFeedback,
          temperature: fishingData.temperature,
          humidity: fishingData.humidity,
          pressure: fishingData.pressure,
          wind_speed: fishingData.wind_speed,
          precipitation: fishingData.precipitation,
          wind_level: fishingData.wind_level,
          tide_level: fishingData.tide_level,
          tide_type: fishingData.tide_type,
          tide_range: fishingData.tide_range,
          hours_to_next_tide: fishingData.hours_to_next_tide,
        });

        notifySuccess('反馈已提交，感谢您的分享！');
        onSuccess?.();
      } catch (err) {
        const message =
          err instanceof Error ? err.message : '提交反馈失败，请重试';
        notifyError(message);
      } finally {
        setLoading(false);
      }
    },
    [
      selectedFeedback,
      locationId,
      locationName,
      fishingData,
      notifyError,
      notifySuccess,
      onSuccess,
      service,
    ],
  );

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/50">
      <div className="mx-4 w-full max-w-md rounded-2xl bg-white p-6 shadow-xl dark:bg-gray-900">
        <h3 className="mb-4 text-lg font-semibold text-gray-900 dark:text-white">
          钓鱼反馈
          <span className="ml-2 text-sm font-normal text-gray-500 dark:text-gray-400">
            你的反馈会帮助我们改进
          </span>
        </h3>

        <div className="mb-4 rounded-lg bg-gray-50 p-3 text-sm dark:bg-gray-800">
          <p className="text-gray-600 dark:text-gray-400">
            地点: {locationName}
          </p>
          <p className="text-gray-600 dark:text-gray-400">
            当前指数: {fishingData.fishing_index} ({fishingData.level})
          </p>
        </div>

        <form onSubmit={(e) => void handleSubmit(e)} className="space-y-4">
          <div>
            <label className="mb-2 block text-sm font-medium text-gray-700 dark:text-gray-300">
              您的钓鱼体验
            </label>
            <div className="grid grid-cols-3 gap-2">
              {FEEDBACK_OPTIONS.map((option) => (
                <button
                  key={option.value}
                  type="button"
                  onClick={() => setSelectedFeedback(option.value)}
                  className={`rounded-lg px-3 py-2 text-sm font-medium transition-colors ${
                    selectedFeedback === option.value
                      ? 'bg-blue-500 text-white'
                      : 'bg-gray-100 text-gray-700 hover:bg-gray-200 dark:bg-gray-700 dark:text-gray-300 dark:hover:bg-gray-600'
                  }`}
                >
                  {option.label}
                </button>
              ))}
            </div>
          </div>

          <div className="flex gap-3 pt-2">
            <button
              type="button"
              onClick={onCancel}
              className="flex-1 rounded-lg border border-gray-300 px-4 py-2 text-sm font-medium text-gray-700 hover:bg-gray-50 dark:border-gray-600 dark:text-gray-300 dark:hover:bg-gray-800"
              disabled={loading}
            >
              取消
            </button>
            <button
              type="submit"
              disabled={!selectedFeedback || loading}
              className="flex-1 rounded-lg bg-blue-500 px-4 py-2 text-sm font-medium text-white hover:bg-blue-600 disabled:cursor-not-allowed disabled:opacity-50"
            >
              {loading ? '提交中...' : '确认提交'}
            </button>
          </div>
        </form>
      </div>
    </div>
  );
}
