// react-app/src/features/home/components/BentoGreeting.tsx
import { BentoCard } from '@/components/bento/BentoCard';
import dayjs from 'dayjs';
import { useNavigate } from 'react-router-dom';

export function BentoGreeting() {
  const greeting =
    dayjs().hour() < 12
      ? 'Good Morning'
      : dayjs().hour() < 18
        ? 'Good Afternoon'
        : 'Good Evening';
  const navigate = useNavigate();

  const isEvening = dayjs().hour() >= 18 || dayjs().hour() < 6;
  return (
    <BentoCard className="border-primary/30! from-primary/90 to-primary/90 relative overflow-hidden bg-linear-to-br p-8 shadow-xl">
      <div className="relative z-10 flex flex-col justify-center">
        <h3 className="text-primary-foreground/80 mb-1 font-serif text-sm font-medium">
          {greeting}
        </h3>
        <h4 className="text-primary-foreground font-serif text-3xl leading-tight font-extrabold">
          Ready for a productive
        </h4>
        <h4 className="text-primary-foreground mb-4 font-serif text-3xl leading-tight font-extrabold">
          session now?
        </h4>
        <div className="mt-2">
          <button
            onClick={() => navigate('/todos')}
            className="bg-primary-foreground/20 text-primary-foreground hover:bg-primary-foreground/30 rounded-full px-6 py-2.5 text-sm font-semibold backdrop-blur-md transition-all active:scale-95"
          >
            Check Today's Tasks
          </button>
        </div>

        {/* <!-- Decorative Abstract Shape --> */}
        <div className="bg-primary-foreground/10 absolute -right-10 -bottom-10 h-48 w-48 rounded-full blur-3xl"></div>
        <div className="absolute top-1/2 right-4 -translate-y-1/2 opacity-20">
          {isEvening ? (
            <svg
              className="text-primary-foreground h-24 w-24"
              fill="currentColor"
              viewBox="0 0 24 24"
            >
              <path
                fillRule="evenodd"
                d="M9.528 1.718a.75.75 0 01.162.819A8.97 8.97 0 009 6a9 9 0 009 9 8.97 8.97 0 003.463-.69.75.75 0 01.981.98 10.503 10.503 0 01-9.694 6.46c-5.799 0-10.5-4.701-10.5-10.5 0-4.368 2.667-8.112 6.46-9.694a.75.75 0 01.818.162z"
                clipRule="evenodd"
              />
            </svg>
          ) : (
            <svg
              className="text-primary-foreground h-24 w-24"
              fill="currentColor"
              viewBox="0 0 24 24"
            >
              <path d="M12 2.25a.75.75 0 01.75.75v2.25a.75.75 0 01-1.5 0V3a.75.75 0 01.75-.75zM7.5 12a4.5 4.5 0 119 0 4.5 4.5 0 01-9 0zM18.894 6.166a.75.75 0 00-1.06-1.06l-1.591 1.59a.75.75 0 101.06 1.061l1.591-1.59zM21.75 12a.75.75 0 01-.75.75h-2.25a.75.75 0 010-1.5H21a.75.75 0 01.75.75zM17.834 18.894a.75.75 0 001.06-1.06l-1.59-1.591a.75.75 0 10-1.061 1.06l1.59 1.591zM12 18a.75.75 0 01.75.75V21a.75.75 0 01-1.5 0v-2.25A.75.75 0 0112 18zM7.758 17.303a.75.75 0 00-1.061-1.06l-1.591 1.59a.75.75 0 001.06 1.061l1.591-1.59zM6 12a.75.75 0 01-.75.75H3a.75.75 0 010-1.5h2.25A.75.75 0 016 12zM6.697 7.757a.75.75 0 001.06-1.06l-1.59-1.591a.75.75 0 00-1.061 1.06l1.59 1.591z" />
            </svg>
          )}
        </div>
      </div>
    </BentoCard>
  );
}

// frontend/src/views/entry/components/BentoGreeting.vue
<template>
  <BentoCard>
    <div class="flex h-full items-center gap-5">
      <div class="flex shrink-0 items-center justify-center">
        <svg
          v-if="isDay"
          class="text-warning size-12"
          viewBox="0 0 24 24"
          fill="currentColor"
        >
          <circle cx="12" cy="12" r="5" />
          <g stroke="currentColor" stroke-width="2" stroke-linecap="round">
            <line x1="12" y1="1" x2="12" y2="3" />
            <line x1="12" y1="21" x2="12" y2="23" />
            <line x1="4.22" y1="4.22" x2="5.64" y2="5.64" />
            <line x1="18.36" y1="18.36" x2="19.78" y2="19.78" />
            <line x1="1" y1="12" x2="3" y2="12" />
            <line x1="21" y1="12" x2="23" y2="12" />
            <line x1="4.22" y1="19.78" x2="5.64" y2="18.36" />
            <line x1="18.36" y1="5.64" x2="19.78" y2="4.22" />
          </g>
        </svg>
        <svg
          v-else
          class="text-muted size-12"
          viewBox="0 0 24 24"
          fill="currentColor"
        >
          <path d="M21 12.79A9 9 0 1 1 11.21 3 7 7 0 0 0 21 12.79z" />
        </svg>
      </div>
      <div class="flex flex-col justify-center">
        <h2
          class="text-foreground font-serif text-2xl font-bold tracking-tight"
        >
          {{ greeting }}
        </h2>
        <p class="text-muted-foreground mt-1 font-serif text-sm font-medium">
          {{ changelogHint }}
        </p>
      </div>
      <!-- 更新日志按钮 -->
      <button
        @click.stop="$router.push('/changelog')"
        class="squircle bg-primary/10 text-primary ring-primary/20 hover:bg-primary/20 ml-4 shrink-0 px-3 py-2 text-xs font-bold ring transition-all hover:scale-105"
      >
        Changelog
      </button>
    </div>
  </BentoCard>
</template>

<script setup lang="ts">
import BentoCard from "@/components/bento/BentoCard.vue";
import { computed } from "vue";

const isDay = computed(() => {
  const hour = new Date().getHours();
  return hour >= 6 && hour < 18;
});

const greeting = computed(() => {
  const hour = new Date().getHours();
  if (hour < 12) return "Good Morning";
  if (hour < 18) return "Good Afternoon";
  return "Good Evening";
});

const changelogHint = computed(() => {
  const hour = new Date().getHours();
  if (hour < 12) return "Check out what's new today!";
  if (hour < 18) return "See what's changed this afternoon";
  return "New updates waiting for you tonight";
});
</script>
