// frontend/src/views/auth/ProfileSettingView.vue
<script setup lang="ts">
import { authGateway } from '@/auth/api/authGateway';
import { useAuthStore } from '@/auth/stores/auth';
import AuthLayout from '@/components/auth/AuthLayout.vue';
import IconCloud from '@/components/icons/IconCloud.vue';
import type { ProfileForm } from '@/types';
import {
  AlertCircle,
  AtSign,
  Camera,
  Check,
  KeyRound,
  Loader2,
  Lock,
  Mail,
  Phone,
  Save,
  ShieldUser,
  Trash2,
  User,
} from '@lucide/vue';
import { startRegistration } from '@simplewebauthn/browser';
import { computed, onMounted, ref } from 'vue';

import {
  AlertDialog,
  AlertDialogAction,
  AlertDialogCancel,
  AlertDialogContent,
  AlertDialogDescription,
  AlertDialogFooter,
  AlertDialogHeader,
  AlertDialogTitle,
  AlertDialogTrigger,
} from '@/components/ui/alert-dialog';

const authStore = useAuthStore();

const form = ref<ProfileForm>({
  name: '',
  username: '',
  gender: '',
  email: '',
  mobile: '',
  password: '',
});

const errors = ref<Record<string, string>>({});
const saving = ref(false);
const message = ref('');
const messageType = ref<'success' | 'error'>('success');

const avatarUrl = computed(() => {
  if (authStore.user?.photo?.startsWith('http')) {
    return authStore.user.photo;
  }
  if (authStore.user?.photo) {
    return `/api/v1/media/${authStore.user.photo}`;
  }
  return '/api/v1/media/default.png';
});

const loadUserData = () => {
  if (authStore.user) {
    form.value.name = authStore.user.name || '';
    form.value.username = authStore.user.username || '';
    form.value.gender = authStore.user.gender || '';
    form.value.email = authStore.user.email || '';
    const userWithMobile = authStore.user as { mobile?: string } | null;
    form.value.mobile = userWithMobile?.mobile || '';
    const userWithPasskey = authStore.user as { has_passkey?: boolean } | null;
    hasPasskey.value = !!userWithPasskey?.has_passkey;
    const userWithGitHub = authStore.user as { github_bound?: boolean } | null;
    hasGitHubBound.value = !!userWithGitHub?.github_bound;
  }
};

const toggleGender = (value: string) => {
  if (form.value.gender === value) {
    form.value.gender = '';
  } else {
    form.value.gender = value;
  }
};

const handlePhotoUpload = async (event: Event) => {
  const input = event.target as HTMLInputElement;
  const file = input.files?.[0];

  if (!file) return;

  const formData = new FormData();
  formData.append('image', file);

  try {
    await authGateway.uploadAvatar(formData);
    await authStore.fetchUser();
    message.value = 'Avatar updated successfully!';
    messageType.value = 'success';
  } catch (error) {
    console.error('Avatar upload error:', error);
    message.value = 'Network error, please try again';
    messageType.value = 'error';
  }

  input.value = '';
};

const addingPasskey = ref(false);
const deletingPasskey = ref(false);
const passkeyMessage = ref('');
const passkeyMessageType = ref<'success' | 'error'>('success');
const hasPasskey = ref(false);

const bindingGitHub = ref(false);
const unbindingGitHub = ref(false);
const githubMessage = ref('');
const githubMessageType = ref<'success' | 'error'>('success');
const hasGitHubBound = ref<boolean>(false);

const handleAddPasskey = async () => {
  addingPasskey.value = true;
  passkeyMessage.value = '';

  try {
    const optionsRes = await authGateway.getPasskeyRegistrationOptions();
    const options = optionsRes.data.data;
    if (!options) throw new Error('Failed to get passkey registration options');

    const credential = await startRegistration({ optionsJSON: options });

    await authGateway.registerPasskey({
      response: credential,
    });

    passkeyMessage.value = 'Passkey added successfully!';
    passkeyMessageType.value = 'success';
    hasPasskey.value = true;
  } catch (error) {
    console.error('Add passkey error:', error);
    passkeyMessage.value = 'Failed to add passkey';
    passkeyMessageType.value = 'error';
  } finally {
    addingPasskey.value = false;
  }
};

const handleDeletePasskey = async () => {
  deletingPasskey.value = true;
  passkeyMessage.value = '';

  try {
    await authGateway.deletePasskey();
    passkeyMessage.value = 'Passkey deleted successfully!';
    passkeyMessageType.value = 'success';
    hasPasskey.value = false;
  } catch (error) {
    console.error('Delete passkey error:', error);
    passkeyMessage.value = 'Failed to delete passkey';
    passkeyMessageType.value = 'error';
  } finally {
    deletingPasskey.value = false;
  }
};

const handleBindGitHub = () => {
  bindingGitHub.value = true;
  githubMessage.value = '';
  window.location.href = '/api/v1/auth/github/bind';
};

const handleUnbindGitHub = async () => {
  unbindingGitHub.value = true;
  githubMessage.value = '';

  try {
    await authGateway.unbindGithub();
    githubMessage.value = 'GitHub account unbound successfully!';
    githubMessageType.value = 'success';
    hasGitHubBound.value = false;
    await authStore.fetchUser();
  } catch (error) {
    console.error('Unbind GitHub error:', error);
    githubMessage.value = 'Failed to unbind GitHub account';
    githubMessageType.value = 'error';
  } finally {
    unbindingGitHub.value = false;
  }
};

const handleSubmit = async () => {
  saving.value = true;
  errors.value = {};
  message.value = '';

  try {
    const payload = {
      name: form.value.name || '',
      username: form.value.username || '',
      gender: form.value.gender || null,
      email: form.value.email || null,
      mobile: form.value.mobile || null,
      password: form.value.password || null,
    };

    await authGateway.updateProfileSettings(payload);
    await authStore.fetchUser();
    form.value.password = '';
    message.value = 'Profile updated successfully!';
    messageType.value = 'success';
  } catch (error) {
    console.error('Settings update error:', error);
    message.value = 'Network error, please try again';
    messageType.value = 'error';
  } finally {
    saving.value = false;
  }
};

onMounted(() => {
  loadUserData();

  const urlParams = new URLSearchParams(window.location.search);
  const error = urlParams.get('error');
  const success = urlParams.get('success');

  if (error) {
    const errorMessages: Record<string, string> = {
      not_logged_in: 'Please log in first to bind GitHub account',
      github_already_bound:
        'This GitHub account is already bound to another user',
      github_not_bound: 'Your account is not bound to GitHub',
      invalid_oauth_state: 'Invalid OAuth state, please try again',
      missing_pkce_info: 'Missing PKCE information, please try again',
      github_auth_failed: 'GitHub authentication failed, please try again',
    };
    githubMessage.value = errorMessages[error] || 'GitHub binding failed';
    githubMessageType.value = 'error';
    window.history.replaceState({}, document.title, window.location.pathname);
  }

  if (success) {
    const successMessages: Record<string, string> = {
      github_bound: 'GitHub account bound successfully!',
      github_unbound: 'GitHub account unbound successfully!',
    };
    githubMessage.value = successMessages[success] || 'Operation successful';
    githubMessageType.value = 'success';
    authStore.fetchUser();
    window.history.replaceState({}, document.title, window.location.pathname);
  }
});
</script>

<template>
  <AuthLayout
    brand-width="w-1/2"
    form-width="lg:w-1/2"
    form-max-width="max-w-md xl:max-w-xl"
  >
    <template #branding>
      <div class="flex items-center gap-2 text-xl font-bold tracking-tight">
        <IconCloud class="text-primary size-8" />
        <span>Kanocifer<span class="text-primary">.chat</span></span>
      </div>
      <div class="z-10 my-auto">
        <div class="flex flex-col">
          <h1 class="text-5xl font-extrabold tracking-tight xl:text-6xl">
            Shape your <br />
            reading identity.
          </h1>
          <p class="mt-6 max-w-md text-lg text-zinc-400">
            Update your profile, manage your passkeys, and connect the accounts
            that power your reading life.
          </p>
        </div>
      </div>
      <div class="z-10 font-serif text-sm text-zinc-500">Kuroome's Blog</div>
    </template>

    <template #header>
      <div class="mb-8 flex flex-col items-center lg:items-start">
        <div
          class="bg-primary text-primary-foreground mb-5 flex h-16 w-16 items-center justify-center rounded-full shadow-[0_8px_16px_rgba(37,99,235,0.25)] lg:hidden"
        >
          <IconCloud class="size-8" />
        </div>
        <h2
          class="font-headline text-foreground text-center text-3xl text-[28px] font-extrabold tracking-tight lg:text-left"
        >
          Profile Settings
        </h2>
        <p
          class="text-muted-foreground mt-2 text-center text-[15px] font-medium lg:text-left"
        >
          Manage your profile and security preferences.
        </p>
      </div>
    </template>

        <div class="mb-8 flex flex-col items-center gap-3">
          <div class="group relative">
            <div
              class="border-border h-24 w-24 overflow-hidden rounded-full border-4 shadow-lg"
            >
              <img
                :src="avatarUrl"
                alt="Avatar"
                class="h-full w-full object-cover"
              />
            </div>
            <input
              id="photo-upload"
              type="file"
              accept=".jpg,.jpeg,.png,.gif"
              class="sr-only"
              @change="handlePhotoUpload"
            />
            <label
              for="photo-upload"
              class="bg-primary text-primary-foreground hover:bg-primary/90 focus:ring-primary/30 absolute -right-1 -bottom-1 flex h-9 w-9 cursor-pointer items-center justify-center rounded-full shadow-lg transition-colors focus:ring-2 focus:ring-offset-2 focus:outline-none"
            >
              <Camera class="size-4" />
            </label>
          </div>
          <p class="text-muted-foreground text-xs">
            Click the camera to update
          </p>
        </div>

        <form @submit.prevent="handleSubmit" class="w-full">
          <div>
            <div class="relative my-3">
              <div
                class="text-muted-foreground/60 pointer-events-none absolute top-1/2 left-0 z-10 flex -translate-y-1/2 items-center pl-4"
              >
                <User class="size-6" />
              </div>
              <input
                v-model="form.name"
                type="text"
                autocomplete="off"
                placeholder="display name"
                class="border-border bg-muted text-foreground focus:ring-primary/30 w-full rounded-xl py-3 pr-4 pl-11 transition-colors placeholder:font-serif placeholder:italic focus:ring-2 focus:outline-none"
                :class="{
                  'border-destructive focus:border-destructive focus:ring-destructive/30':
                    errors.name,
                }"
              />
            </div>
            <span
              v-if="errors.name"
              class="text-destructive mt-1.5 flex items-center gap-1.5 text-sm"
            >
              <AlertCircle class="size-4 shrink-0" />
              {{ errors.name }}
            </span>
          </div>

          <div>
            <div class="relative my-3">
              <div
                class="text-muted-foreground/60 pointer-events-none absolute top-1/2 left-0 z-10 flex -translate-y-1/2 items-center pl-4"
              >
                <AtSign class="size-6" />
              </div>
              <input
                v-model="form.username"
                type="text"
                autocomplete="off"
                placeholder="username"
                class="border-border bg-muted text-foreground focus:ring-primary/30 w-full rounded-xl py-3 pr-4 pl-11 transition-colors placeholder:font-serif placeholder:italic focus:ring-2 focus:outline-none"
                :class="{
                  'border-destructive focus:border-destructive focus:ring-destructive/30':
                    errors.username,
                }"
              />
            </div>
            <span
              v-if="errors.username"
              class="text-destructive mt-1.5 flex items-center gap-1.5 text-sm"
            >
              <AlertCircle class="size-4 shrink-0" />
              {{ errors.username }}
            </span>
          </div>

          <div class="my-3">
            <div
              class="text-muted-foreground/60 flex items-center gap-2 text-sm"
            >
              <ShieldUser class="size-5" />
              <span>Gender</span>
            </div>
            <div class="mt-2 grid grid-cols-2 gap-3">
              <label class="group relative cursor-pointer">
                <input
                  v-model="form.gender"
                  type="radio"
                  value="male"
                  class="peer sr-only"
                  @click="toggleGender('male')"
                />
                <div
                  class="border-border bg-muted peer-checked:border-primary peer-checked:bg-primary/10 peer-checked:shadow-primary/10 hover:border-primary/30 flex items-center justify-center rounded-xl border-2 px-4 py-2.5 transition-all duration-200 select-none group-active:scale-95"
                >
                  <span
                    class="text-muted-foreground peer-checked:text-primary text-sm font-bold transition-colors"
                    >Male</span
                  >
                </div>
              </label>
              <label class="group relative cursor-pointer">
                <input
                  v-model="form.gender"
                  type="radio"
                  value="female"
                  class="peer sr-only"
                  @click="toggleGender('female')"
                />
                <div
                  class="border-border bg-muted peer-checked:border-primary peer-checked:bg-primary/10 peer-checked:shadow-primary/10 hover:border-primary/30 flex items-center justify-center rounded-xl border-2 px-4 py-2.5 transition-all duration-200 select-none group-active:scale-95"
                >
                  <span
                    class="text-muted-foreground peer-checked:text-primary text-sm font-bold transition-colors"
                    >Female</span
                  >
                </div>
              </label>
            </div>
          </div>

          <div>
            <div class="relative my-3">
              <div
                class="text-muted-foreground/60 pointer-events-none absolute top-1/2 left-0 z-10 flex -translate-y-1/2 items-center pl-4"
              >
                <Mail class="size-6" />
              </div>
              <input
                v-model="form.email"
                type="email"
                autocomplete="off"
                placeholder="email"
                class="border-border bg-muted text-foreground focus:ring-primary/30 w-full rounded-xl py-3 pr-4 pl-11 transition-colors placeholder:font-serif placeholder:italic focus:ring-2 focus:outline-none"
                :class="{
                  'border-destructive focus:border-destructive focus:ring-destructive/30':
                    errors.email,
                }"
              />
            </div>
            <span
              v-if="errors.email"
              class="text-destructive mt-1.5 flex items-center gap-1.5 text-sm"
            >
              <AlertCircle class="size-4 shrink-0" />
              {{ errors.email }}
            </span>
          </div>

          <div>
            <div class="relative my-3">
              <div
                class="text-muted-foreground/60 pointer-events-none absolute top-1/2 left-0 z-10 flex -translate-y-1/2 items-center pl-4"
              >
                <Phone class="size-6" />
              </div>
              <input
                v-model="form.mobile"
                type="tel"
                autocomplete="off"
                placeholder="mobile"
                class="border-border bg-muted text-foreground focus:ring-primary/30 w-full rounded-xl py-3 pr-4 pl-11 transition-colors placeholder:font-serif placeholder:italic focus:ring-2 focus:outline-none"
                :class="{
                  'border-destructive focus:border-destructive focus:ring-destructive/30':
                    errors.mobile,
                }"
              />
            </div>
            <span
              v-if="errors.mobile"
              class="text-destructive mt-1.5 flex items-center gap-1.5 text-sm"
            >
              <AlertCircle class="size-4 shrink-0" />
              {{ errors.mobile }}
            </span>
          </div>

          <div>
            <div class="relative my-3">
              <div
                class="text-muted-foreground/60 pointer-events-none absolute top-1/2 left-0 z-10 flex -translate-y-1/2 items-center pl-4"
              >
                <Lock class="size-6" />
              </div>
              <input
                v-model="form.password"
                type="password"
                autocomplete="off"
                placeholder="new password (leave empty to keep current)"
                class="border-border bg-muted text-foreground focus:ring-primary/30 w-full rounded-xl py-3 pr-4 pl-11 transition-colors placeholder:font-serif placeholder:italic focus:ring-2 focus:outline-none"
                :class="{
                  'border-destructive focus:border-destructive focus:ring-destructive/30':
                    errors.password,
                }"
              />
            </div>
            <span
              v-if="errors.password"
              class="text-destructive mt-1.5 flex items-center gap-1.5 text-sm"
            >
              <AlertCircle class="size-4 shrink-0" />
              {{ errors.password }}
            </span>
          </div>

          <div class="mt-6">
            <button
              type="submit"
              class="bg-primary text-primary-foreground shadow-primary/30 hover:bg-primary/90 focus:ring-primary/30 inline-flex w-full cursor-pointer items-center justify-center gap-2 rounded-xl px-8 py-2.5 font-bold shadow-lg transition-colors focus:ring-2 focus:ring-offset-2 focus:outline-none disabled:cursor-not-allowed disabled:opacity-50"
              :disabled="saving"
            >
              <Loader2 v-if="saving" class="h-5 w-5 animate-spin" />
              <Save v-else class="h-5 w-5" />
              {{ saving ? 'Saving Changes...' : 'Save Changes' }}
            </button>
          </div>

          <div
            v-if="message"
            :class="[
              messageType === 'success' ? 'text-success' : 'text-destructive',
              'mt-3 flex items-center justify-center gap-1.5 text-center text-sm',
            ]"
          >
            <Check v-if="messageType === 'success'" class="h-4 w-4" />
            <AlertCircle v-else class="h-4 w-4" />
            {{ message }}
          </div>
        </form>

        <div class="relative mt-8">
          <div class="absolute inset-0 flex items-center">
            <span class="border-border w-full border-t"></span>
          </div>
          <div class="relative flex justify-center text-xs uppercase">
            <span class="bg-background text-muted-foreground px-2">
              Security
            </span>
          </div>
        </div>

        <div class="mt-6">
          <button
            v-if="!hasPasskey"
            type="button"
            @click="handleAddPasskey"
            :disabled="addingPasskey"
            class="bg-success text-primary-foreground shadow-success/30 hover:bg-success/90 focus:ring-success/30 inline-flex w-full cursor-pointer items-center justify-center gap-2 rounded-xl px-8 py-2.5 font-bold shadow-lg transition-colors focus:ring-2 focus:ring-offset-2 focus:outline-none disabled:cursor-not-allowed disabled:opacity-50"
          >
            <Loader2 v-if="addingPasskey" class="h-5 w-5 animate-spin" />
            <KeyRound v-else class="h-5 w-5" />
            {{ addingPasskey ? 'Adding Passkey...' : 'Add Passkey' }}
          </button>
          <AlertDialog v-else>
            <AlertDialogTrigger as-child>
              <button
                type="button"
                :disabled="deletingPasskey"
                class="bg-destructive text-primary-foreground shadow-destructive/30 hover:bg-destructive/90 focus:ring-destructive/30 inline-flex w-full cursor-pointer items-center justify-center gap-2 rounded-xl px-8 py-2.5 font-bold shadow-lg transition-colors focus:ring-2 focus:ring-offset-2 focus:outline-none disabled:cursor-not-allowed disabled:opacity-50"
              >
                <Loader2 v-if="deletingPasskey" class="h-5 w-5 animate-spin" />
                <Trash2 v-else class="h-5 w-5" />
                {{ deletingPasskey ? 'Deleting Passkey...' : 'Delete Passkey' }}
              </button>
            </AlertDialogTrigger>
            <AlertDialogContent>
              <AlertDialogHeader>
                <AlertDialogTitle>Are you absolutely sure?</AlertDialogTitle>
                <AlertDialogDescription>
                  This action cannot be undone. You will need to use your
                  password to log in after deleting your passkey.
                </AlertDialogDescription>
              </AlertDialogHeader>
              <AlertDialogFooter>
                <AlertDialogCancel>Cancel</AlertDialogCancel>
                <AlertDialogAction @click="handleDeletePasskey">
                  Confirm
                </AlertDialogAction>
              </AlertDialogFooter>
            </AlertDialogContent>
          </AlertDialog>

          <p
            v-if="passkeyMessage"
            :class="[
              passkeyMessageType === 'success'
                ? 'text-success'
                : 'text-destructive',
              'mt-2 flex items-center justify-center gap-1.5 text-center text-sm',
            ]"
          >
            <Check v-if="passkeyMessageType === 'success'" class="h-4 w-4" />
            <AlertCircle v-else class="h-4 w-4" />
            {{ passkeyMessage }}
          </p>
        </div>

        <div class="relative mt-8">
          <div class="absolute inset-0 flex items-center">
            <span class="border-border w-full border-t"></span>
          </div>
          <div class="relative flex justify-center text-xs uppercase">
            <span class="bg-background text-muted-foreground px-2">
              Connected Accounts
            </span>
          </div>
        </div>

        <div class="mt-6">
          <button
            v-if="!hasGitHubBound"
            type="button"
            @click="handleBindGitHub"
            :disabled="bindingGitHub"
            class="text-primary-foreground focus:ring-primary inline-flex w-full cursor-pointer items-center justify-center gap-2 rounded-xl bg-black px-8 py-2.5 font-bold shadow-lg transition-colors hover:bg-black/90 focus:ring-2 focus:ring-offset-2 focus:outline-none disabled:cursor-not-allowed disabled:opacity-50"
          >
            <Loader2 v-if="bindingGitHub" class="h-5 w-5 animate-spin" />
            <svg
              v-else
              xmlns="http://www.w3.org/2000/svg"
              class="h-5 w-5"
              fill="currentColor"
              viewBox="0 0 24 24"
            >
              <path
                d="M12 .297c-6.63 0-12 5.373-12 12 0 5.303 3.438 9.8 8.205 11.385.6.113.82-.258.82-.577 0-.285-.01-1.04-.015-2.04-3.338.724-4.042-1.61-4.042-1.61C4.422 18.07 3.633 17.7 3.633 17.7c-1.087-.744.084-.729.084-.729 1.205.084 1.838 1.236 1.838 1.236 1.07 1.835 2.809 1.305 3.495.998.108-.776.417-1.305.76-1.605-2.665-.3-5.466-1.332-5.466-5.93 0-1.31.465-2.38 1.235-3.22-.135-.303-.54-1.523.105-3.176 0 0 1.005-.322 3.3 1.23.96-.267 1.98-.399 3-.405 1.02.006 2.04.138 3 .405 2.28-1.552 3.285-1.23 3.285-1.23.645 1.653.24 2.873.12 3.176.765.84 1.23 1.91 1.23 3.22 0 4.61-2.805 5.625-5.475 5.92.42.36.81 1.096.81 2.22 0 1.606-.015 2.896-.015 3.286 0 .315.21.69.825.57C20.565 22.092 24 17.592 24 12.297c0-6.627-5.373-12-12-12"
              />
            </svg>
            {{ bindingGitHub ? 'Binding GitHub...' : 'Bind GitHub Account' }}
          </button>
          <AlertDialog v-else>
            <AlertDialogTrigger as-child>
              <button
                type="button"
                :disabled="unbindingGitHub"
                class="text-primary-foreground focus:ring-primary inline-flex w-full cursor-pointer items-center justify-center gap-2 rounded-xl bg-black px-8 py-2.5 font-bold shadow-lg transition-colors hover:bg-black/90 focus:ring-2 focus:ring-offset-2 focus:outline-none disabled:cursor-not-allowed disabled:opacity-50 dark:text-white"
              >
                <Loader2 v-if="unbindingGitHub" class="h-5 w-5 animate-spin" />
                <Trash2 v-else class="h-5 w-5" />
                {{ unbindingGitHub ? 'Unbinding...' : 'Unbind GitHub Account' }}
              </button>
            </AlertDialogTrigger>
            <AlertDialogContent>
              <AlertDialogHeader>
                <AlertDialogTitle>Are you absolutely sure?</AlertDialogTitle>
                <AlertDialogDescription>
                  This action will unbind your GitHub account from your profile.
                  You will no longer be able to log in with GitHub after this.
                </AlertDialogDescription>
              </AlertDialogHeader>
              <AlertDialogFooter>
                <AlertDialogCancel>Cancel</AlertDialogCancel>
                <AlertDialogAction @click="handleUnbindGitHub">
                  Confirm
                </AlertDialogAction>
              </AlertDialogFooter>
            </AlertDialogContent>
          </AlertDialog>

          <p
            v-if="githubMessage"
            :class="[
              githubMessageType === 'success'
                ? 'text-success'
                : 'text-destructive',
              'mt-2 flex items-center justify-center gap-1.5 text-center text-sm',
            ]"
          >
            <Check v-if="githubMessageType === 'success'" class="h-4 w-4" />
            <AlertCircle v-else class="h-4 w-4" />
            {{ githubMessage }}
          </p>
        </div>
  </AuthLayout>
</template>

// react-app/src/views/Auth/ProfileSettingView.tsx
import request from '@/api/request';
import { useAuthStore } from '@/stores/authState';
import type { ProfileForm } from '@/types';
import { startRegistration } from '@simplewebauthn/browser';
import { motion } from 'framer-motion';
import axios from 'axios';
import { User } from 'lucide-react';
import { useEffect, useState } from 'react';
import { useSearchParams } from 'react-router-dom';
import {
  AlertDialog,
  AvatarUpload,
  ProfileFormFields,
  SecuritySection,
} from './components';

export default function ProfileSettingView() {
  const [searchParams] = useSearchParams();
  const auth = useAuthStore();

  const [form, setForm] = useState<ProfileForm>({
    name: '',
    username: '',
    gender: '',
    email: '',
    mobile: '',
    password: '',
  });

  const [errors, setErrors] = useState<{
    name?: string;
    username?: string;
    email?: string;
    mobile?: string;
    password?: string;
    submit?: string;
  }>({});
  const [saving, setSaving] = useState(false);
  const [message, setMessage] = useState('');
  const [messageType, setMessageType] = useState<'success' | 'error'>(
    'success',
  );
  const [avatarUrl, setAvatarUrl] = useState('/api/v1/media/default.png');
  const [showPassword, setShowPassword] = useState(false);

  const [hasPasskey, setHasPasskey] = useState(false);
  const [addingPasskey, setAddingPasskey] = useState(false);
  const [deletingPasskey, setDeletingPasskey] = useState(false);
  const [passkeyMessage, setPasskeyMessage] = useState('');
  const [passkeyMessageType, setPasskeyMessageType] = useState<
    'success' | 'error'
  >('success');

  const [hasGitHubBound, setHasGitHubBound] = useState(false);
  const [bindingGitHub, setBindingGitHub] = useState(false);
  const [unbindingGitHub, setUnbindingGitHub] = useState(false);
  const [githubMessage, setGithubMessage] = useState('');
  const [githubMessageType, setGithubMessageType] = useState<
    'success' | 'error'
  >('success');

  const [passkeyDialogOpen, setPasskeyDialogOpen] = useState(false);
  const [githubDialogOpen, setGithubDialogOpen] = useState(false);

  useEffect(() => {
    if (auth.user) {
      setForm({
        name: auth.user.name || '',
        username: auth.user.username || '',
        gender: auth.user.gender || '',
        email: auth.user.email || '',
        mobile: auth.user.mobile || '',
        password: '',
      });
      setHasPasskey(!!auth.user.has_passkey);
      setHasGitHubBound(!!auth.user.github_bound);

      if (auth.user.photo?.startsWith('http')) {
        setAvatarUrl(auth.user.photo);
      } else if (auth.user.photo) {
        setAvatarUrl(`/api/v1/media/${auth.user.photo}`);
      }
    }
  }, [auth.user]);

  useEffect(() => {
    const error = searchParams.get('error');
    const success = searchParams.get('success');

    if (error) {
      const errorMessages: Record<string, string> = {
        not_logged_in: 'Please log in first to bind GitHub account',
        github_already_bound:
          'This GitHub account is already bound to another user',
        github_not_bound: 'Your account is not bound to GitHub',
        invalid_oauth_state: 'Invalid OAuth state, please try again',
        missing_pkce_info: 'Missing PKCE information, please try again',
        github_auth_failed: 'GitHub authentication failed, please try again',
      };
      setGithubMessage(errorMessages[error] || 'GitHub binding failed');
      setGithubMessageType('error');
      window.history.replaceState({}, document.title, window.location.pathname);
    }

    if (success) {
      const successMessages: Record<string, string> = {
        github_bound: 'GitHub account bound successfully!',
        github_unbound: 'GitHub account unbound successfully!',
      };
      setGithubMessage(successMessages[success] || 'Operation successful');
      setGithubMessageType('success');
      auth.hydrateAuth();
      window.history.replaceState({}, document.title, window.location.pathname);
    }
  }, [searchParams, auth]);

  const toggleGender = (value: string) => {
    setForm((prev) => ({
      ...prev,
      gender: prev.gender === value ? '' : value,
    }));
  };

  const handlePhotoUpload = async (
    event: React.ChangeEvent<HTMLInputElement>,
  ) => {
    const file = event.target.files?.[0];
    if (!file) return;

    const formData = new FormData();
    formData.append('image', file);

    try {
      const response = await request.put('/auth/upload-pic', formData, {
        headers: { 'Content-Type': 'multipart/form-data' },
      });

      if (response.data) {
        await auth.hydrateAuth();
        setMessage('Avatar updated successfully!');
        setMessageType('success');
      }
    } catch {
      setMessage('Network error, please try again');
      setMessageType('error');
    }

    event.target.value = '';
  };

  const handleAddPasskey = async () => {
    setAddingPasskey(true);
    setPasskeyMessage('');

    try {
      const optionsRes = await request.get(
        '/auth/passkey/registration-options',
      );
      const options = optionsRes.data.data;

      const credential = await startRegistration({ optionsJSON: options });

      await request.post('/auth/passkey/register', {
        response: credential,
      });

      setPasskeyMessage('Passkey added successfully!');
      setPasskeyMessageType('success');
      setHasPasskey(true);
      await auth.hydrateAuth();
    } catch (err) {
      console.error('Add passkey error:', err);
      setPasskeyMessage('Failed to add passkey');
      setPasskeyMessageType('error');
    } finally {
      setAddingPasskey(false);
    }
  };

  const handleDeletePasskey = async () => {
    setDeletingPasskey(true);
    setPasskeyMessage('');

    try {
      await request.delete('/auth/passkey/delete');
      setPasskeyMessage('Passkey deleted successfully!');
      setPasskeyMessageType('success');
      setHasPasskey(false);
      await auth.hydrateAuth();
    } catch (err) {
      console.error('Delete passkey error:', err);
      setPasskeyMessage('Failed to delete passkey');
      setPasskeyMessageType('error');
    } finally {
      setDeletingPasskey(false);
    }
  };

  const handleBindGitHub = () => {
    setBindingGitHub(true);
    setGithubMessage('');
    window.location.href = '/api/v1/auth/github/bind';
  };

  const handleUnbindGitHub = async () => {
    setUnbindingGitHub(true);
    setGithubMessage('');

    try {
      await request.post('/auth/github/unbind');
      setGithubMessage('GitHub account unbound successfully!');
      setGithubMessageType('success');
      setHasGitHubBound(false);
      await auth.hydrateAuth();
    } catch (err) {
      console.error('Unbind GitHub error:', err);
      setGithubMessage('Failed to unbind GitHub account');
      setGithubMessageType('error');
    } finally {
      setUnbindingGitHub(false);
    }
  };

  const handleSubmit = async (e: React.SyntheticEvent) => {
    e.preventDefault();
    setErrors({});
    setMessage('');
    setSaving(true);

    try {
      const payload = {
        name: form.name || '',
        username: form.username || '',
        gender: form.gender || null,
        email: form.email || null,
        mobile: form.mobile || null,
        password: form.password || null,
      };

      const response = await request.put('/auth/settings', payload);

      if (response.data.code === 200) {
        await auth.hydrateAuth();
        setForm((prev) => ({ ...prev, password: '' }));
        setMessage('Profile updated successfully!');
        setMessageType('success');
      } else {
        setMessage(response.data.message || 'Failed to update profile');
        setMessageType('error');
      }
    } catch (err) {
      if (axios.isAxiosError(err) && err.response?.data) {
        const data = err.response.data as Record<
          string,
          string | string[] | undefined
        >;
        setErrors({
          name: typeof data.name === 'string' ? data.name : undefined,
          username:
            typeof data.username === 'string' ? data.username : undefined,
          email: typeof data.email === 'string' ? data.email : undefined,
          mobile: typeof data.mobile === 'string' ? data.mobile : undefined,
          password:
            typeof data.password === 'string' ? data.password : undefined,
          submit: typeof data.error === 'string' ? data.error : undefined,
        });
        if (!errors.submit) {
          setMessage('Failed to update profile');
          setMessageType('error');
        }
      } else {
        setMessage('Network error, please try again');
        setMessageType('error');
      }
    } finally {
      setSaving(false);
    }
  };

  return (
    <div className="font-body bg-background relative mb-24 h-full overflow-hidden">
      {/* Main Content */}
      <main className="relative z-10 mt-4 flex flex-col items-center px-5 pt-8 pb-10">
        {/* Header Section */}
        <motion.div
          initial={{ opacity: 0, y: 8 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.7, ease: 'easeOut', delay: 0.05 }}
          className="mb-8 flex flex-col items-center justify-center"
        >
          <div className="bg-primary text-primary-foreground mb-5 flex h-16 w-16 items-center justify-center rounded-full shadow-[0_8px_16px_rgba(37,99,235,0.25)]">
            <User className="size-8" />
          </div>
          <h2 className="font-headline text-foreground text-center text-[28px] font-extrabold tracking-tight">
            Profile Settings
          </h2>
          <p className="text-muted-foreground mt-1 text-center text-[15px] font-medium">
            Manage your profile and preferences
          </p>
        </motion.div>

        {/* Settings Card */}
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.5, ease: 'easeOut', delay: 0.15 }}
          className="border-border/50 bg-card/70 w-full max-w-100 rounded-4xl border p-6 shadow-xl"
        >
          <form className="flex flex-col" onSubmit={handleSubmit}>
            {/* Avatar Upload */}
            <AvatarUpload
              avatarUrl={avatarUrl}
              onPhotoUpload={handlePhotoUpload}
            />

            {/* Form Fields */}
            <ProfileFormFields
              form={form}
              errors={errors}
              showPassword={showPassword}
              toggleGender={toggleGender}
              setForm={setForm}
              setShowPassword={setShowPassword}
            />

            {/* Security Section */}
            <SecuritySection
              hasPasskey={hasPasskey}
              addingPasskey={addingPasskey}
              deletingPasskey={deletingPasskey}
              passkeyMessage={passkeyMessage}
              passkeyMessageType={passkeyMessageType}
              hasGitHubBound={hasGitHubBound}
              bindingGitHub={bindingGitHub}
              unbindingGitHub={unbindingGitHub}
              githubMessage={githubMessage}
              githubMessageType={githubMessageType}
              onAddPasskey={handleAddPasskey}
              onBindGitHub={handleBindGitHub}
              onOpenPasskeyDialog={() => setPasskeyDialogOpen(true)}
              onOpenGithubDialog={() => setGithubDialogOpen(true)}
            />

            {/* Save Button */}
            <button
              type="submit"
              disabled={saving}
              className="bg-primary text-primary-foreground hover:bg-primary/90 w-full rounded-full py-4 text-[15px] font-bold shadow-[0_8px_16px_rgba(30,58,138,0.2)] transition-all active:scale-[0.98] disabled:opacity-70"
            >
              {saving ? (
                <span className="flex items-center justify-center gap-2">
                  <span className="border-primary-foreground h-4 w-4 animate-spin rounded-full border-2 border-t-transparent"></span>
                  Saving...
                </span>
              ) : (
                'Save Changes'
              )}
            </button>

            {/* Message */}
            {message && (
              <div
                className={`mt-4 rounded-2xl p-3 text-center text-[12px] font-medium ${
                  messageType === 'success'
                    ? 'bg-success/10 text-success'
                    : 'bg-destructive/10 text-destructive'
                }`}
              >
                {message}
              </div>
            )}
          </form>
        </motion.div>
      </main>

      {/* Dialogs */}
      <AlertDialog
        open={passkeyDialogOpen}
        onOpenChange={setPasskeyDialogOpen}
        title="Are you absolutely sure?"
        description="This action cannot be undone. You will need to use your password to log in after deleting your passkey."
        onConfirm={handleDeletePasskey}
        destructive
      />

      <AlertDialog
        open={githubDialogOpen}
        onOpenChange={setGithubDialogOpen}
        title="Are you absolutely sure?"
        description="This action will unbind your GitHub account from your profile. You will no longer be able to log in with GitHub after this."
        onConfirm={handleUnbindGitHub}
        destructive
      />
    </div>
  );
}
