// frontend/src/views/ProfileSettingView.vue
<template>
  <div
    class="m-4 mx-auto max-w-md rounded-[40px] bg-white/80 p-8 shadow-xl backdrop-blur-sm dark:bg-gray-800/50"
  >
    <p class="text-2xl font-bold dark:text-white">Profile Settings</p>
    <p class="mb-4 text-gray-500 italic dark:text-gray-400">
      Manage your profile and preferences here.
    </p>
    <!-- Avatar Section -->
    <div class="mb-8 flex justify-center">
      <div class="relative">
        <div
          class="h-24 w-24 overflow-hidden rounded-full border-4 border-white shadow-lg dark:border-gray-700"
        >
          <img
            :src="avatarUrl"
            alt="Avatar"
            class="h-full w-full object-cover"
          />
        </div>
        <div class="absolute right-0 bottom-0">
          <input
            id="photo-upload"
            type="file"
            accept=".jpg,.jpeg,.png,.gif"
            class="sr-only"
            @change="handlePhotoUpload"
          />
          <label
            for="photo-upload"
            class="flex h-8 w-8 cursor-pointer items-center justify-center rounded-full bg-blue-500 text-white shadow-md transition-colors hover:bg-blue-600"
          >
            <svg
              xmlns="http://www.w3.org/2000/svg"
              fill="none"
              viewBox="0 0 24 24"
              stroke-width="1.5"
              stroke="currentColor"
              class="pointer-events-none h-4 w-4"
            >
              <path
                stroke-linecap="round"
                stroke-linejoin="round"
                d="M6.827 6.175A2.31 2.31 0 015.186 7.23c-.38.054-.757.112-1.134.175C2.999 7.58 2.25 8.507 2.25 9.574V18a2.25 2.25 0 002.25 2.25h15A2.25 2.25 0 0021.75 18V9.574c0-1.067-.75-1.994-1.802-2.169a47.865 47.865 0 00-1.134-.175 2.31 2.31 0 01-1.64-1.055l-.822-1.316a2.192 2.192 0 00-1.736-1.039 48.774 48.774 0 00-5.232 0 2.192 2.192 0 00-1.736 1.039l-.821 1.316z"
              />
              <path
                stroke-linecap="round"
                stroke-linejoin="round"
                d="M16.5 12.75a4.5 4.5 0 11-9 0 4.5 4.5 0 019 0zM18.75 10.5h.008v.008h-.008V10.5z"
              />
            </svg>
          </label>
        </div>
      </div>
    </div>

    <!-- Form Section -->
    <form @submit.prevent="handleSubmit">
      <!-- Name -->
      <div class="mb-4">
        <label
          class="mb-3 block text-sm font-medium text-gray-700 dark:text-gray-300"
        >
          Name
        </label>
        <input
          v-model="form.name"
          type="text"
          autocomplete="off"
          class="w-full rounded-lg border border-gray-300 px-4 py-2 focus:border-blue-500 focus:ring-2 focus:ring-blue-500 focus:outline-none dark:border-gray-600 dark:bg-gray-700 dark:text-white"
          placeholder="Your display name"
        />
        <p v-if="errors.name" class="mt-1 text-sm text-red-500">
          {{ errors.name }}
        </p>
      </div>

      <!-- Username -->
      <div class="mb-4">
        <label
          class="mb-3 block text-sm font-medium text-gray-700 dark:text-gray-300"
        >
          Username
          <span class="text-xs text-red-400 italic">* Login-in name</span>
        </label>
        <input
          v-model="form.username"
          type="text"
          autocomplete="off"
          class="w-full rounded-lg border border-gray-300 px-4 py-2 focus:border-blue-500 focus:ring-2 focus:ring-blue-500 focus:outline-none dark:border-gray-600 dark:bg-gray-700 dark:text-white"
          placeholder="Your username"
        />
        <p v-if="errors.username" class="mt-1 text-sm text-red-500">
          {{ errors.username }}
        </p>
      </div>

      <!-- Gender -->
      <div class="mb-4">
        <label
          class="mb-3 block text-sm font-medium text-gray-700 dark:text-gray-300"
        >
          Gender
        </label>
        <div class="flex gap-4">
          <label class="group relative flex-1 cursor-pointer">
            <input
              v-model="form.gender"
              type="radio"
              value="male"
              class="peer sr-only"
              @click="toggleGender('male')"
            />
            <div
              class="flex items-center justify-between rounded-xl border-2 border-gray-100 bg-white px-4 py-3 shadow-sm transition-all duration-200 group-active:scale-95 peer-checked:border-blue-500 peer-checked:bg-blue-50/50 peer-checked:shadow-blue-100/50 hover:border-blue-200 dark:border-gray-600 dark:bg-gray-700 dark:peer-checked:border-blue-500 dark:peer-checked:bg-blue-500/10 dark:peer-checked:shadow-none dark:hover:border-blue-500/50"
            >
              <span
                class="text-sm font-semibold text-gray-600 transition-colors peer-checked:text-blue-700 dark:text-gray-300 dark:peer-checked:text-blue-400"
                >Male</span
              >
            </div>
          </label>
          <label class="group relative flex-1 cursor-pointer">
            <input
              v-model="form.gender"
              type="radio"
              value="female"
              class="peer sr-only"
              @click="toggleGender('female')"
            />
            <div
              class="flex items-center justify-between rounded-xl border-2 border-gray-100 bg-white px-4 py-3 shadow-sm transition-all duration-200 group-active:scale-95 peer-checked:border-blue-500 peer-checked:bg-blue-50/50 peer-checked:shadow-blue-100/50 hover:border-blue-200 dark:border-gray-600 dark:bg-gray-700 dark:peer-checked:border-blue-500 dark:peer-checked:bg-blue-500/10 dark:peer-checked:shadow-none dark:hover:border-blue-500/50"
            >
              <span
                class="text-sm font-semibold text-gray-600 transition-colors peer-checked:text-blue-700 dark:text-gray-300 dark:peer-checked:text-blue-400"
                >Female</span
              >
            </div>
          </label>
        </div>
      </div>

      <!-- Email -->
      <div class="mb-4">
        <label
          class="mb-3 block text-sm font-medium text-gray-700 dark:text-gray-300"
        >
          Email
        </label>
        <input
          v-model="form.email"
          type="email"
          autocomplete="off"
          class="w-full rounded-lg border border-gray-300 px-4 py-2 focus:border-blue-500 focus:ring-2 focus:ring-blue-500 focus:outline-none dark:border-gray-600 dark:bg-gray-700 dark:text-white"
          placeholder="your@email.com"
        />
        <p v-if="errors.email" class="mt-1 text-sm text-red-500">
          {{ errors.email }}
        </p>
      </div>

      <!-- Mobile -->
      <div class="mb-4">
        <label
          class="mb-3 block text-sm font-medium text-gray-700 dark:text-gray-300"
        >
          Mobile
        </label>
        <input
          v-model="form.mobile"
          type="tel"
          autocomplete="off"
          class="w-full rounded-lg border border-gray-300 px-4 py-2 focus:border-blue-500 focus:ring-2 focus:ring-blue-500 focus:outline-none dark:border-gray-600 dark:bg-gray-700 dark:text-white"
          placeholder="Your phone number"
        />
        <p v-if="errors.mobile" class="mt-1 text-sm text-red-500">
          {{ errors.mobile }}
        </p>
      </div>

      <!-- Password -->
      <div class="mb-6">
        <label
          class="mb-3 block text-sm font-medium text-gray-700 dark:text-gray-300"
        >
          Password
        </label>
        <input
          v-model="form.password"
          type="password"
          class="w-full rounded-lg border border-gray-300 px-4 py-2 focus:border-blue-500 focus:ring-2 focus:ring-blue-500 focus:outline-none dark:border-gray-600 dark:bg-gray-700 dark:text-white"
          placeholder="Leave empty to keep current"
        />
        <p v-if="errors.password" class="mt-1 text-sm text-red-500">
          {{ errors.password }}
        </p>
      </div>

      <!-- Submit Button -->
      <button
        type="submit"
        :disabled="saving"
        class="mt-4 w-full rounded-xl bg-blue-600 px-6 py-2.5 font-semibold text-white shadow-md transition-colors hover:bg-blue-700 focus:ring-2 focus:ring-blue-500 focus:ring-offset-2 focus:outline-none disabled:cursor-not-allowed disabled:opacity-50 dark:focus:ring-offset-gray-800"
      >
        <span v-if="saving" class="flex items-center justify-center gap-2">
          <span
            class="h-4 w-4 animate-spin rounded-full border-2 border-white border-t-transparent"
          ></span>
          Saving...
        </span>
        <span v-else>Save</span>
      </button>

      <!-- Success/Error Messages -->
      <div v-if="message" class="mt-4 text-center">
        <p
          :class="[
            messageType === 'success'
              ? 'bg-green-50 text-green-600'
              : 'bg-red-50 text-red-600',
            'rounded-3xl px-4 py-2',
          ]"
        >
          {{ message }}
        </p>
      </div>
    </form>
  </div>
</template>

<script setup lang="ts">
import request from "@/request";
import { useAuthStore } from "@/stores/auth";
import type { ProfileForm } from "@/types";
import { computed, onMounted, ref } from "vue";
const authStore = useAuthStore();

const form = ref<ProfileForm>({
  name: "",
  username: "",
  gender: "",
  email: "",
  mobile: "",
  password: "",
});

const errors = ref<Record<string, string>>({});
const saving = ref(false);
const message = ref("");
const messageType = ref<"success" | "error">("success");

const avatarUrl = computed(() => {
  if (authStore.user?.photo) {
    return `/api/v1/media/${authStore.user.photo}`;
  }
  return "/api/v1/media/default.png";
});

const loadUserData = () => {
  if (authStore.user) {
    form.value.name = authStore.user.name || "";
    form.value.username = authStore.user.username || "";
    form.value.gender = authStore.user.gender || "";
    form.value.email = authStore.user.email || "";
    const userWithMobile = authStore.user as { mobile?: string } | null;
    form.value.mobile = userWithMobile?.mobile || "";
  }
};

const toggleGender = (value: string) => {
  if (form.value.gender === value) {
    form.value.gender = "";
  } else {
    form.value.gender = value;
  }
};

const handlePhotoUpload = async (event: Event) => {
  const input = event.target as HTMLInputElement;
  console.log("Selected file:", input.files?.[0]);
  const file = input.files?.[0];

  if (!file) return;

  const formData = new FormData();
  formData.append("image", file);

  try {
    const response = await request.put("/user/upload-pic", formData, {
      headers: {
        "Content-Type": "multipart/form-data",
      },
    });

    if (response.data) {
      await authStore.fetchUser();
      message.value = "Avatar updated successfully!";
      messageType.value = "success";
    } else {
      message.value = response.data?.message || "Failed to upload avatar";
      messageType.value = "error";
    }
  } catch (error) {
    console.error("Avatar upload error:", error);
    message.value = "Network error, please try again";
    messageType.value = "error";
  }

  input.value = "";
};

const handleSubmit = async () => {
  saving.value = true;
  errors.value = {};
  message.value = "";

  try {
    const payload = {
      name: form.value.name || "",
      username: form.value.username || "",
      gender: form.value.gender || null,
      email: form.value.email || null,
      mobile: form.value.mobile || null,
      password: form.value.password || null,
    };

    const response = await request.put("/user/settings", payload);

    if (response.data.code === 200) {
      await authStore.fetchUser();
      form.value.password = "";
      message.value = "Profile updated successfully!";
      messageType.value = "success";
    } else {
      message.value = response.data.message || "Failed to update profile";
      messageType.value = "error";
    }
  } catch (error) {
    console.error("Settings update error:", error);
    message.value = "Network error, please try again";
    messageType.value = "error";
  } finally {
    saving.value = false;
  }
};

onMounted(() => {
  loadUserData();
});
</script>

<style scoped>
.form-group {
  margin-bottom: 1rem;
}
</style>

// react-app/src/views/Auth/ProfileSettingView.tsx
import request from '@/api/request';
import { useAuthStore } from '@/stores/authState';
import type { ProfileForm } from '@/types';
import { startRegistration } from '@simplewebauthn/browser';
import { motion } from 'framer-motion';
import axios from 'axios';
import { User } from 'lucide-react';
import { useEffect, useState } from 'react';
import { useSearchParams } from 'react-router-dom';
import {
  AlertDialog,
  AvatarUpload,
  ProfileFormFields,
  SecuritySection,
} from './components';

export default function ProfileSettingView() {
  const [searchParams] = useSearchParams();
  const auth = useAuthStore();

  const [form, setForm] = useState<ProfileForm>({
    name: '',
    username: '',
    gender: '',
    email: '',
    mobile: '',
    password: '',
  });

  const [errors, setErrors] = useState<{
    name?: string;
    username?: string;
    email?: string;
    mobile?: string;
    password?: string;
    submit?: string;
  }>({});
  const [saving, setSaving] = useState(false);
  const [message, setMessage] = useState('');
  const [messageType, setMessageType] = useState<'success' | 'error'>(
    'success',
  );
  const [avatarUrl, setAvatarUrl] = useState('/api/v1/media/default.png');
  const [showPassword, setShowPassword] = useState(false);

  const [hasPasskey, setHasPasskey] = useState(false);
  const [addingPasskey, setAddingPasskey] = useState(false);
  const [deletingPasskey, setDeletingPasskey] = useState(false);
  const [passkeyMessage, setPasskeyMessage] = useState('');
  const [passkeyMessageType, setPasskeyMessageType] = useState<
    'success' | 'error'
  >('success');

  const [hasGitHubBound, setHasGitHubBound] = useState(false);
  const [bindingGitHub, setBindingGitHub] = useState(false);
  const [unbindingGitHub, setUnbindingGitHub] = useState(false);
  const [githubMessage, setGithubMessage] = useState('');
  const [githubMessageType, setGithubMessageType] = useState<
    'success' | 'error'
  >('success');

  const [passkeyDialogOpen, setPasskeyDialogOpen] = useState(false);
  const [githubDialogOpen, setGithubDialogOpen] = useState(false);

  useEffect(() => {
    if (auth.user) {
      setForm({
        name: auth.user.name || '',
        username: auth.user.username || '',
        gender: auth.user.gender || '',
        email: auth.user.email || '',
        mobile: auth.user.mobile || '',
        password: '',
      });
      setHasPasskey(!!auth.user.has_passkey);
      setHasGitHubBound(!!auth.user.github_bound);

      if (auth.user.photo?.startsWith('http')) {
        setAvatarUrl(auth.user.photo);
      } else if (auth.user.photo) {
        setAvatarUrl(`/api/v1/media/${auth.user.photo}`);
      }
    }
  }, [auth.user]);

  useEffect(() => {
    const error = searchParams.get('error');
    const success = searchParams.get('success');

    if (error) {
      const errorMessages: Record<string, string> = {
        not_logged_in: 'Please log in first to bind GitHub account',
        github_already_bound:
          'This GitHub account is already bound to another user',
        github_not_bound: 'Your account is not bound to GitHub',
        invalid_oauth_state: 'Invalid OAuth state, please try again',
        missing_pkce_info: 'Missing PKCE information, please try again',
        github_auth_failed: 'GitHub authentication failed, please try again',
      };
      setGithubMessage(errorMessages[error] || 'GitHub binding failed');
      setGithubMessageType('error');
      window.history.replaceState({}, document.title, window.location.pathname);
    }

    if (success) {
      const successMessages: Record<string, string> = {
        github_bound: 'GitHub account bound successfully!',
        github_unbound: 'GitHub account unbound successfully!',
      };
      setGithubMessage(successMessages[success] || 'Operation successful');
      setGithubMessageType('success');
      auth.hydrateAuth();
      window.history.replaceState({}, document.title, window.location.pathname);
    }
  }, [searchParams, auth]);

  const toggleGender = (value: string) => {
    setForm((prev) => ({
      ...prev,
      gender: prev.gender === value ? '' : value,
    }));
  };

  const handlePhotoUpload = async (
    event: React.ChangeEvent<HTMLInputElement>,
  ) => {
    const file = event.target.files?.[0];
    if (!file) return;

    const formData = new FormData();
    formData.append('image', file);

    try {
      const response = await request.put('/auth/upload-pic', formData, {
        headers: { 'Content-Type': 'multipart/form-data' },
      });

      if (response.data) {
        await auth.hydrateAuth();
        setMessage('Avatar updated successfully!');
        setMessageType('success');
      }
    } catch {
      setMessage('Network error, please try again');
      setMessageType('error');
    }

    event.target.value = '';
  };

  const handleAddPasskey = async () => {
    setAddingPasskey(true);
    setPasskeyMessage('');

    try {
      const optionsRes = await request.get(
        '/auth/passkey/registration-options',
      );
      const options = optionsRes.data.data;

      const credential = await startRegistration({ optionsJSON: options });

      await request.post('/auth/passkey/register', {
        response: credential,
      });

      setPasskeyMessage('Passkey added successfully!');
      setPasskeyMessageType('success');
      setHasPasskey(true);
      await auth.hydrateAuth();
    } catch (err) {
      console.error('Add passkey error:', err);
      setPasskeyMessage('Failed to add passkey');
      setPasskeyMessageType('error');
    } finally {
      setAddingPasskey(false);
    }
  };

  const handleDeletePasskey = async () => {
    setDeletingPasskey(true);
    setPasskeyMessage('');

    try {
      await request.delete('/auth/passkey/delete');
      setPasskeyMessage('Passkey deleted successfully!');
      setPasskeyMessageType('success');
      setHasPasskey(false);
      await auth.hydrateAuth();
    } catch (err) {
      console.error('Delete passkey error:', err);
      setPasskeyMessage('Failed to delete passkey');
      setPasskeyMessageType('error');
    } finally {
      setDeletingPasskey(false);
    }
  };

  const handleBindGitHub = () => {
    setBindingGitHub(true);
    setGithubMessage('');
    window.location.href = '/api/v1/auth/github/bind';
  };

  const handleUnbindGitHub = async () => {
    setUnbindingGitHub(true);
    setGithubMessage('');

    try {
      await request.post('/auth/github/unbind');
      setGithubMessage('GitHub account unbound successfully!');
      setGithubMessageType('success');
      setHasGitHubBound(false);
      await auth.hydrateAuth();
    } catch (err) {
      console.error('Unbind GitHub error:', err);
      setGithubMessage('Failed to unbind GitHub account');
      setGithubMessageType('error');
    } finally {
      setUnbindingGitHub(false);
    }
  };

  const handleSubmit = async (e: React.SyntheticEvent) => {
    e.preventDefault();
    setErrors({});
    setMessage('');
    setSaving(true);

    try {
      const payload = {
        name: form.name || '',
        username: form.username || '',
        gender: form.gender || null,
        email: form.email || null,
        mobile: form.mobile || null,
        password: form.password || null,
      };

      const response = await request.put('/auth/settings', payload);

      if (response.data.code === 200) {
        await auth.hydrateAuth();
        setForm((prev) => ({ ...prev, password: '' }));
        setMessage('Profile updated successfully!');
        setMessageType('success');
      } else {
        setMessage(response.data.message || 'Failed to update profile');
        setMessageType('error');
      }
    } catch (err) {
      if (axios.isAxiosError(err) && err.response?.data) {
        const data = err.response.data as Record<
          string,
          string | string[] | undefined
        >;
        setErrors({
          name: typeof data.name === 'string' ? data.name : undefined,
          username:
            typeof data.username === 'string' ? data.username : undefined,
          email: typeof data.email === 'string' ? data.email : undefined,
          mobile: typeof data.mobile === 'string' ? data.mobile : undefined,
          password:
            typeof data.password === 'string' ? data.password : undefined,
          submit: typeof data.error === 'string' ? data.error : undefined,
        });
        if (!errors.submit) {
          setMessage('Failed to update profile');
          setMessageType('error');
        }
      } else {
        setMessage('Network error, please try again');
        setMessageType('error');
      }
    } finally {
      setSaving(false);
    }
  };

  return (
    <div className="font-body relative mb-24 h-full overflow-hidden bg-gray-50 dark:bg-gray-800">
      {/* Main Content */}
      <main className="relative z-10 mt-4 flex flex-col items-center px-5 pt-8 pb-10">
        {/* Header Section */}
        <motion.div
          initial={{ opacity: 0, y: 8 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.7, ease: 'easeOut', delay: 0.05 }}
          className="mb-8 flex flex-col items-center justify-center"
        >
          <div className="mb-5 flex h-16 w-16 items-center justify-center rounded-full bg-[#2563eb] text-white shadow-[0_8px_16px_rgba(37,99,235,0.25)]">
            <User className="size-8" />
          </div>
          <h2 className="font-headline text-center text-[28px] font-extrabold tracking-tight text-[#111827] dark:text-white">
            Profile Settings
          </h2>
          <p className="mt-1 text-center text-[15px] font-medium text-[#4b5563] dark:text-gray-400">
            Manage your profile and preferences
          </p>
        </motion.div>

        {/* Settings Card */}
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.5, ease: 'easeOut', delay: 0.15 }}
          className="w-full max-w-100 rounded-4xl border border-white/50 bg-white/70 p-6 shadow-xl dark:border-slate-700/50 dark:bg-slate-800/60"
        >
          <form className="flex flex-col" onSubmit={handleSubmit}>
            {/* Avatar Upload */}
            <AvatarUpload
              avatarUrl={avatarUrl}
              onPhotoUpload={handlePhotoUpload}
            />

            {/* Form Fields */}
            <ProfileFormFields
              form={form}
              errors={errors}
              showPassword={showPassword}
              toggleGender={toggleGender}
              setForm={setForm}
              setShowPassword={setShowPassword}
            />

            {/* Security Section */}
            <SecuritySection
              hasPasskey={hasPasskey}
              addingPasskey={addingPasskey}
              deletingPasskey={deletingPasskey}
              passkeyMessage={passkeyMessage}
              passkeyMessageType={passkeyMessageType}
              hasGitHubBound={hasGitHubBound}
              bindingGitHub={bindingGitHub}
              unbindingGitHub={unbindingGitHub}
              githubMessage={githubMessage}
              githubMessageType={githubMessageType}
              onAddPasskey={handleAddPasskey}
              onBindGitHub={handleBindGitHub}
              onOpenPasskeyDialog={() => setPasskeyDialogOpen(true)}
              onOpenGithubDialog={() => setGithubDialogOpen(true)}
            />

            {/* Save Button */}
            <button
              type="submit"
              disabled={saving}
              className="w-full rounded-full bg-blue-500 py-4 text-[15px] font-bold text-white shadow-[0_8px_16px_rgba(30,58,138,0.2)] transition-all hover:bg-[#1e3a8a]/90 active:scale-[0.98] disabled:opacity-70 dark:bg-blue-600 dark:hover:bg-blue-600/90"
            >
              {saving ? (
                <span className="flex items-center justify-center gap-2">
                  <span className="h-4 w-4 animate-spin rounded-full border-2 border-white border-t-transparent"></span>
                  Saving...
                </span>
              ) : (
                'Save Changes'
              )}
            </button>

            {/* Message */}
            {message && (
              <div
                className={`mt-4 rounded-2xl p-3 text-center text-[12px] font-medium ${
                  messageType === 'success'
                    ? 'bg-green-100 text-green-600 dark:bg-green-900/20 dark:text-green-400'
                    : 'bg-red-100 text-red-600 dark:bg-red-900/20 dark:text-red-400'
                }`}
              >
                {message}
              </div>
            )}
          </form>
        </motion.div>
      </main>

      {/* Dialogs */}
      <AlertDialog
        open={passkeyDialogOpen}
        onOpenChange={setPasskeyDialogOpen}
        title="Are you absolutely sure?"
        description="This action cannot be undone. You will need to use your password to log in after deleting your passkey."
        onConfirm={handleDeletePasskey}
        destructive
      />

      <AlertDialog
        open={githubDialogOpen}
        onOpenChange={setGithubDialogOpen}
        title="Are you absolutely sure?"
        description="This action will unbind your GitHub account from your profile. You will no longer be able to log in with GitHub after this."
        onConfirm={handleUnbindGitHub}
        destructive
      />
    </div>
  );
}
