// react-app/src/views/Home/components/BentoCalendar.tsx
import { BentoCard } from '@/components/bento/BentoCard';
import dayjs from 'dayjs';

export function BentoCalendar() {
  const now = dayjs();
  const monthLabel = now.format('MMMM');
  const yearLabel = now.format('YYYY');

  const weekday = now.day(); // 0-6, 0是周日
  const weekdayLabels = ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'];
  const weekdayHeaders = weekdayLabels.map((label, idx) => (
    <span
      key={idx}
      className={`py-1 text-xs font-medium ${
        idx === weekday
          ? 'rounded-2xl bg-blue-50 font-bold text-blue-600 dark:bg-blue-900/30 dark:text-blue-400'
          : ''
      }`}
    >
      {label}
    </span>
  ));

  const startOffset = () => {
    const offset = now.startOf('month').day();

    const offsetArray = new Array(offset).fill(0);

    return offsetArray.map((_, idx) => <span key={idx}></span>);
  };

  const daysInMonthArray = new Array(now.daysInMonth()).fill(0);
  const daysInMonth = daysInMonthArray.map((_, idx) => {
    const dayNum = idx + 1;
    const isToday = dayNum === now.date();

    return (
      <span
        key={idx}
        className={`mx-auto flex aspect-square w-full max-w-8 items-center justify-center rounded-full text-sm transition-colors ${
          isToday
            ? 'bg-blue-500 font-bold text-white'
            : 'text-slate-700 hover:bg-blue-100 dark:text-slate-300 dark:hover:bg-blue-900/30'
        }`}
      >
        {dayNum}
      </span>
    );
  });

  return (
    <BentoCard className="flex flex-col">
      <div className="mb-3 flex items-center justify-between">
        <h3 className="text-lg font-semibold text-slate-800 dark:text-slate-200">
          {monthLabel}
        </h3>
        <span className="text-sm text-slate-600 dark:text-slate-400">
          {yearLabel}
        </span>
      </div>
      {/* 表头 */}
      <div className="mb-1 grid grid-cols-7 text-center">{weekdayHeaders}</div>

      {/* 日期部分 */}
      <div className="grid grid-cols-7 text-center">
        {startOffset()}
        {daysInMonth}
      </div>
    </BentoCard>
  );
}

// frontend/src/components/bento/BentoCalendar.vue
<template>
  <BentoCard class="flex flex-col">
    <div class="mb-3 flex items-center justify-between">
      <h3 class="text-lg font-semibold text-slate-800 dark:text-slate-200">
        {{ monthLabel }}
      </h3>
      <span class="text-sm text-slate-600 dark:text-slate-400">{{
        yearLabel
      }}</span>
    </div>

    <!-- Weekday headers -->
    <div
      class="mb-1 grid text-center"
      style="grid-template-columns: repeat(7, 1fr)"
    >
      <span
        v-for="(label, idx) in weekdays"
        :key="idx"
        class="py-1 text-xs font-medium"
        :class="idx === weekdayToday ? 'text-blue-500' : 'text-slate-500'"
      >
        {{ label }}
      </span>
    </div>

    <!-- Days grid -->
    <div class="grid text-center" style="grid-template-columns: repeat(7, 1fr)">
      <!-- Leading blank cells for alignment -->
      <span v-for="n in startOffset" :key="'blank-' + n" />

      <!-- Day numbers -->
      <span
        v-for="day in daysInMonth"
        :key="day"
        class="mx-auto flex aspect-square w-full max-w-8 items-center justify-center rounded-full text-sm transition-colors"
        :class="
          day === today
            ? 'bg-blue-500 font-bold text-white'
            : 'text-slate-700 hover:bg-blue-100 dark:text-slate-300 dark:hover:bg-blue-900/30'
        "
      >
        {{ day }}
      </span>
    </div>
  </BentoCard>
</template>

<script setup lang="ts">
import dayjs from "dayjs";
import { computed } from "vue";
import BentoCard from "./BentoCard.vue";

const now = dayjs();

const weekdays = ["Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"];
const weekdayToday = computed(() => dayjs().day());
const monthLabel = computed(() => now.format("MMMM"));
const yearLabel = computed(() => now.format("YYYY"));

// Day of week for the 1st of the month (0 = Sunday)
const startOffset = computed(() => now.startOf("month").day());

// Total days in current month
const daysInMonth = computed(() => now.daysInMonth());

// Current day number (1-31)
const today = computed(() => now.date());
</script>
