// frontend/src/views/pages/AboutView.vue
<script setup lang="ts">
import { computed, onMounted, ref, nextTick } from 'vue';
import { motion } from 'motion-v';
import { useTypewriter } from '@/composables/useTypewriter';

const AboutIMG = '/images/about.webp';

// Greeting typewriter
const greeting = useTypewriter();
const GREETING_TEXT = '你好；)';
const GREETING_SPEED = 200;

// Bio typewriter — each line types sequentially
const bioLines = [
  { hook: useTypewriter(), text: '我是 Kuroome。', class: 'font-bold' },
  {
    hook: useTypewriter(),
    text: '技术栈包括 Python、React、TaskIQ、FastAPI、PostgreSQL、Vue3、Redis、MongoDB 等。',
  },
  {
    hook: useTypewriter(),
    text: '技术方向包含 Web 开发、前后端、Python 数据分析等。',
  },
  {
    hook: useTypewriter(),
    text: '我的兴趣爱好广泛，涵盖编程、阅读、钓鱼等多个领域。',
  },
  {
    hook: useTypewriter(),
    text: '这个网站主要用来记录我的学习、阅读、生活点滴，希望你能喜欢！',
  },
];

const activeLineIdx = ref(-1);
const BIO_SPEED = 50;

const allBioDone = computed(
  () => bioLines.length > 0 && bioLines.every((l) => l.hook.isDone.value),
);

function typeNextLine(idx: number) {
  if (idx >= bioLines.length) return;
  activeLineIdx.value = idx;
  bioLines[idx].hook.start(bioLines[idx].text, BIO_SPEED, () =>
    setTimeout(() => typeNextLine(idx + 1), 300),
  );
}

onMounted(() => {
  nextTick();
  greeting.start(GREETING_TEXT, GREETING_SPEED, () =>
    setTimeout(() => typeNextLine(0), 500),
  );
});
</script>

<template>
  <div
    class="about-page bg-card flex min-h-screen flex-col items-center justify-center px-6 py-20"
  >
    <!-- Hero: greeting + avatar -->
    <div
      class="hero-section animate-message-pop flex flex-col items-center gap-6"
    >
      <motion.div
        :initial="{ scale: 0, opacity: 0 }"
        :animate="{ scale: 1, opacity: 1 }"
        :transition="{ type: 'spring' }"
        class="avatar-wrapper relative"
      >
        <div class="avatar-glow"></div>
        <img
          :src="AboutIMG"
          alt="Kuroome"
          class="avatar-img relative h-28 w-28 rounded-full border-[3px] border-white object-cover shadow-xl md:h-36 md:w-36"
        />
      </motion.div>

      <div class="greeting-wrapper">
        <span class="greeting-text">{{ greeting.displayed.value }}</span>
        <span v-if="!greeting.isDone.value" class="cursor-blink"></span>
      </div>
    </div>

    <!-- Divider -->
    <div class="divider my-10 w-xs"></div>

    <!-- Bio lines -->
    <div class="bio-section flex flex-col items-center gap-1 text-center">
      <div v-for="(line, i) in bioLines" :key="i" class="bio-line-wrapper">
        <span :class="line.class" class="bio-text">{{
          line.hook.displayed.value
        }}</span>
        <span
          v-if="activeLineIdx === i && !line.hook.isDone.value"
          class="cursor-blink"
        ></span>
      </div>
    </div>

    <!-- Social links -->
    <motion.div
      :initial="{ opacity: 0, y: 12 }"
      :animate="allBioDone ? { opacity: 1, y: 0 } : { opacity: 0, y: 12 }"
      :transition="{ duration: 0.6 }"
      class="social-section mt-10 flex items-center gap-5"
    >
      <span class="text-muted-foreground text-sm font-medium tracking-wide"
        >联系方式</span
      >
      <div class="bg-border h-4 w-px"></div>
      <a
        href="https://github.com/KanoCifer"
        target="_blank"
        class="social-link text-muted-foreground hover:text-foreground"
        title="GitHub"
      >
        <svg
          class="h-5 w-5"
          fill="currentColor"
          viewBox="0 0 24 24"
          aria-hidden="true"
        >
          <path
            fill-rule="evenodd"
            d="M12 2C6.477 2 2 6.484 2 12.017c0 4.425 2.865 8.18 6.839 9.504.5.092.682-.217.682-.483 0-.237-.008-.868-.013-1.703-2.782.605-3.369-1.343-3.369-1.343-.454-1.158-1.11-1.466-1.11-1.466-.908-.62.069-.608.069-.608 1.003.07 1.531 1.032 1.531 1.032.892 1.53 2.341 1.088 2.91.832.092-.647.35-1.088.636-1.338-2.22-.253-4.555-1.113-4.555-4.951 0-1.093.39-1.988 1.029-2.688-.103-.253-.446-1.272.098-2.65 0 0 .84-.27 2.75 1.026A9.564 9.564 0 0112 6.844c.85.004 1.705.115 2.504.337 1.909-1.296 2.747-1.027 2.747-1.027.546 1.379.202 2.398.1 2.651.64.7 1.028 1.595 1.028 2.688 0 3.848-2.339 4.695-4.566 4.943.359.309.678.92.678 1.855 0 1.338-.012 2.419-.012 2.747 0 .268.18.58.688.482A10.019 10.019 0 0022 12.017C22 6.484 17.522 2 12 2z"
            clip-rule="evenodd"
          />
        </svg>
      </a>
      <a
        href="mailto:kano3255@outlook.com"
        class="social-link text-muted-foreground hover:text-foreground"
        title="Email"
      >
        <svg
          class="h-5 w-5"
          fill="currentColor"
          viewBox="0 0 24 24"
          aria-hidden="true"
        >
          <path
            d="M20 4H4c-1.1 0-1.99.9-1.99 2L2 18c0 1.1.9 2 2 2h16c1.1 0 2-.9 2-2V6c0-1.1-.9-2-2-2zm0 4l-8 5-8-5V6l8 5 8-5v2z"
          />
        </svg>
      </a>
    </motion.div>
  </div>
</template>

<style scoped>
.greeting-text {
  font-size: clamp(3rem, 10vw, 6rem);
  line-height: 1;
  letter-spacing: 0.08em;
  color: var(--color-foreground);
}

.bio-text {
  font-size: 1.05rem;
  line-height: 1.8;
  color: var(--color-muted-foreground);
}

.bio-line-wrapper {
  display: inline;
}

.greeting-wrapper {
  display: flex;
  align-items: baseline;
  justify-content: center;
  min-height: 1.2em;
}

.cursor-blink {
  display: inline-block;
  width: 2px;
  height: 1em;
  margin-left: 2px;
  background-color: var(--color-primary);
  vertical-align: text-bottom;
  animation: blink 1s step-end infinite;
}

@keyframes blink {
  0%,
  100% {
    opacity: 1;
  }
  50% {
    opacity: 0;
  }
}

.divider {
  height: 2px;
  background: linear-gradient(
    90deg,
    transparent,
    var(--color-border) 30%,
    var(--color-border) 70%,
    transparent
  );
}

.avatar-glow {
  position: absolute;
  inset: -4px;
  border-radius: 9999px;
  background: linear-gradient(
    135deg,
    var(--color-primary),
    var(--color-accent)
  );
  opacity: 0.25;
  filter: blur(14px);
  transition: opacity 0.5s ease;
}

.avatar-wrapper:hover .avatar-glow {
  opacity: 0.45;
}

.social-link {
  transition:
    transform 0.2s ease,
    color 0.2s ease;
}

.social-link:hover {
  transform: scale(1.15);
}
</style>

// react-app/src/views/general/AboutView.tsx
import { motion } from 'framer-motion';
import { Mail } from 'lucide-react';
import { BentoCard } from '@/components/bento/BentoCard';
import { BentoSocial } from '@/components/bento/BentoSocial';

const AboutIMG = '/images/about.webp';

const techStack = [
  'Python',
  'JS/TS',
  'TaskIQ',
  'FastApi',
  'HTML/CSS/TailwindCSS',
  'PostgreSQL',
  'Vue3',
  'Redis',
  'MongoDB',
];

const techDirections = ['Web 开发', '前后端', 'Python数据分析'];

const hobbies = ['编程、阅读、钓鱼'];

export default function AboutView() {
  return (
    <div className="mx-auto my-auto flex max-w-6xl flex-col items-center justify-center px-4 py-8">
      <motion.div
        initial={{ opacity: 0, y: 20 }}
        animate={{ opacity: 1, y: 0 }}
        whileHover={{ scale: 1.01 }}
        transition={{ duration: 0.3 }}
        className="mx-auto mt-20 flex w-full max-w-6xl flex-col items-center justify-center"
      >
        <BentoCard className="w-full p-6 md:p-12">
          <div className="flex flex-col items-center gap-6 md:flex-row md:items-center md:gap-12">
            <div className="group relative shrink-0">
              <div className="absolute -inset-1 rounded-full bg-linear-to-br from-pink-200 to-blue-200 opacity-50 blur transition duration-500 group-hover:opacity-75 dark:from-pink-400/30 dark:to-blue-400/30" />
              <img
                src={AboutIMG}
                alt="Kuroome"
                className="relative h-32 w-32 transform rounded-full border-4 border-white object-cover shadow-xl transition duration-500 group-hover:scale-105 md:h-48 md:w-48 dark:border-gray-800"
              />
            </div>

            <div className="hidden h-48 w-px bg-stone-600/80 dark:bg-stone-100/80 md:block" />

            <div className="flex-1 space-y-5 text-center md:text-left">
              <div className="space-y-4 text-base leading-relaxed text-gray-600 md:text-lg dark:text-gray-300">
                <p>
                  <span className="text-xl font-bold md:text-2xl">
                    我是 Kuroome。
                  </span>
                  <span className="block pt-1">
                    你好！欢迎来到我的博客。很多内容正在建设中...
                  </span>
                </p>
                <p>这个网站是我的第一个web项目。</p>

                <p className="flex flex-wrap items-center justify-center gap-x-2 gap-y-1 md:justify-start">
                  <span className="shrink-0">主要技术栈包括</span>
                  {techStack.map((tech, i) => (
                    <span
                      key={tech}
                      className="cursor-default font-medium text-gray-800 underline decoration-blue-400/60 decoration-2 underline-offset-2 transition-colors hover:decoration-pink-400 dark:text-gray-100"
                    >
                      {tech}
                      {i < techStack.length - 1 && '、'}
                    </span>
                  ))}
                  <span className="shrink-0">等。</span>
                </p>

                <p className="flex flex-wrap items-center justify-center gap-x-2 gap-y-1 md:justify-start">
                  <span className="shrink-0">技术方向包含</span>
                  {techDirections.map((dir, i) => (
                    <span
                      key={dir}
                      className="cursor-default font-medium text-gray-800 underline decoration-blue-400/60 decoration-2 underline-offset-2 transition-colors hover:decoration-pink-400 dark:text-gray-100"
                    >
                      {dir}
                      {i < techDirections.length - 1 && '、'}
                    </span>
                  ))}
                  <span className="shrink-0">等。</span>
                </p>

                <p>
                  我的兴趣爱好广泛，涵盖
                  <span className="cursor-default font-medium text-gray-800 underline decoration-blue-400/60 decoration-2 underline-offset-2 transition-colors hover:decoration-pink-400 dark:text-gray-100">
                    {hobbies}
                  </span>
                  等多个领域。
                </p>

                <p className="text-sm md:text-base">
                  这个博客主要用来记录我的学习、读书、生活点滴，希望你能喜欢！如果你有任何建议或想法，欢迎通过下面的联系方式与我交流。
                </p>
              </div>

              <div className="flex items-center justify-center gap-5 pt-3 md:justify-start">
                <span className="text-sm font-medium text-gray-400">
                  联系方式：
                </span>

                <a
                  href="https://github.com/KanoCifer"
                  target="_blank"
                  rel="noopener noreferrer"
                  className="flex h-12 w-12 items-center justify-center rounded-full bg-white/60 text-gray-400 shadow-sm transition-all duration-300 hover:-translate-y-1 hover:bg-orange-50 hover:text-orange-600 hover:shadow-md dark:bg-slate-700 dark:text-gray-400 dark:hover:text-white"
                  title="GitHub"
                  aria-label="GitHub"
                >
                  <svg
                    className="h-6 w-6"
                    fill="currentColor"
                    viewBox="0 0 24 24"
                    aria-hidden="true"
                  >
                    <path
                      fillRule="evenodd"
                      clipRule="evenodd"
                      d="M12 2C6.477 2 2 6.477 2 12c0 4.42 2.865 8.166 6.839 9.489.5.092.682-.217.682-.482 0-.237-.008-.866-.013-1.699-2.782.603-3.369-1.34-3.369-1.34-.454-1.156-1.11-1.463-1.11-1.463-.908-.62.069-.608.069-.608 1.003.07 1.531 1.03 1.531 1.03.892 1.529 2.341 1.087 2.91.831.092-.646.35-1.086.636-1.336-2.22-.253-4.555-1.11-4.555-4.943 0-1.091.39-1.984 1.029-2.683-.103-.253-.446-1.27.098-2.647 0 0 .84-.269 2.75 1.025A9.564 9.564 0 0112 6.844c.85.004 1.705.115 2.504.337 1.909-1.294 2.747-1.025 2.747-1.025.546 1.379.203 2.394.1 2.647.64.699 1.028 1.592 1.028 2.683 0 3.842-2.339 4.687-4.566 4.935.359.309.678.919.678 1.852 0 1.336-.012 2.415-.012 2.743 0 .267.18.578.688.48C19.138 20.161 22 16.416 22 12c0-5.523-4.477-10-10-10z"
                    />
                  </svg>
                </a>

                <a
                  href="mailto:kano3255@outlook.com"
                  className="flex h-12 w-12 items-center justify-center rounded-full bg-white/60 text-gray-400 shadow-sm transition-all duration-300 hover:-translate-y-1 hover:bg-orange-50 hover:text-orange-600 hover:shadow-md dark:bg-slate-700 dark:text-gray-400 dark:hover:text-white"
                  title="Email"
                  aria-label="Email"
                >
                  <Mail className="h-6 w-6" />
                </a>
              </div>
            </div>
          </div>
        </BentoCard>

        <motion.div
          initial={{ scale: 0 }}
          animate={{ scale: 1 }}
          transition={{ delay: 0.2, duration: 0.4 }}
          className="mt-4 w-full max-w-sm"
        >
          <BentoSocial />
        </motion.div>
      </motion.div>
    </div>
  );
}
