// react-app/src/views/BookShelf/BookShelf.tsx
import type { WereadUserBook } from '@/api/wereadGateway';
import {
  useReadStatsStore,
  selectWeeklySnapshot,
} from '@/stores/readStatsStore';
import { wereadService } from '@/services/wereadService';
import { ArrowLeft, ExternalLink, RefreshCw } from 'lucide-react';
import { useCallback, useEffect, useState } from 'react';
import { useNavigate } from 'react-router-dom';

function formatDuration(seconds: number | null): string {
  if (!seconds || seconds <= 0) return '0';
  const h = Math.floor(seconds / 3600);
  const m = Math.floor((seconds % 3600) / 60);
  if (h > 0) return `${h}h ${m}m`;
  return `${m}m`;
}

export default function BookShelf() {
  const navigate = useNavigate();
  const [books, setBooks] = useState<WereadUserBook[]>([]);
  const [isLoading, setIsLoading] = useState(true);
  const [isSyncing, setIsSyncing] = useState(false);
  const [errorMessage, setErrorMessage] = useState('');

  const statsStore = useReadStatsStore();
  const weeklySnapshot = useReadStatsStore(selectWeeklySnapshot);

  const latestBook = weeklySnapshot?.readLongest?.[0] ?? null;

  const visibleBooks = books.filter((b) => !b.secret);

  const fetchBooks = useCallback(async () => {
    setIsLoading(true);
    setErrorMessage('');
    try {
      const res = await wereadService.getUserShelf();
      if (res.status === 'success' && res.data) {
        setBooks(res.data.user_books);
      } else {
        throw new Error(res.message || '获取书架失败');
      }
    } catch (err: unknown) {
      const error = err as {
        response?: { data?: { message?: string } };
        message?: string;
      };
      setErrorMessage(
        error?.response?.data?.message || error?.message || '获取书架失败',
      );
    } finally {
      setIsLoading(false);
    }
  }, []);

  const handleSync = useCallback(async () => {
    setIsSyncing(true);
    try {
      const res = await wereadService.syncMyBooks();
      if (res.status === 'success') {
        await fetchBooks();
      } else {
        throw new Error(res.message || '同步失败');
      }
    } catch (err: unknown) {
      const error = err as {
        response?: { data?: { message?: string } };
        message?: string;
      };
      setErrorMessage(
        error?.response?.data?.message || error?.message || '同步失败',
      );
    } finally {
      setIsSyncing(false);
    }
  }, [fetchBooks]);

  const handleBack = useCallback(() => {
    if (window.history.length > 1) {
      navigate(-1);
    } else {
      navigate('/');
    }
  }, [navigate]);

  const handleBookClick = useCallback((bookId: string) => {
    const link = document.createElement('a');
    link.href = `weread://reading?bId=${bookId}`;
    link.click();
  }, []);

  useEffect(() => {
    Promise.all([fetchBooks(), statsStore.fetchStats()]);
  }, [fetchBooks, statsStore]);

  return (
    <div className="bg-background flex min-h-[calc(100dvh-4rem)] flex-col">
      {/* Hero Image Section */}
      <div className="relative h-[40vh] flex-shrink-0 overflow-hidden md:h-[45vh]">
        <img
          src="/card/card-1.jpeg"
          alt=""
          className="h-full w-full object-cover"
        />
        <div className="from-background/40 via-background/5 to-background pointer-events-none absolute inset-0 bg-gradient-to-b" />

        {/* Back Button */}
        <div className="absolute top-0 right-0 left-0 z-10 flex items-center px-4 py-4 md:px-6">
          <button
            type="button"
            className="border-border bg-card/60 hover:bg-accent flex h-10 w-10 items-center justify-center rounded-full border backdrop-blur-md transition-colors"
            onClick={handleBack}
            aria-label="返回"
          >
            <ArrowLeft className="text-foreground h-5 w-5" />
          </button>
        </div>

        {/* Sync Button */}
        <div className="absolute top-0 right-0 z-10 flex items-center px-4 py-4 md:px-6">
          <button
            type="button"
            className="border-border bg-card/60 hover:bg-accent flex h-10 w-10 items-center justify-center rounded-full border backdrop-blur-md transition-colors disabled:opacity-50"
            disabled={isSyncing}
            onClick={handleSync}
            aria-label="同步书架"
          >
            <RefreshCw
              className={`text-foreground h-5 w-5 ${isSyncing ? 'animate-spin' : ''}`}
            />
          </button>
        </div>

        {/* Title Overlay */}
        <div className="absolute right-0 bottom-0 left-0 z-10 px-6 pb-6 md:px-10 md:pb-8">
          <h1 className="font-serif text-3xl font-bold text-white drop-shadow-lg md:text-5xl">
            我的书架
          </h1>
          <div className="mt-2 flex items-center gap-3">
            <span className="text-sm text-white/75 md:text-base">微信读书</span>
            <span className="h-1 w-1 rounded-full bg-white/40" />
            {!isLoading && (
              <span className="text-sm text-white/75 md:text-base">
                {visibleBooks.length} 本书
              </span>
            )}
          </div>
        </div>
      </div>

      {/* Stats Summary Bar */}
      {weeklySnapshot && (
        <div
          className="border-border bg-card mx-auto mt-6 mb-4 w-[calc(100%-2rem)] max-w-6xl cursor-pointer rounded-2xl border p-4 shadow-sm transition-shadow hover:shadow-md sm:px-6 md:mt-8 md:mb-6 md:px-10"
          onClick={() => navigate('/bookshelf/stats')}
        >
          <div className="flex items-center gap-4 sm:gap-6">
            <div className="flex-1">
              <p className="text-muted-foreground mb-1 text-xs">本周阅读</p>
              <p className="text-foreground text-xl font-bold">
                {formatDuration(weeklySnapshot.totalReadTime)}
              </p>
            </div>
            <div className="bg-border h-10 w-px" />
            <div className="flex-1">
              <p className="text-muted-foreground mb-1 text-xs">阅读天数</p>
              <p className="text-foreground text-xl font-bold">
                {weeklySnapshot.readDays ?? 0}
                <span className="text-muted-foreground text-xs font-normal">
                  天
                </span>
              </p>
            </div>
            <div className="bg-border hidden h-10 w-px sm:block" />
            {latestBook && (
              <div className="hidden min-w-0 flex-1 items-center gap-3 sm:flex">
                {latestBook.cover && (
                  <img
                    src={latestBook.cover}
                    alt={latestBook.title ?? ''}
                    className="h-12 w-9 flex-shrink-0 rounded object-cover shadow-sm"
                  />
                )}
                <div className="min-w-0">
                  <p className="text-muted-foreground mb-0.5 text-xs">
                    最近在读
                  </p>
                  <p className="text-foreground truncate text-sm font-medium">
                    {latestBook.title}
                  </p>
                </div>
              </div>
            )}
            <svg
              xmlns="http://www.w3.org/2000/svg"
              fill="none"
              viewBox="0 0 24 24"
              strokeWidth="2"
              stroke="currentColor"
              className="text-muted-foreground h-5 w-5 flex-shrink-0"
            >
              <path
                strokeLinecap="round"
                strokeLinejoin="round"
                d="M8.25 4.5l7.5 7.5-7.5 7.5"
              />
            </svg>
          </div>
        </div>
      )}

      {/* Books Section */}
      <div className="flex-1 pb-8">
        <div className="mx-auto max-w-6xl px-4 py-8 sm:px-6 md:px-10">
          {/* Loading skeleton */}
          {isLoading && (
            <div className="grid grid-cols-2 gap-4 sm:grid-cols-3 md:grid-cols-4 lg:grid-cols-5 xl:grid-cols-6">
              {Array.from({ length: 8 }).map((_, i) => (
                <div key={i} className="animate-pulse">
                  <div className="bg-muted aspect-3/4 rounded-xl" />
                  <div className="mt-2 space-y-1.5 px-1.5">
                    <div className="bg-muted h-3 w-5/6 rounded" />
                    <div className="bg-muted h-3 w-3/4 rounded" />
                    <div className="bg-muted h-2.5 w-1/2 rounded" />
                  </div>
                </div>
              ))}
            </div>
          )}

          {/* Error state */}
          {!isLoading && errorMessage && (
            <div className="flex flex-col items-center justify-center py-20">
              <p className="text-destructive mb-4 text-center text-sm">
                {errorMessage}
              </p>
              <button
                type="button"
                className="bg-destructive/10 text-destructive hover:bg-destructive/20 rounded-xl px-5 py-2 text-sm font-medium transition-colors"
                onClick={fetchBooks}
              >
                重试
              </button>
            </div>
          )}

          {/* Empty state */}
          {!isLoading && !errorMessage && visibleBooks.length === 0 && (
            <div className="flex flex-col items-center justify-center py-20">
              <p className="text-muted-foreground font-medium">暂无书籍</p>
              <p className="text-muted-foreground/60 mt-1 text-sm">
                你的微信读书书架还是空的
              </p>
            </div>
          )}

          {/* Books grid */}
          {!isLoading && !errorMessage && visibleBooks.length > 0 && (
            <div className="grid grid-cols-2 gap-4 sm:grid-cols-3 md:grid-cols-4 lg:grid-cols-5 xl:grid-cols-6">
              {visibleBooks.map((book, index) => (
                <a
                  key={book.bookId}
                  href={`weread://reading?bId=${book.bookId}`}
                  className="group block"
                  onClick={(e) => {
                    e.preventDefault();
                    handleBookClick(book.bookId);
                  }}
                >
                  <div
                    className="bg-card hover:shadow-primary/5 relative overflow-hidden rounded-xl shadow-sm transition-all duration-300 hover:-translate-y-1 hover:shadow-lg"
                    style={{ animationDelay: `${index * 30}ms` }}
                  >
                    <div className="relative aspect-3/4 overflow-hidden">
                      {book.cover ? (
                        <img
                          src={book.cover}
                          alt={book.title}
                          className="h-full w-full object-cover transition-transform duration-300 group-hover:scale-[1.03]"
                          loading="lazy"
                          onError={(e) => {
                            (e.target as HTMLImageElement).style.display =
                              'none';
                          }}
                        />
                      ) : (
                        <div className="bg-muted flex h-full w-full items-center justify-center">
                          <span className="text-muted-foreground/40 font-serif text-2xl">
                            {book.title.slice(0, 1)}
                          </span>
                        </div>
                      )}

                      {/* Hover overlay with open icon */}
                      <div className="absolute inset-0 flex items-center justify-center bg-black/0 transition-colors duration-300 group-hover:bg-black/30">
                        <div className="bg-background/90 text-foreground flex h-10 w-10 items-center justify-center rounded-full opacity-0 shadow-lg backdrop-blur-sm transition-all duration-300 group-hover:opacity-100">
                          <ExternalLink className="h-5 w-5" />
                        </div>
                      </div>

                      {book.finishReading && (
                        <div className="bg-success/90 absolute top-2 right-2 rounded-full px-2 py-0.5 text-[10px] font-medium text-white">
                          已读
                        </div>
                      )}
                    </div>
                    <div className="px-1.5 py-2">
                      <p
                        className="text-foreground line-clamp-2 text-xs font-medium leading-snug"
                        title={book.title}
                      >
                        {book.title}
                      </p>
                      <p
                        className="text-muted-foreground mt-1 truncate text-[11px] leading-snug"
                        title={book.author}
                      >
                        {book.author}
                      </p>
                    </div>
                  </div>
                </a>
              ))}
            </div>
          )}
        </div>
      </div>
    </div>
  );
}

// frontend/src/views/BookShelf.vue
<template>
  <div
    class="mx-auto mb-24 min-h-screen max-w-5xl rounded-4xl bg-gray-50/70 px-4 py-8 backdrop-blur-lg sm:px-6 lg:px-8 dark:bg-gray-900/50"
  >
    <div class="mx-auto">
      <!-- 页面标题 -->
      <div class="mb-8 flex items-center gap-3">
        <div
          class="flex h-12 w-12 items-center justify-center rounded-xl bg-blue-100 text-blue-600 dark:bg-blue-900/30 dark:text-blue-400"
        >
          <svg
            xmlns="http://www.w3.org/2000/svg"
            fill="none"
            viewBox="0 0 24 24"
            stroke-width="2"
            stroke="currentColor"
            class="h-7 w-7"
          >
            <path
              stroke-linecap="round"
              stroke-linejoin="round"
              d="M12 6.042A8.967 8.967 0 006 3.75c-1.052 0-2.062.18-3 .512v14.25A8.987 8.987 0 016 18c2.305 0 4.408.867 6 2.292m0-14.25a8.966 8.966 0 016-2.292c1.052 0 2.062.18 3 .512v14.25A8.987 8.987 0 0018 18a8.987 8.987 0 00-6 2.292m0-14.25v14.25"
            />
          </svg>
        </div>
        <div>
          <div class="flex items-center gap-6">
            <h1 class="font-serif text-3xl font-bold text-gray-900 dark:text-white">我的书架</h1>
            <span
              class="self-center rounded-full border border-blue-300 bg-blue-200/60 px-4 py-2 text-xs text-blue-500 dark:bg-blue-200 dark:text-blue-900"
              >{{ books_count }}</span
            >
          </div>
          <p class="mt-1 text-sm text-gray-500 dark:text-gray-400">管理您的阅读收藏</p>
        </div>
      </div>

      <!-- 加载状态 - 骨架屏 -->
      <div
        v-if="isLoading"
        class="grid grid-cols-1 gap-6 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4"
      >
        <div
          v-for="i in 6"
          :key="i"
          class="animate-pulse overflow-hidden rounded-xl bg-white shadow-sm dark:bg-gray-800"
        >
          <div class="aspect-2/3 bg-gray-200 dark:bg-gray-700" />
          <div class="p-4">
            <div class="mb-2 h-5 w-3/4 rounded bg-gray-200 dark:bg-gray-700" />
            <div class="h-4 w-1/2 rounded bg-gray-200 dark:bg-gray-700" />
          </div>
        </div>
      </div>

      <!-- 错误状态 -->
      <div
        v-else-if="errorMessage"
        class="flex flex-col items-center justify-center rounded-2xl bg-white py-16 shadow-sm dark:bg-gray-800"
      >
        <div
          class="mb-4 flex h-16 w-16 items-center justify-center rounded-full bg-red-100 text-red-600 dark:bg-red-900/30 dark:text-red-400"
        >
          <svg
            xmlns="http://www.w3.org/2000/svg"
            fill="none"
            viewBox="0 0 24 24"
            stroke-width="2"
            stroke="currentColor"
            class="h-8 w-8"
          >
            <path
              stroke-linecap="round"
              stroke-linejoin="round"
              d="M12 9v3.75m-9.303 3.376c-.866 1.5.217 3.374 1.948 3.374h14.71c1.73 0 2.813-1.874 1.948-3.374L13.949 3.378c-.866-1.5-3.032-1.5-3.898 0L2.697 16.126zM12 15.75h.007v.008H12v-.008z"
            />
          </svg>
        </div>
        <p class="mb-4 text-center text-red-600 dark:text-red-400">
          {{ errorMessage }}
        </p>
        <button
          type="button"
          class="inline-flex items-center gap-2 rounded-xl bg-red-600 px-6 py-2.5 font-semibold text-white shadow-lg shadow-red-500/30 transition-colors hover:bg-red-700 focus:ring-2 focus:ring-red-500 focus:ring-offset-2 focus:outline-none dark:ring-offset-gray-800"
          @click="() => fetchBooks()"
        >
          <svg
            xmlns="http://www.w3.org/2000/svg"
            fill="none"
            viewBox="0 0 24 24"
            stroke-width="2"
            stroke="currentColor"
            class="h-5 w-5"
          >
            <path
              stroke-linecap="round"
              stroke-linejoin="round"
              d="M16.023 9.348h4.992v-.001M2.985 19.644v-4.992m0 0h4.992m-4.993 0l3.181 3.183a8.25 8.25 0 0013.803-3.7M4.731 4.002l.129-.143a8.25 8.25 0 0113.803 3.7M4.731 4.002l3.181-3.182"
            />
          </svg>
          重试
        </button>
      </div>

      <!-- 空状态 -->
      <div
        v-else-if="books.length === 0"
        class="flex flex-col items-center justify-center rounded-2xl bg-white py-16 shadow-sm dark:bg-gray-800"
      >
        <div
          class="mb-4 flex h-20 w-20 items-center justify-center rounded-full bg-gray-100 text-gray-400 dark:bg-gray-700 dark:text-gray-500"
        >
          <svg
            xmlns="http://www.w3.org/2000/svg"
            fill="none"
            viewBox="0 0 24 24"
            stroke-width="1.5"
            stroke="currentColor"
            class="h-10 w-10"
          >
            <path
              stroke-linecap="round"
              stroke-linejoin="round"
              d="M12 6.042A8.967 8.967 0 006 3.75c-1.052 0-2.062.18-3 .512v14.25A8.987 8.987 0 016 18c2.305 0 4.408.867 6 2.292m0-14.25a8.966 8.966 0 016-2.292c1.052 0 2.062.18 3 .512v14.25A8.987 8.987 0 0018 18a8.987 8.987 0 00-6 2.292m0-14.25v14.25"
            />
          </svg>
        </div>
        <h3 class="mb-2 font-serif text-xl font-semibold text-gray-900 dark:text-white">
          暂无书籍
        </h3>
        <p class="mb-6 text-center text-gray-500 dark:text-gray-400">
          您的书架还是空的，快去导入一些书籍吧
        </p>
        <router-link
          to="/import"
          class="inline-flex items-center gap-2 rounded-xl bg-blue-600 px-6 py-2.5 font-semibold text-white shadow-lg shadow-blue-500/30 transition-colors hover:bg-blue-700 focus:ring-2 focus:ring-blue-500 focus:ring-offset-2 focus:outline-none dark:ring-offset-gray-800"
        >
          <svg
            xmlns="http://www.w3.org/2000/svg"
            fill="none"
            viewBox="0 0 24 24"
            stroke-width="2"
            stroke="currentColor"
            class="h-5 w-5"
          >
            <path
              stroke-linecap="round"
              stroke-linejoin="round"
              d="M3 16.5v2.25A2.25 2.25 0 005.25 21h13.5A2.25 2.25 0 0021 18.75V16.5m-13.5-9L12 3m0 0l4.5 4.5M12 3v13.5"
            />
          </svg>
          导入书籍
        </router-link>
      </div>

      <!-- 书籍 Grid -->
      <transition
        enter-active-class="transition-all transition-gpu duration-500 ease-out"
        enter-from-class="opacity-0 translate-y-4 scale-95"
        enter-to-class="opacity-100 translate-y-0 scale-100"
      >
        <div
          v-if="!isLoading && !errorMessage && books.length > 0"
          class="book-grid-animation grid grid-cols-1 gap-6 sm:grid-cols-2 lg:grid-cols-4"
        >
          <BookCard v-for="book in books" :key="book.id" :book="book" />
        </div>
      </transition>
      <!-- 分页 -->
      <div v-if="pagination && pagination.pages > 1" class="mt-8 flex justify-center">
        <nav class="flex items-center gap-2">
          <!-- 上一页 -->
          <button
            :disabled="!pagination.has_prev"
            class="rounded-lg px-3 py-2 text-sm font-medium transition-colors hover:bg-gray-100 disabled:cursor-not-allowed disabled:opacity-50 dark:hover:bg-gray-800"
            :class="pagination?.has_prev ? 'text-gray-700 dark:text-gray-300' : 'text-gray-400'"
            @click="goToPage(pagination!.prev_num!)"
            type="button"
          >
            上一页
          </button>

          <!-- 页码 -->
          <div class="flex items-center gap-1">
            <!-- 显示第一页 -->
            <button
              v-if="pagination && pagination.page > 3"
              class="min-w-32px rounded-lg px-2 py-2 text-sm font-medium text-gray-700 hover:bg-gray-100 dark:text-gray-300 dark:hover:bg-gray-800"
              @click="goToPage(1)"
              type="button"
            >
              1
            </button>

            <!-- 省略号 -->
            <span
              v-if="pagination && pagination.page > 4"
              class="px-1 text-gray-500 dark:text-gray-400"
              >...</span
            >

            <!-- 显示当前页附近的页码 -->
            <button
              v-for="pageNum in getVisiblePages"
              :key="pageNum"
              class="min-w-32px rounded-lg px-2 py-2 text-sm font-medium transition-colors"
              :class="
                pageNum === pagination?.page
                  ? 'bg-blue-600 text-white'
                  : 'text-gray-700 hover:bg-gray-100 dark:text-gray-300 dark:hover:bg-gray-800'
              "
              @click="goToPage(pageNum)"
              type="button"
            >
              {{ pageNum }}
            </button>

            <!-- 省略号 -->
            <span
              v-if="pagination && pagination.page < pagination.pages - 3"
              class="px-1 text-gray-500 dark:text-gray-400"
              >...</span
            >

            <!-- 显示最后一页 -->
            <button
              v-if="pagination && pagination.page < pagination.pages - 2"
              class="min-w-32px rounded-lg px-2 py-2 text-sm font-medium text-gray-700 hover:bg-gray-100 dark:text-gray-300 dark:hover:bg-gray-800"
              @click="goToPage(pagination.pages)"
              type="button"
            >
              {{ pagination.pages }}
            </button>
          </div>

          <!-- 下一页 -->
          <button
            :disabled="!pagination?.has_next"
            class="rounded-lg px-3 py-2 text-sm font-medium transition-colors hover:bg-gray-100 disabled:cursor-not-allowed disabled:opacity-50 dark:hover:bg-gray-800"
            :class="pagination?.has_next ? 'text-gray-700 dark:text-gray-300' : 'text-gray-400'"
            @click="goToPage(pagination!.next_num!)"
            type="button"
          >
            下一页
          </button>
        </nav>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import BookCard from "@/components/BookCard.vue";
import request from "@/request";
import type { BookItem, BookListResponse, Pagination } from "@/types";
import { computed, ref } from "vue";
import { RouterLink } from "vue-router";

// 响应式状态
const books = ref<BookItem[]>([]);
const isLoading = ref(false);
const errorMessage = ref("");
const pagination = ref<Pagination | null>(null);
const currentPage = ref(1);
const books_count = ref(0);

// 获取可见页码范围
const getVisiblePages = computed(() => {
  if (!pagination.value) return [];

  const totalPages = pagination.value.pages;
  const current = pagination.value.page;
  const visiblePages = [];

  // 显示当前页附近的页码
  for (let i = Math.max(2, current - 2); i <= Math.min(totalPages - 1, current + 2); i++) {
    visiblePages.push(i);
  }

  return visiblePages;
});

// 数据获取
const fetchBooks = async (page: number = 1) => {
  isLoading.value = true;
  errorMessage.value = "";
  try {
    const res = await request.get<BookListResponse>("/book", {
      params: { page, per_page: 12 },
    });
    if (res.data.status === "success") {
      books.value = res.data.data?.books || [];
      //
      books_count.value = res.data.data?.pagination?.total || 0;
      pagination.value = res.data.data?.pagination || null;
      currentPage.value = page;
    } else {
      throw new Error(res.data.message || "获取书籍列表失败");
    }
  } catch (err: unknown) {
    const error = err as {
      response?: { data?: { message?: string } };
      message?: string;
    };
    errorMessage.value = error?.response?.data?.message || error?.message || "获取书籍列表失败";
  } finally {
    isLoading.value = false;
  }
};

// 分页导航
const goToPage = (page: number) => {
  if (page >= 1 && pagination.value && page <= pagination.value.pages) {
    fetchBooks(page);
  }
};

// 初始化
fetchBooks();
</script>

<style scoped>
.book-grid-animation :deep(.book-card-wrapper) {
  animation-delay: calc(var(--index) * 0.1s);
}

/* 为每个书籍卡片添加动画延迟 */
.book-grid-animation > *:nth-child(1) {
  --index: 1;
}
.book-grid-animation > *:nth-child(2) {
  --index: 2;
}
.book-grid-animation > *:nth-child(3) {
  --index: 3;
}
.book-grid-animation > *:nth-child(4) {
  --index: 4;
}
.book-grid-animation > *:nth-child(5) {
  --index: 5;
}
.book-grid-animation > *:nth-child(6) {
  --index: 6;
}
.book-grid-animation > *:nth-child(7) {
  --index: 7;
}
.book-grid-animation > *:nth-child(8) {
  --index: 8;
}
.book-grid-animation > *:nth-child(9) {
  --index: 9;
}
.book-grid-animation > *:nth-child(10) {
  --index: 10;
}
.book-grid-animation > *:nth-child(11) {
  --index: 11;
}
.book-grid-animation > *:nth-child(12) {
  --index: 12;
}
</style>
