// frontend/src/views/blog/BlogPostView.vue
<script setup lang="ts">
import { BasicDetail } from '@/components/basic';
import ArticleSummaryCard from '@/components/blog/ArticleSummaryCard.vue';
import TwikooComments from '@/components/blog/TwikooComments.vue';
import {
  AlertDialog,
  AlertDialogAction,
  AlertDialogCancel,
  AlertDialogContent,
  AlertDialogDescription,
  AlertDialogFooter,
  AlertDialogHeader,
  AlertDialogTitle,
} from '@/components/ui/alert-dialog';
import CalendarIcon from '@/components/icons/CalendarIcon.vue';
import DelIcon from '@/components/icons/DelIcon.vue';
import EditIcon from '@/components/icons/EditIcon.vue';
import { blogGateway } from '@/api/public';
import { useAuthStore } from '@/auth/stores/auth';
import { useOrigin } from '@/composables/shared';
import { useNotificationStore } from '@/stores/notification';
import type { Post } from '@/types';
import { formatDate } from '@/utils/formatdate';
import { useHead } from '@vueuse/head';
import hljs from 'highlight.js/lib/common';
import 'highlight.js/scss/rainbow.scss';
import { marked } from 'marked';
import { computed, nextTick, onMounted, onUnmounted, ref, watch } from 'vue';
import { useRoute, useRouter } from 'vue-router';

const route = useRoute();
const router = useRouter();
const postId = ref<string>(route.params.id as string);

const post = ref<Post | null>(null);
const isLoading = ref(false);
const errorMessage = ref('');

const auth = useAuthStore();
const showEditButton = computed(() => !!auth.user?.is_admin);

const fetchPost = async () => {
  if (!postId.value) {
    errorMessage.value = '无效的文章 ID';
    return;
  }

  isLoading.value = true;
  errorMessage.value = '';

  try {
    const res = await blogGateway.getLegacyPost(postId.value);
    post.value = res as unknown as Post;
  } catch (err: unknown) {
    console.error(err);
    errorMessage.value =
      err instanceof Error ? err.message : '加载文章失败，请稍后重试。';
    useNotificationStore().error(errorMessage.value);
  } finally {
    isLoading.value = false;
  }
};

const handleRetry = () => {
  fetchPost();
};

onMounted(() => {
  fetchPost();
});

watch(
  () => route.params.id,
  (newId): void => {
    if (newId && newId !== postId.value) {
      postId.value = newId as string;
      fetchPost();
    }
  },
);

watch(
  () => post.value?.body,
  async (html): Promise<void> => {
    if (!html) return;
    await nextTick();
    hljs.highlightAll();
    setupCodeCopy();
  },
);

const renderedBody = computed(() => {
  if (!post.value?.body) return '';
  return marked.parse(post.value.body, {
    async: false,
    breaks: false,
  }) as string;
});

// 非 http(s) 开头的 src 用 https://api.kanocifer.chat 作为前缀（仅在 https 环境下生效）
const coverSrc = computed(() =>
  post.value?.cover ? useOrigin(post.value.cover) : '',
);

// 渲染正文中所有 <img src="...">，非 http(s) 开头的补上前缀
const renderedBodyWithOrigin = computed(() => {
  if (!renderedBody.value) return '';
  return renderedBody.value.replace(
    /<img\s+([^>]*?)src=["']([^"']+)["']([^>]*)>/gi,
    (match, pre, src, post) => {
      const fixed = useOrigin(src);
      return `<img ${pre}src="${fixed}"${post}>`;
    },
  );
});

const subtitle = computed(() => {
  if (!post.value) return '';
  const { author, created_at, category } = post.value;
  return [author, created_at && formatDate(created_at), category?.name]
    .filter(Boolean)
    .join(' · ');
});

useHead(() => {
  const title = post.value
    ? `${post.value.title} - ReadingList`
    : '文章未找到 - ReadingList';
  const desc = post.value
    ? post.value.summary || `阅读 ${post.value.title} 的完整内容`
    : '抱歉，您请求的文章不存在或已被删除';
  const keywords = post.value
    ? [
        post.value.title,
        post.value.author || 'Kurroome',
        post.value.category?.name || '博客',
        '阅读',
        '读书笔记',
        '个人博客',
      ]
        .filter(Boolean)
        .join(', ')
    : '文章未找到, 阅读清单, ReadingList';

  const imageMeta = post.value?.cover
    ? [
        { property: 'og:image', content: post.value.cover },
        { name: 'twitter:image', content: post.value.cover },
      ]
    : [];

  return {
    title,
    meta: [
      { name: 'description', content: desc },
      { name: 'keywords', content: keywords },
      { property: 'og:title', content: post.value?.title ?? '文章未找到' },
      { property: 'og:description', content: desc },
      { property: 'og:type', content: 'article' },
      {
        property: 'og:url',
        content: `https://readinglist.example.com/blog/${postId.value}`,
      },
      {
        property: 'og:article:author',
        content: post.value?.author || 'Kurroome',
      },
      {
        property: 'og:article:published_time',
        content: post.value?.created_at,
      },
      { property: 'og:article:modified_time', content: post.value?.updated_at },
      {
        property: 'og:article:section',
        content: post.value?.category?.name || '博客',
      },
      { name: 'twitter:title', content: post.value?.title ?? '文章未找到' },
      { name: 'twitter:description', content: desc },
      ...imageMeta,
    ],
  };
});

const showDeleteDialog = ref(false);

const confirmDelete = async () => {
  showDeleteDialog.value = false;
  await handleDelete();
};

const handleDelete = async () => {
  try {
    await blogGateway.deleteLegacyPost(postId.value);
    useNotificationStore().success('文章删除成功');
    router.push('/blog');
  } catch (err: unknown) {
    console.error('删除文章失败:', err);
    const errorMsg =
      err instanceof Error ? err.message : '删除文章失败，请稍后重试';
    useNotificationStore().error(errorMsg);
  }
};

let clickHandler: ((event: Event) => void) | undefined;
const setupCodeCopy = () => {
  const contentContainer = document.querySelector('.prose');
  if (!contentContainer) return;

  if (clickHandler) {
    contentContainer.removeEventListener('click', clickHandler);
  }

  clickHandler = (event: Event) => {
    const target = event.target as HTMLElement;
    if (target.classList.contains('copy-btn')) {
      const codeBlock = target.closest('pre');
      if (codeBlock) {
        const codeElement = codeBlock.querySelector('code');
        if (codeElement) {
          navigator.clipboard
            .writeText(codeElement.textContent ?? '')
            .then(() => {
              useNotificationStore().success('代码已复制到剪贴板');
            })
            .catch(() => {
              useNotificationStore().error('复制失败，请手动复制');
            });
        }
      }
    }
  };

  contentContainer.addEventListener('click', clickHandler);

  contentContainer.querySelectorAll('.copy-btn').forEach((btn) => btn.remove());

  const codeBlocks = contentContainer.querySelectorAll('pre');
  codeBlocks.forEach((block) => {
    block.classList.add('w-full', 'whitespace-pre-wrap');
    const button = document.createElement('button');
    button.innerHTML = `<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-copy-icon lucide-copy"><rect width="14" height="14" x="8" y="8" rx="2" ry="2"/><path d="M4 16c-1.1 0-2-.9-2-2V4c0-1.1.9-2 2-2h10c1.1 0 2 .9 2 2"/></svg>`;
    button.className =
      'copy-btn absolute top-1 w-fit right-3 rounded-lg bg-secondary/90 p-1 text-foreground';
    block.style.position = 'relative';
    block.appendChild(button);
  });
};

onUnmounted(() => {
  const contentContainer = document.querySelector('.prose');
  if (contentContainer && clickHandler) {
    contentContainer.removeEventListener('click', clickHandler);
  }
});
</script>

<template>
  <div>
    <BasicDetail :title="post?.title || ''" :subtitle="subtitle">
      <!-- Loading -->
      <div v-if="isLoading" class="sm:col-span-2 lg:col-span-3">
        <div
          class="border-border bg-background animate-pulse space-y-6 rounded-2xl border p-8 shadow-sm"
        >
          <div class="bg-muted mb-6 h-8 w-3/4 rounded" />
          <div class="mb-8 flex gap-4">
            <div class="bg-muted h-4 w-24 rounded" />
            <div class="bg-muted h-4 w-32 rounded" />
          </div>
          <div class="space-y-4">
            <div class="bg-muted h-4 w-full rounded" />
            <div class="bg-muted h-4 w-full rounded" />
            <div class="bg-muted h-4 w-5/6 rounded" />
            <div class="bg-muted h-4 w-full rounded" />
            <div class="bg-muted h-4 w-4/5 rounded" />
          </div>
        </div>
      </div>

      <!-- Error -->
      <div v-else-if="errorMessage" class="sm:col-span-2 lg:col-span-3">
        <div
          class="border-destructive/30 bg-destructive/5 flex flex-col items-center justify-center rounded-2xl border border-dashed py-16 text-center"
        >
          <svg
            xmlns="http://www.w3.org/2000/svg"
            class="text-destructive mb-4 h-12 w-12"
            fill="none"
            viewBox="0 0 24 24"
            stroke-width="1.5"
            stroke="currentColor"
          >
            <path
              stroke-linecap="round"
              stroke-linejoin="round"
              d="M12 9v3.75m-9.303 3.376c-.866 1.5.217 3.374 1.948 3.374h14.71c1.73 0 2.813-1.874 1.948-3.374L13.949 3.378c-.866-1.5-3.032-1.5-3.898 0L2.697 16.126zM12 15.75h.007v.008H12v-.008z"
            />
          </svg>
          <p class="text-destructive text-lg font-medium">加载失败</p>
          <p class="text-muted-foreground mt-1 text-sm">{{ errorMessage }}</p>
          <button
            @click="handleRetry"
            class="bg-destructive/90 hover:bg-destructive mt-4 cursor-pointer rounded-lg px-4 py-2 text-sm font-medium text-white"
          >
            重试
          </button>
        </div>
      </div>

      <!-- Content -->
      <template v-else>
        <div
          v-if="showEditButton && post"
          class="flex items-center justify-end gap-2 sm:col-span-2 lg:col-span-3"
        >
          <router-link
            :to="`/blog/${post._id}/edit`"
            class="bg-muted text-foreground hover:bg-muted/80 inline-flex cursor-pointer items-center gap-2 rounded-xl px-4 py-2 text-sm font-medium transition-colors"
          >
            <EditIcon />
            编辑
          </router-link>
          <button
            @click="showDeleteDialog = true"
            class="bg-destructive/10 text-destructive hover:bg-destructive/15 inline-flex cursor-pointer items-center gap-2 rounded-xl px-4 py-2 text-sm font-medium transition-colors"
          >
            <DelIcon />
            删除
          </button>
        </div>

        <div
          v-if="post"
          class="border-border bg-background overflow-hidden rounded-2xl border shadow-sm sm:col-span-2 lg:col-span-3"
        >
          <div
            v-if="post.cover"
            class="border-border bg-muted aspect-[16/9] w-full overflow-hidden border-x border-t"
          >
            <img
              :src="coverSrc"
              :alt="`${post.title} 封面`"
              class="h-full w-full object-cover"
              loading="lazy"
            />
          </div>
          <div class="border-border border-b p-8">
            <h1 class="text-foreground mb-4 text-3xl leading-tight font-bold">
              {{ post.title }}
            </h1>

            <div class="text-primary flex flex-wrap gap-x-6 gap-y-3 text-sm">
              <div
                v-if="post.author"
                class="flex items-center gap-1.5 font-medium"
              >
                <svg
                  xmlns="http://www.w3.org/2000/svg"
                  fill="none"
                  viewBox="0 0 24 24"
                  stroke-width="1.5"
                  stroke="currentColor"
                  class="h-4 w-4"
                >
                  <path
                    stroke-linecap="round"
                    stroke-linejoin="round"
                    d="M15.75 6a3.75 3.75 0 11-7.5 0 3.75 3.75 0 017.5 0zM4.501 20.118a7.5 7.5 0 0114.998 0A17.933 17.933 0 0112 21.75c-2.676 0-5.216-.584-7.499-1.632z"
                  />
                </svg>
                {{ post.author }}
              </div>

              <div v-if="post.created_at" class="flex items-center gap-1.5">
                <CalendarIcon />
                {{ formatDate(post.created_at) }}
              </div>
            </div>
          </div>

          <div class="p-8">
            <ArticleSummaryCard
              :title="post.title"
              :content="post.body || ''"
            />
            <div class="prose prose-lg max-w-none">
              <div v-if="post.body" v-html="renderedBodyWithOrigin" />
              <div v-else class="text-muted-foreground italic">暂无内容</div>
            </div>
          </div>
        </div>

        <TwikooComments
          v-if="post"
          :path="`/blog/${postId}`"
          class="sm:col-span-2 lg:col-span-3"
        />
      </template>
    </BasicDetail>

    <Teleport to="body">
      <AlertDialog
        :open="showDeleteDialog"
        @update:open="showDeleteDialog = $event"
      >
        <AlertDialogContent class="sm:max-w-[425px]">
          <AlertDialogHeader>
            <AlertDialogTitle>Are you sure delete this Post?</AlertDialogTitle>
            <AlertDialogDescription>
              The action cannot be undone.
            </AlertDialogDescription>
          </AlertDialogHeader>
          <AlertDialogFooter>
            <AlertDialogCancel>Cancel</AlertDialogCancel>
            <AlertDialogAction
              class="bg-destructive hover:bg-destructive/90 text-white"
              @click="confirmDelete"
            >
              Delete
            </AlertDialogAction>
          </AlertDialogFooter>
        </AlertDialogContent>
      </AlertDialog>
    </Teleport>
  </div>
</template>

<style>
@import 'twikoo/dist/twikoo.css';

.copy-btn::before {
  content: '复制';
  position: absolute;
  bottom: -150%;
  left: 50%;
  transform: translateX(-50%) translateY(4px);
  opacity: 0;
  transition:
    opacity 0.2s ease-out,
    transform 0.2s ease-out;
  padding: 4px 8px;
  background: var(--ink);
  color: var(--paper);
  border-radius: 4px;
  pointer-events: none;
  font-size: 0.875rem;
  white-space: nowrap;
}

.copy-btn:hover::before {
  opacity: 1;
  transform: translateX(-50%) translateY(0);
}
/* 文章阅读体验由 .prose（base.scss）统一提供。 */
</style>

// react-app/src/views/Blog/BlogPostView.tsx
import { ArticleSummaryCard } from '@/components/basic/ArticleSummary';
import type { BlogDetail } from '@/services/blogService';
import { blogService } from '@/services/blogService';
import { TwikooComments } from '@/components/blog/TwikooComments';
import { useAuthStore } from '@/stores/authState';
import { useNotificationStore } from '@/stores/notificationState';
import { formatDate } from '@/utils/formatdate';
import { AnimatePresence, motion } from 'framer-motion';
import hljs from 'highlight.js/lib/common';
import 'highlight.js/styles/github.css';
import { marked } from 'marked';
import { useCallback, useEffect, useRef, useState } from 'react';
import { useNavigate, useParams } from 'react-router-dom';

function LoadingSkeleton() {
  return (
    <div className="border-border bg-card animate-pulse space-y-6 rounded-2xl border p-6 shadow-sm sm:p-8">
      <div className="space-y-4">
        <div className="bg-muted h-8 w-3/4 rounded-lg" />
        <div className="bg-muted h-4 w-1/4 rounded" />
      </div>
      <div className="bg-border/60 h-1 w-16" />
      <div className="space-y-3">
        <div className="bg-muted h-4 w-full rounded" />
        <div className="bg-muted h-4 w-full rounded" />
        <div className="bg-muted h-4 w-5/6 rounded" />
        <div className="bg-muted h-4 w-full rounded" />
        <div className="bg-muted h-4 w-4/5 rounded" />
      </div>
    </div>
  );
}

function ErrorState({
  message,
  onRetry,
}: {
  message: string;
  onRetry: () => void;
}) {
  return (
    <div className="border-destructive/30 bg-destructive/5 flex flex-col items-center justify-center rounded-2xl border border-dashed py-16 text-center">
      <svg
        xmlns="http://www.w3.org/2000/svg"
        className="text-destructive mb-4 h-12 w-12"
        fill="none"
        viewBox="0 0 24 24"
        strokeWidth="1.5"
        stroke="currentColor"
      >
        <path
          strokeLinecap="round"
          strokeLinejoin="round"
          d="M12 9v3.75m-9.303 3.376c-.866 1.5.217 3.374 1.948 3.374h14.71c1.73 0 2.813-1.874 1.948-3.374L13.949 3.378c-.866-1.5-3.032-1.5-3.898 0L2.697 16.126zM12 15.75h.007v.008H12v-.008z"
        />
      </svg>
      <p className="text-destructive text-lg font-medium">加载失败</p>
      <p className="text-muted-foreground mt-1 text-sm">{message}</p>
      <button
        onClick={onRetry}
        className="bg-destructive/90 hover:bg-destructive mt-4 cursor-pointer rounded-lg px-5 py-2.5 text-sm font-medium text-white transition-transform active:scale-95"
      >
        重试
      </button>
    </div>
  );
}

const COPY_ICON_SVG = `<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 01-2-2V4a2 2 0 012-2h9a2 2 0 012 2v1"/></svg>`;

function setupCodeCopy(
  container: HTMLElement,
  onCopy: (msg: string) => void,
): () => void {
  const preElements = container.querySelectorAll('pre');
  const cleanups: (() => void)[] = [];

  preElements.forEach((pre) => {
    pre.style.position = 'relative';
    pre.classList.add('group');

    const btn = document.createElement('button');
    btn.innerHTML = COPY_ICON_SVG;
    btn.title = '复制';
    btn.className =
      'absolute top-2 right-2 p-1.5 rounded-md bg-muted/80 text-muted-foreground opacity-0 group-hover:opacity-100 transition-opacity duration-200 hover:bg-accent cursor-pointer';
    btn.setAttribute('aria-label', '复制代码');

    const handleClick = () => {
      const code = pre.querySelector('code');
      if (code) {
        navigator.clipboard
          .writeText(code.textContent || '')
          .then(() => onCopy('代码已复制'))
          .catch(() => onCopy('复制失败'));
      }
    };

    btn.addEventListener('click', handleClick);
    pre.appendChild(btn);
    cleanups.push(() => {
      btn.removeEventListener('click', handleClick);
      btn.remove();
    });
  });

  return () => cleanups.forEach((fn) => fn());
}

export default function BlogPostView() {
  const { postId } = useParams<{ postId: string }>();
  const navigate = useNavigate();
  const notification = useNotificationStore();
  const { user, isAuthenticated } = useAuthStore();

  const [post, setPost] = useState<BlogDetail | null>(null);
  const [isLoading, setIsLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [showDeleteDialog, setShowDeleteDialog] = useState(false);
  const contentRef = useRef<HTMLDivElement>(null);

  const showEditButton = isAuthenticated && user?.is_admin;

  // SEO: set document title
  useEffect(() => {
    if (post?.title) {
      document.title = `${post.title} - ReadingList`;
    }
    return () => {
      document.title = 'ReadingList';
    };
  }, [post?.title]);

  // Render markdown to HTML
  const renderedBody = post?.body
    ? (marked.parse(post.body, { async: false, breaks: false }) as string)
    : '';

  // Highlight code blocks + setup copy buttons after content renders
  useEffect(() => {
    if (contentRef.current && renderedBody) {
      hljs.highlightAll();
      const cleanup = setupCodeCopy(contentRef.current, (msg) =>
        notification.success(msg),
      );
      return cleanup;
    }
  }, [renderedBody, notification]);

  const fetchPost = useCallback(async () => {
    if (!postId) return;

    setIsLoading(true);
    setError(null);

    try {
      const service = blogService();
      const result = await service.getBlogPost(postId);
      setPost(result);
    } catch (err) {
      setError(err instanceof Error ? err.message : '加载文章失败');
    } finally {
      setIsLoading(false);
    }
  }, [postId]);

  useEffect(() => {
    fetchPost();
  }, [fetchPost]);

  const handleDelete = async () => {
    if (!postId) return;
    setShowDeleteDialog(false);
    try {
      const service = blogService();
      await service.deleteLegacyPost(postId);
      notification.success('文章删除成功');
      navigate('/blog');
    } catch (err) {
      const msg = err instanceof Error ? err.message : '删除文章失败';
      notification.error(msg);
    }
  };

  return (
    <div className="bg-background min-h-dvh">
      {/* Header */}
      <div className="bg-surface sticky top-0 z-10 backdrop-blur-md">
        <div className="flex items-center gap-3 px-4 py-3">
          <button
            onClick={() => navigate(-1)}
            className="hover:bg-accent flex h-11 w-11 items-center justify-center rounded-full transition-transform active:scale-95"
          >
            <svg
              className="text-foreground h-5 w-5"
              fill="none"
              stroke="currentColor"
              viewBox="0 0 24 24"
            >
              <path
                strokeLinecap="round"
                strokeLinejoin="round"
                strokeWidth="2"
                d="M15 19l-7-7 7-7"
              />
            </svg>
          </button>
          <h1 className="text-foreground flex-1 truncate text-lg font-semibold">
            {post?.title || '文章'}
          </h1>
        </div>
      </div>

      <AnimatePresence mode="wait">
        {isLoading ? (
          <motion.div
            key="loading"
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ opacity: 0 }}
            className="px-5 pt-5"
          >
            <LoadingSkeleton />
          </motion.div>
        ) : error ? (
          <motion.div
            key="error"
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ opacity: 0 }}
            className="px-5 pt-5"
          >
            <ErrorState message={error} onRetry={fetchPost} />
          </motion.div>
        ) : post ? (
          <motion.article
            key="content"
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            exit={{ opacity: 0 }}
            className="pb-20"
          >
            {/* Admin actions */}
            {showEditButton && (
              <div className="flex items-center justify-end gap-2 px-5 pt-4">
                <button
                  onClick={() => navigate(`/blog/edit/${post._id}`)}
                  className="bg-accent text-foreground hover:bg-accent/80 inline-flex cursor-pointer items-center gap-2 rounded-xl px-4 py-2.5 text-sm font-medium transition-colors"
                >
                  <svg
                    xmlns="http://www.w3.org/2000/svg"
                    className="h-4 w-4"
                    fill="none"
                    viewBox="0 0 24 24"
                    strokeWidth="1.5"
                    stroke="currentColor"
                  >
                    <path
                      strokeLinecap="round"
                      strokeLinejoin="round"
                      d="M16.862 4.487l1.687-1.688a1.875 1.875 0 112.652 2.652L10.582 16.07a4.5 4.5 0 01-1.897 1.13L6 18l.8-2.685a4.5 4.5 0 011.13-1.897l8.932-8.931zm0 0L19.5 7.125M18 14v4.75A2.25 2.25 0 0115.75 21H5.25A2.25 2.25 0 013 18.75V8.25A2.25 2.25 0 015.25 6H10"
                    />
                  </svg>
                  编辑
                </button>
                <button
                  onClick={() => setShowDeleteDialog(true)}
                  className="bg-destructive/10 text-destructive hover:bg-destructive/15 inline-flex cursor-pointer items-center gap-2 rounded-xl px-4 py-2.5 text-sm font-medium transition-colors"
                >
                  <svg
                    xmlns="http://www.w3.org/2000/svg"
                    className="h-4 w-4"
                    fill="none"
                    viewBox="0 0 24 24"
                    strokeWidth="1.5"
                    stroke="currentColor"
                  >
                    <path
                      strokeLinecap="round"
                      strokeLinejoin="round"
                      d="M14.74 9l-.346 9m-4.788 0L9.26 9m9.968-3.21c.342.052.682.107 1.022.166m-1.022-.165L18.16 19.673a2.25 2.25 0 01-2.244 2.077H8.084a2.25 2.25 0 01-2.244-2.077L4.772 5.79m14.456 0a48.108 48.108 0 00-3.478-.397m-12 .562c.34-.059.68-.114 1.022-.165m0 0a48.11 48.11 0 013.478-.397m7.5 0v-.916c0-1.18-.91-2.164-2.09-2.201a51.964 51.964 0 00-3.32 0c-1.18.037-2.09 1.022-2.09 2.201v.916m7.5 0a48.667 48.667 0 00-7.5 0"
                    />
                  </svg>
                  删除
                </button>
              </div>
            )}

            {/* Hero */}
            <div className="px-5 pt-4">
              {post.is_pinned && (
                <div className="bg-primary/15 text-primary mb-3 inline-flex items-center gap-1.5 rounded-full px-3 py-1 text-xs font-medium">
                  <svg
                    xmlns="http://www.w3.org/2000/svg"
                    className="h-3.5 w-3.5"
                    viewBox="0 0 20 20"
                    fill="currentColor"
                  >
                    <path d="M5 4a2 2 0 012-2h6a2 2 0 012 2v14l-5-2.5L5 18V4z" />
                  </svg>
                  置顶文章
                </div>
              )}

              <h1 className="text-foreground text-2xl leading-tight font-bold sm:text-3xl">
                {post.title}
              </h1>

              <div className="text-primary mt-3 flex flex-wrap gap-x-6 gap-y-2 text-sm">
                <div className="flex items-center gap-1.5 font-medium">
                  <svg
                    xmlns="http://www.w3.org/2000/svg"
                    fill="none"
                    viewBox="0 0 24 24"
                    strokeWidth="1.5"
                    stroke="currentColor"
                    className="h-4 w-4"
                  >
                    <path
                      strokeLinecap="round"
                      strokeLinejoin="round"
                      d="M15.75 6a3.75 3.75 0 11-7.5 0 3.75 3.75 0 017.5 0zM4.501 20.118a7.5 7.5 0 0114.998 0A17.933 17.933 0 0112 21.75c-2.676 0-5.216-.584-7.499-1.632z"
                    />
                  </svg>
                  {post.category?.name || '未分类'}
                </div>
                {post.created_at && (
                  <div className="flex items-center gap-1.5">
                    <svg
                      xmlns="http://www.w3.org/2000/svg"
                      className="h-4 w-4"
                      fill="none"
                      viewBox="0 0 24 24"
                      strokeWidth="1.5"
                      stroke="currentColor"
                    >
                      <path
                        strokeLinecap="round"
                        strokeLinejoin="round"
                        d="M6.75 3v2.25M17.25 3v2.25M3 18.75V7.5a2.25 2.25 0 012.25-2.25h13.5A2.25 2.25 0 0121 7.5v11.25m-18 0A2.25 2.25 0 005.25 21h13.5A2.25 2.25 0 0021 18.75m-18 0v-7.5A2.25 2.25 0 015.25 9h13.5A2.25 2.25 0 0121 11.25v7.5"
                      />
                    </svg>
                    {formatDate(post.created_at)}
                  </div>
                )}
              </div>
            </div>

            {/* Divider */}
            <div className="bg-muted mx-5 my-4 h-px" />

            {/* Content card */}
            <div className="border-border bg-card mx-5 overflow-hidden rounded-2xl border shadow-sm">
              <div className="p-5 sm:p-8">
                {/* Article Summary */}
                <ArticleSummaryCard
                  title={post?.title}
                  content={post?.body || ''}
                />

                {/* Markdown body */}
                <div
                  ref={contentRef}
                  className="article-content prose prose-lg dark:prose-invert max-w-none"
                >
                  {renderedBody ? (
                    <div dangerouslySetInnerHTML={{ __html: renderedBody }} />
                  ) : (
                    <p className="text-muted-foreground italic">暂无内容</p>
                  )}
                </div>
              </div>
            </div>

            {/* Comments */}
            <div className="px-5 pt-5">
              <TwikooComments path={`/blog/${postId}`} />
            </div>
          </motion.article>
        ) : null}
      </AnimatePresence>

      {/* Delete confirmation dialog */}
      {showDeleteDialog && (
        <div className="fixed inset-0 z-50 flex items-center justify-center p-4">
          <div
            className="bg-foreground/80 fixed inset-0 backdrop-blur-sm"
            onClick={() => setShowDeleteDialog(false)}
          />
          <div className="bg-card border-border relative w-full max-w-sm rounded-2xl border p-6 shadow-lg">
            <h3 className="text-foreground text-lg font-semibold">确认删除</h3>
            <p className="text-muted-foreground mt-2 text-sm">
              确定要删除这篇文章吗？此操作无法撤销。
            </p>
            <div className="mt-6 flex justify-end gap-3">
              <button
                onClick={() => setShowDeleteDialog(false)}
                className="bg-accent text-foreground hover:bg-accent/80 rounded-xl px-4 py-2.5 text-sm font-medium transition-colors"
              >
                取消
              </button>
              <button
                onClick={handleDelete}
                className="bg-destructive hover:bg-destructive/90 rounded-xl px-4 py-2.5 text-sm font-medium text-white transition-colors"
              >
                删除
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
