// frontend/src/views/BlogPostView.vue
<script setup lang="ts">
import ArticleToc from "@/components/ArticleToc.vue";
import CommentForm from "@/components/CommentForm.vue";
import CommentItem from "@/components/CommentItem.vue";
import request from "@/request";
import { useAuthStore } from "@/stores/auth";
import { useNotificationStore } from "@/stores/notification";
import type { Comment, Post, PostResponse } from "@/types";
import { formatDate } from "@/utils/formatdate";
import { useHead } from "@unhead/vue";
import { computed, onMounted, ref, watch } from "vue";
import { useRoute, useRouter } from "vue-router";

const route = useRoute();
const router = useRouter();
const postId = ref<string>(route.params.id as string);

const post = ref<Post | null>(null);
const isLoading = ref(false);
const errorMessage = ref("");
const notFound = ref(false);

const auth = useAuthStore();
const showEditButton = computed(() => !!auth.user?.is_admin);

const fetchPost = async () => {
  if (!postId.value) {
    errorMessage.value = "无效的文章 ID";
    return;
  }

  isLoading.value = true;
  errorMessage.value = "";

  try {
    const res = await request.get<PostResponse>("/post", {
      params: { _id: postId.value },
    });

    if (res.data.status === "success") {
      post.value = res.data.data;
    } else {
      throw new Error(res.data.message || "获取文章失败");
    }
  } catch (err: unknown) {
    console.error(err);
    errorMessage.value = err instanceof Error ? err.message : "加载文章失败，请稍后重试。";
    useNotificationStore().error(errorMessage.value);
  } finally {
    isLoading.value = false;
  }
};

onMounted(() => {
  fetchPost();
});

watch(
  () => route.params.id,
  (newId) => {
    if (newId && newId !== postId.value) {
      postId.value = newId as string;
      fetchPost();
    }
  },
);

// 设置页面 meta 标签
useHead(() => ({
  title: post.value ? `${post.value.title} - ReadingList` : "文章未找到 - ReadingList",
  meta: [
    {
      name: "description",
      content: post.value
        ? post.value.summary || `阅读 ${post.value.title} 的完整内容`
        : "抱歉，您请求的文章不存在或已被删除",
    },
    {
      name: "keywords",
      content: post.value
        ? [
            post.value.title,
            post.value.author || "Kurroome",
            post.value.category?.name || "博客",
            "阅读",
            "读书笔记",
            "个人博客",
          ]
            .filter(Boolean)
            .join(", ")
        : "文章未找到, 阅读清单, ReadingList",
    },
    {
      property: "og:title",
      content: post.value ? post.value.title : "文章未找到",
    },
    {
      property: "og:description",
      content: post.value
        ? post.value.summary || `阅读 ${post.value.title} 的完整内容`
        : "抱歉，您请求的文章不存在或已被删除",
    },
    {
      property: "og:type",
      content: "article",
    },
    {
      property: "og:url",
      content: `https://readinglist.example.com/blog/${postId.value}`,
    },
    {
      property: "og:article:author",
      content: post.value?.author || "Kurroome",
    },
    {
      property: "og:article:published_time",
      content: post.value?.created_at,
    },
    {
      property: "og:article:modified_time",
      content: post.value?.updated_at,
    },
    {
      property: "og:article:section",
      content: post.value?.category?.name || "博客",
    },
    {
      name: "twitter:title",
      content: post.value ? post.value.title : "文章未找到",
    },
    {
      name: "twitter:description",
      content: post.value
        ? post.value.summary || `阅读 ${post.value.title} 的完整内容`
        : "抱歉，您请求的文章不存在或已被删除",
    },
  ],
}));

const comments = computed(() => {
  return post.value?.comments || [];
});

const goBack = () => {
  router.push("/blog");
};

// 处理评论回复
const handleReply = async (commentId: string, body: string) => {
  try {
    // 递归查找评论的方法
    const findComment = (commentsList: Comment[], id: string): Comment | undefined => {
      for (const comment of commentsList) {
        if (comment._id === id) {
          return comment;
        }
        if (comment.comments && comment.comments.length > 0) {
          const found = findComment(comment.comments, id);
          if (found) {
            return found;
          }
        }
      }
      return undefined;
    };

    // 获取被回复的评论信息
    const parentComment = findComment(post.value?.comments || [], commentId);

    if (!parentComment) {
      useNotificationStore().error("找不到要回复的评论");
      return;
    }

    // 提交回复到后端
    const res = await request.post("/comments", {
      post_id: postId.value,
      body: body,
      reply_to: commentId, // 被回复的评论ID
      reply_to_author: parentComment.author, // 被回复者用户名
      author: auth.isAuthenticated && auth.user ? auth.user.username : "",
    });

    if (res.data.status === "success" || res.status === 200 || res.status === 201) {
      useNotificationStore().success("评论已提交，待审核后显示");
      // 刷新文章数据以获取最新评论
      await fetchPost();
    } else {
      throw new Error(res.data.message || "提交评论失败");
    }
  } catch (err: unknown) {
    console.error("提交回复失败:", err);
    const errorMsg = err instanceof Error ? err.message : "提交评论失败，请稍后重试";
    useNotificationStore().error(errorMsg);
  }
};
</script>

<template>
  <div class="container mx-auto px-4 py-8">
    <router-link
      to="/blog"
      class="group mb-6 inline-flex items-center gap-2 rounded-xl bg-blue-600 px-6 py-3 font-semibold text-white shadow-md transition-all hover:bg-blue-700 hover:shadow-lg"
    >
      <svg
        class="h-4 w-4 transition-transform group-hover:-translate-x-1"
        fill="none"
        stroke="currentColor"
        viewBox="0 0 24 24"
      >
        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15 19l-7-7 7-7" />
      </svg>
      返回博客列表
    </router-link>
    <!-- Loading State -->
    <div v-if="isLoading" class="flex min-h-[60vh] flex-col items-center justify-center">
      <div
        class="h-12 w-12 animate-spin rounded-full border-4 border-blue-200 border-t-blue-600"
      ></div>
      <p class="mt-4 text-gray-600 dark:text-gray-400">加载中...</p>
    </div>

    <!-- Error State -->
    <div
      v-else-if="errorMessage"
      class="flex min-h-[60vh] flex-col items-center justify-center rounded-xl border border-red-200 bg-red-50 px-6 py-16 text-center dark:border-red-800 dark:bg-red-900/20"
    >
      <svg
        xmlns="http://www.w3.org/2000/svg"
        class="mb-4 h-12 w-12 text-red-400"
        fill="none"
        viewBox="0 0 24 24"
        stroke-width="1.5"
        stroke="currentColor"
      >
        <path
          stroke-linecap="round"
          stroke-linejoin="round"
          d="M12 9v3.75m-9.303 3.376c-.866 1.5.217 3.374 1.948 3.374h14.71c1.73 0 2.813-1.874 1.948-3.374L13.949 3.378c-.866-1.5-3.032-1.5-3.898 0L2.697 16.126zM12 15.75h.007v.008H12v-.008z"
        />
      </svg>
      <p class="text-lg font-medium text-red-600 dark:text-red-400">加载失败</p>
      <p class="mt-1 text-sm text-red-500">{{ errorMessage }}</p>
      <div class="mt-4 space-x-4">
        <button
          class="rounded-lg bg-red-600 px-4 py-2 text-sm font-medium text-white hover:bg-red-700 focus:ring-2 focus:ring-red-500 focus:ring-offset-2 focus:outline-none"
          @click="fetchPost"
        >
          重试
        </button>
        <button
          class="rounded-lg bg-gray-200 px-4 py-2 text-sm font-medium text-gray-700 hover:bg-gray-300 focus:ring-2 focus:ring-gray-500 focus:ring-offset-2 focus:outline-none"
          @click="goBack"
        >
          返回列表
        </button>
      </div>
    </div>

    <!-- 404 Not Found -->
    <div
      v-else-if="notFound || !post"
      class="flex min-h-[60vh] flex-col items-center justify-center px-6 py-16 text-center"
    >
      <div class="mb-4 text-9xl font-bold text-gray-200 dark:text-gray-700">404</div>
      <h2 class="mb-2 text-2xl font-bold text-gray-900 dark:text-white">文章未找到</h2>
      <p class="mb-6 text-gray-600 dark:text-gray-400">抱歉，您请求的文章不存在或已被删除。</p>
      <button
        class="rounded-lg bg-blue-600 px-6 py-2 text-sm font-medium text-white hover:bg-blue-700 focus:ring-2 focus:ring-blue-500 focus:ring-offset-2 focus:outline-none"
        @click="goBack"
      >
        返回文章列表
      </button>
    </div>

    <!-- Main Content -->
    <div v-else class="relative mx-auto max-w-7xl">
      <div class="flex flex-col gap-8 lg:flex-row">
        <!-- 文章内容卡片 - 占据主要空间并居中 -->
        <div class="min-w-0 flex-1">
          <div
            class="w-full min-w-0 rounded-[36px] bg-gray-100/90 p-8 shadow-2xl backdrop-blur-xl dark:bg-gray-800/90"
          >
            <!-- 文章头部区域 -->
            <div class="p-6">
              <h1 class="mb-6 text-3xl font-bold dark:text-white">
                {{ post.title || "" }}
              </h1>

              <!-- 作者和日期信息 -->
              <div
                class="flex flex-wrap items-center gap-4 text-sm text-gray-600 dark:text-gray-400"
              >
                <div class="flex items-center gap-2">
                  <div
                    class="flex h-10 w-10 items-center justify-center rounded-full bg-linear-to-br from-blue-500 to-sky-600 text-lg font-bold text-white"
                  >
                    {{ post.author?.charAt(0).toUpperCase() || "K" }}
                  </div>
                  <span class="font-medium text-gray-900 dark:text-gray-200"
                    >@{{ post.author || "Kurroome" }}</span
                  >
                </div>
                <span class="text-gray-400">·</span>
                <div class="flex items-center gap-1">
                  <svg class="h-4 w-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                    <path
                      stroke-linecap="round"
                      stroke-linejoin="round"
                      stroke-width="2"
                      d="M8 7V3m8 4V3m-9 8h10M5 21h14a2 2 0 002-2V7a2 2 0 00-2-2H5a2 2 0 00-2 2v12a2 2 0 002 2z"
                    />
                  </svg>
                  <span v-if="post.created_at && post.updated_at !== post.created_at">{{
                    formatDate(post.updated_at)
                  }}</span>
                  <span v-else>{{ formatDate(post.created_at) }}</span>
                </div>
                <span v-if="post.category" class="flex items-center gap-1">
                  <svg class="h-4 w-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                    <path
                      stroke-linecap="round"
                      stroke-linejoin="round"
                      stroke-width="2"
                      d="M7 7h.01M7 3h5c.512 0 1.024.195 1.414.586l7 7a2 2 0 010 2.828l-7 7a2 2 0 01-2.828 0l-7-7A1.994 1.994 0 013 12V7a4 4 0 014-4z"
                    />
                  </svg>
                  <router-link
                    :to="`/blog/category/${post.category.id}`"
                    class="text-blue-600 hover:text-blue-800 hover:underline dark:text-blue-400 dark:hover:text-blue-300"
                  >
                    {{ post.category.name }}
                  </router-link>
                </span>
              </div>
            </div>

            <!-- 文章内容区 -->
            <div class="mb-8 px-6">
              <div class="prose prose-base dark:prose-invert max-w-none">
                <!-- 使用 v-html 渲染 HTML 内容（取消转译） -->
                <div v-if="post.body" v-html="post.body" />
                <div v-else class="text-gray-400 italic">暂无内容</div>
              </div>
            </div>

            <!-- 评论区 - 独立卡片 -->
            <div id="comments" class="p-8">
              <div
                class="mb-8 flex items-center gap-4 border-b border-gray-100 pb-6 dark:border-gray-700"
              >
                <h3 class="text-2xl font-bold text-gray-900 dark:text-white">评论</h3>
                <span
                  v-if="post.comments && post.comments.length > 0"
                  class="rounded-full bg-blue-100 px-3 py-1 text-sm font-semibold text-blue-700 dark:bg-blue-900/50 dark:text-blue-300"
                >
                  {{ post.comments.length }}
                </span>
              </div>

              <div v-if="comments.length > 0" class="space-y-6">
                <CommentItem
                  v-for="comment in comments"
                  :key="comment._id"
                  :comment="comment"
                  :post-id="postId"
                  @reply="handleReply"
                />
              </div>

              <!-- Empty State -->
              <div
                v-else
                class="mb-8 flex flex-col items-center justify-center rounded-2xl border border-dashed border-gray-200 bg-gray-50/50 py-12 text-center dark:border-gray-700 dark:bg-gray-800/30"
              >
                <div
                  class="mb-4 flex h-16 w-16 items-center justify-center rounded-full bg-white shadow-sm ring-1 ring-gray-100 dark:bg-gray-800 dark:ring-gray-700"
                >
                  <svg
                    class="h-8 w-8 text-gray-400 dark:text-gray-500"
                    fill="none"
                    stroke="currentColor"
                    viewBox="0 0 24 24"
                  >
                    <path
                      stroke-linecap="round"
                      stroke-linejoin="round"
                      stroke-width="1.5"
                      d="M8 12h.01M12 12h.01M16 12h.01M21 12c0 4.418-4.03 8-9 8a9.863 9.863 0 01-4.255-.949L3 20l1.395-3.72C3.512 15.042 3 13.574 3 12c0-4.418 4.03-8 9-8s9 3.582 9 8z"
                    />
                  </svg>
                </div>
                <h3 class="text-lg font-semibold text-gray-900 dark:text-white">暂无评论</h3>
                <p class="mx-auto mt-2 max-w-sm text-sm text-gray-500 dark:text-gray-400">
                  成为第一个评论的人吧！
                </p>
              </div>

              <CommentForm :post-id="postId" />
            </div>

            <!-- 底部导航 -->
            <div class="mt-8 flex justify-center">
              <router-link
                v-if="showEditButton"
                :to="`/blog/edit/${post._id}`"
                class="ml-4 inline-flex items-center gap-2 rounded-xl bg-gray-100 px-6 py-3 font-semibold text-gray-700 shadow-md transition-all hover:bg-gray-200 dark:bg-gray-800 dark:text-gray-300 dark:hover:bg-gray-700"
              >
                <svg class="h-4 w-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                  <path
                    stroke-linecap="round"
                    stroke-linejoin="round"
                    stroke-width="2"
                    d="M11 5H6a2 2 0 00-2 2v11a2 2 0 002 2h11a2 2 0 002-2v-5m-1.414-9.414a2 2 0 112.828 2.828L11.828 15H9v-2.828l8.586-8.586z"
                  />
                </svg>
                编辑文章
              </router-link>
            </div>
          </div>
        </div>

        <!-- 目录侧边栏卡片 - 大屏显示在右侧 -->
        <div class="hidden lg:block lg:w-64 lg:shrink-0">
          <div class="sticky top-24">
            <ArticleToc :content="post.body" />
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

// react-app/src/views/Blog/BlogPostView.tsx
import type { BlogDetail } from '@/services/blogService';
import { blogService } from '@/services/blogService';
import type { Comment } from '@/types';
import { formatDate } from '@/utils/formatdate';
import DOMPurify from 'dompurify';
import { motion, AnimatePresence } from 'framer-motion';
import { useCallback, useEffect, useRef, useState } from 'react';
import { useParams, useNavigate } from 'react-router-dom';

function sanitizeHtml(html: string): string {
  if (!html) return '';
  return DOMPurify.sanitize(html, { USE_PROFILES: { html: true } });
}

function CommentItem({
  comment,
  depth = 0,
  onReply,
}: {
  comment: Comment;
  depth?: number;
  onReply: (comment: Comment) => void;
}) {
  return (
    <motion.div
      initial={{ opacity: 0, y: 10 }}
      animate={{ opacity: 1, y: 0 }}
      className={`${depth > 0 ? 'ml-4 border-l-2 border-gray-100 dark:border-gray-800 pl-4' : ''}`}
    >
      <div className="py-3">
        <div className="flex items-center gap-2">
          <div className="flex h-8 w-8 items-center justify-center rounded-full bg-gradient-to-br from-blue-500 to-sky-500 text-sm font-bold text-white">
            {comment.author?.[0]?.toUpperCase() || 'A'}
          </div>
          <div className="flex-1">
            <div className="flex items-center gap-2">
              <span className="font-medium text-gray-900 dark:text-white">
                {comment.author}
              </span>
              {comment.from_admin && (
                <span className="rounded-full bg-blue-100 px-2 py-0.5 text-xs font-medium text-blue-600 dark:bg-blue-900/30 dark:text-blue-400">
                  博主
                </span>
              )}
              <span className="text-xs text-gray-400">
                {formatDate(comment.created_at)}
              </span>
            </div>
          </div>
          <button
            onClick={() => onReply(comment)}
            className="rounded-lg px-2 py-1 text-xs text-gray-500 hover:bg-gray-100 dark:text-gray-400 dark:hover:bg-gray-800"
          >
            回复
          </button>
        </div>
        <p className="mt-2 text-sm leading-relaxed text-gray-700 dark:text-gray-300">
          {comment.body}
        </p>
        {comment.comments && comment.comments.length > 0 && (
          <div className="mt-2">
            {comment.comments.map((reply: Comment) => (
              <CommentItem
                key={reply._id}
                comment={reply}
                depth={depth + 1}
                onReply={onReply}
              />
            ))}
          </div>
        )}
      </div>
    </motion.div>
  );
}

function CommentForm({
  onSubmit,
  onCancel,
  isSubmitting,
  placeholder = '写下你的评论...',
  initialValue = '',
}: {
  onSubmit: (body: string) => void;
  onCancel?: () => void;
  isSubmitting?: boolean;
  placeholder?: string;
  initialValue?: string;
}) {
  const [body, setBody] = useState(initialValue);

  return (
    <div className="rounded-2xl border border-gray-200 bg-white p-4 dark:border-gray-700 dark:bg-gray-900">
      <textarea
        value={body}
        onChange={(e) => setBody(e.target.value)}
        placeholder={placeholder}
        rows={3}
        className="w-full resize-none rounded-xl border border-gray-200 bg-gray-50 p-3 text-sm text-gray-900 placeholder:text-gray-400 focus:border-blue-500 focus:outline-none focus:ring-2 focus:ring-blue-500/20 dark:border-gray-700 dark:bg-gray-800 dark:text-white dark:placeholder:text-gray-500"
      />
      <div className="mt-3 flex justify-end gap-2">
        {onCancel && (
          <button
            onClick={onCancel}
            className="rounded-lg px-4 py-2 text-sm font-medium text-gray-600 hover:bg-gray-100 dark:text-gray-400 dark:hover:bg-gray-800"
          >
            取消
          </button>
        )}
        <button
          onClick={() => {
            if (body.trim()) {
              onSubmit(body);
              setBody('');
            }
          }}
          disabled={!body.trim() || isSubmitting}
          className="rounded-lg bg-blue-600 px-4 py-2 text-sm font-medium text-white hover:bg-blue-700 disabled:cursor-not-allowed disabled:opacity-50 active:scale-95 transition-transform"
        >
          {isSubmitting ? '发布中...' : '发布评论'}
        </button>
      </div>
    </div>
  );
}

function LoadingSkeleton() {
  return (
    <div className="animate-pulse space-y-6 px-4">
      <div className="space-y-4">
        <div className="h-8 w-3/4 rounded-lg bg-gray-200 dark:bg-gray-800" />
        <div className="h-4 w-1/4 rounded bg-gray-200 dark:bg-gray-800" />
      </div>
      <div className="space-y-3">
        <div className="h-4 w-full rounded bg-gray-200 dark:bg-gray-800" />
        <div className="h-4 w-full rounded bg-gray-200 dark:bg-gray-800" />
        <div className="h-4 w-2/3 rounded bg-gray-200 dark:bg-gray-800" />
      </div>
    </div>
  );
}

function ErrorState({
  message,
  onRetry,
}: {
  message: string;
  onRetry: () => void;
}) {
  return (
    <div className="flex flex-col items-center justify-center rounded-2xl border-2 border-dashed border-red-200 bg-red-50/50 p-8 text-center dark:border-red-800/50 dark:bg-red-900/20 mx-4">
      <svg
        xmlns="http://www.w3.org/2000/svg"
        className="h-12 w-12 text-red-400"
        fill="none"
        viewBox="0 0 24 24"
        strokeWidth="1.5"
        stroke="currentColor"
      >
        <path
          strokeLinecap="round"
          strokeLinejoin="round"
          d="M12 9v3.75m-9.303 3.376c-.866 1.5.217 3.374 1.948 3.374h14.71c1.73 0 2.813-1.874 1.948-3.374L13.949 3.378c-.866-1.5-3.032-1.5-3.898 0L2.697 16.126zM12 15.75h.007v.008H12v-.008z"
        />
      </svg>
      <p className="mt-4 text-lg font-medium text-red-600 dark:text-red-400">
        加载失败
      </p>
      <p className="mt-1 text-sm text-red-500">{message}</p>
      <button
        onClick={onRetry}
        className="mt-4 rounded-lg bg-red-600 px-4 py-2 text-sm font-medium text-white hover:bg-red-700 active:scale-95 transition-transform"
      >
        重试
      </button>
    </div>
  );
}

export default function BlogPostView() {
  const { postId } = useParams<{ postId: string }>();
  const navigate = useNavigate();

  const [post, setPost] = useState<BlogDetail | null>(null);
  const [isLoading, setIsLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [isSubmitting, setIsSubmitting] = useState(false);
  const [replyTo, setReplyTo] = useState<Comment | null>(null);

  const contentRef = useRef<HTMLDivElement>(null);

  const fetchPost = useCallback(async () => {
    if (!postId) return;

    setIsLoading(true);
    setError(null);

    try {
      const service = blogService();
      const result = await service.getBlogPost(postId);
      setPost(result);
    } catch (err) {
      setError(err instanceof Error ? err.message : '加载文章失败');
    } finally {
      setIsLoading(false);
    }
  }, [postId]);

  useEffect(() => {
    fetchPost();
  }, [fetchPost]);

  const handleSubmitComment = async (body: string) => {
    if (!postId || !body.trim()) return;

    setIsSubmitting(true);

    try {
      const service = blogService();
      await service.postComment({
        post_id: postId,
        body: body.trim(),
        author: '匿名用户',
        reply_to: replyTo?._id,
        reply_to_author: replyTo?.author,
      });
      setReplyTo(null);
      await fetchPost();
    } catch (err) {
      alert(err instanceof Error ? err.message : '评论失败');
    } finally {
      setIsSubmitting(false);
    }
  };

  const handleReply = (comment: Comment) => {
    setReplyTo(comment);
    contentRef.current?.scrollIntoView({ behavior: 'smooth' });
  };

  const flatComments = (comments: Comment[]): Comment[] => {
    const flat: Comment[] = [];
    const flatten = (list: Comment[]) => {
      list.forEach((c) => {
        flat.push(c);
        if (c.comments && c.comments.length > 0) {
          flatten(c.comments);
        }
      });
    };
    flatten(comments);
    return flat;
  };

  return (
    <div className="min-h-dvh bg-gray-50 dark:bg-slate-950">
      {/* Header */}
      <div className="sticky top-0 z-10 bg-white/80 backdrop-blur-md dark:bg-gray-900/80">
        <div className="flex items-center gap-3 px-4 py-3">
          <button
            onClick={() => navigate(-1)}
            className="flex h-10 w-10 items-center justify-center rounded-full hover:bg-gray-100 active:scale-95 transition-transform dark:hover:bg-gray-800"
          >
            <svg
              className="h-5 w-5 text-gray-700 dark:text-gray-300"
              fill="none"
              stroke="currentColor"
              viewBox="0 0 24 24"
            >
              <path
                strokeLinecap="round"
                strokeLinejoin="round"
                strokeWidth="2"
                d="M15 19l-7-7 7-7"
              />
            </svg>
          </button>
          <h1 className="flex-1 truncate text-lg font-semibold text-gray-900 dark:text-white">
            {post?.title || '文章'}
          </h1>
        </div>
      </div>

      <AnimatePresence mode="wait">
        {isLoading ? (
          <motion.div
            key="loading"
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ opacity: 0 }}
            className="py-6"
          >
            <LoadingSkeleton />
          </motion.div>
        ) : error ? (
          <motion.div
            key="error"
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ opacity: 0 }}
            className="py-6"
          >
            <ErrorState message={error} onRetry={fetchPost} />
          </motion.div>
        ) : post ? (
          <motion.article
            key="content"
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            exit={{ opacity: 0 }}
            className="pb-20"
          >
            {/* Hero */}
            <div className="px-4 pt-4">
              {post.is_pinned && (
                <div className="mb-3 inline-flex items-center gap-1.5 rounded-full bg-blue-100 px-3 py-1 text-xs font-medium text-blue-700 dark:bg-blue-900/30 dark:text-blue-400">
                  <svg
                    xmlns="http://www.w3.org/2000/svg"
                    className="h-3.5 w-3.5"
                    viewBox="0 0 20 20"
                    fill="currentColor"
                  >
                    <path d="M5 4a2 2 0 012-2h6a2 2 0 012 2v14l-5-2.5L5 18V4z" />
                  </svg>
                  置顶文章
                </div>
              )}

              <h1 className="text-2xl font-bold leading-tight text-gray-900 dark:text-white">
                {post.title}
              </h1>

              <div className="mt-3 flex flex-wrap items-center gap-3 text-sm text-gray-500 dark:text-gray-400">
                <div className="flex items-center gap-2">
                  <div className="flex h-6 w-6 items-center justify-center rounded-full bg-gradient-to-br from-blue-500 to-sky-500 text-xs font-bold text-white">
                    A
                  </div>
                  <span>{post.category?.name || '未分类'}</span>
                </div>
                <span className="text-gray-300 dark:text-gray-600">|</span>
                <span>{formatDate(post.created_at)}</span>
                {post.updated_at !== post.created_at && (
                  <>
                    <span className="text-gray-300 dark:text-gray-600">|</span>
                    <span>更新于 {formatDate(post.updated_at)}</span>
                  </>
                )}
              </div>
            </div>

            {/* Divider */}
            <div className="my-4 h-px bg-gray-100 dark:bg-gray-800" />

            {/* Content */}
            <div
              ref={contentRef}
              className="px-4 prose prose-sm dark:prose-invert max-w-none"
            >
              <div
                className="leading-relaxed text-gray-700 dark:text-gray-300 [&_p]:mb-4 [&_h1,&_h2,&_h3,&_h4]:font-bold [&_h1]:text-xl [&_h2]:text-lg [&_h3]:text-base [&_a]:text-blue-600 [&_a]:underline"
                dangerouslySetInnerHTML={{ __html: sanitizeHtml(post.body) }}
              />
            </div>

            {/* Comments Section */}
            <div className="mx-4 mt-8 rounded-2xl bg-white p-4 dark:bg-gray-900">
              <h2 className="text-lg font-semibold text-gray-900 dark:text-white">
                评论 ({flatComments(post.comments || []).length})
              </h2>

              {/* Comment Form */}
              <div className="mt-4">
                {replyTo ? (
                  <div className="mb-3 flex items-center gap-2 text-sm text-gray-500 dark:text-gray-400">
                    <span>回复 @</span>
                    <span className="font-medium text-gray-700 dark:text-gray-300">
                      {replyTo.author}
                    </span>
                    <button
                      onClick={() => setReplyTo(null)}
                      className="ml-auto rounded-lg px-2 py-1 hover:bg-gray-100 dark:hover:bg-gray-800"
                    >
                      取消
                    </button>
                  </div>
                ) : null}
                <CommentForm
                  onSubmit={handleSubmitComment}
                  onCancel={replyTo ? () => setReplyTo(null) : undefined}
                  isSubmitting={isSubmitting}
                  placeholder={
                    replyTo
                      ? `回复 @${replyTo.author}...`
                      : '写下你的评论...'
                  }
                />
              </div>

              {/* Comments List */}
              {post.comments && post.comments.length > 0 ? (
                <div className="mt-4 divide-y divide-gray-100 dark:divide-gray-800">
                  {post.comments.map((comment) => (
                    <CommentItem
                      key={comment._id}
                      comment={comment}
                      onReply={handleReply}
                    />
                  ))}
                </div>
              ) : (
                <div className="mt-6 text-center text-sm text-gray-400">
                  暂无评论，来发表第一条评论吧
                </div>
              )}
            </div>
          </motion.article>
        ) : null}
      </AnimatePresence>
    </div>
  );
}
