// react-app/src/views/Home/components/BentoCalendar.tsx
import { BentoCard } from '@/components/bento/BentoCard';
import dayjs from 'dayjs';

export function BentoCalendar() {
  const now = dayjs();
  const monthLabel = now.format('MMMM');
  const yearLabel = now.format('YYYY');

  const weekday = now.day(); // 0-6, 0是周日
  const weekdayLabels = ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'];
  const weekdayHeaders = weekdayLabels.map((label, idx) => (
    <span
      key={idx}
      className={`py-1 text-xs font-medium tabular-nums ${
        idx === weekday ? 'bg-primary/10 text-primary rounded-xl font-bold' : ''
      }`}
    >
      {label}
    </span>
  ));

  const startOffset = () => {
    const offset = now.startOf('month').day();

    const offsetArray = new Array(offset).fill(0);

    return offsetArray.map((_, idx) => <span key={idx}></span>);
  };

  const daysInMonthArray = new Array(now.daysInMonth()).fill(0);
  const daysInMonth = daysInMonthArray.map((_, idx) => {
    const dayNum = idx + 1;
    const isToday = dayNum === now.date();

    return (
      <span
        key={idx}
        className={`mx-auto flex aspect-square w-full max-w-8 items-center justify-center rounded-full text-sm transition-colors ${
          isToday
            ? 'bg-primary text-primary-foreground font-bold'
            : 'text-card-foreground hover:bg-primary/10'
        }`}
      >
        {dayNum}
      </span>
    );
  });

  return (
    <BentoCard className="flex flex-col">
      <div className="mb-3 flex items-center justify-between">
        <h3 className="text-foreground text-lg font-semibold">{monthLabel}</h3>
        <span className="text-muted-foreground text-sm tabular-nums">
          {yearLabel}
        </span>
      </div>
      {/* 表头 */}
      <div className="mb-1 grid grid-cols-7 text-center">{weekdayHeaders}</div>

      {/* 日期部分 */}
      <div className="grid grid-cols-7 text-center">
        {startOffset()}
        {daysInMonth}
      </div>
    </BentoCard>
  );
}

// frontend/src/features/entry/components/BentoCalendar.vue
<template>
  <BentoCard
    class="group relative flex flex-col gap-2 overflow-hidden select-none"
  >
    <!-- 背景水波纹效果 -->
    <div
      class="from-primary/30 via-secondary/30 to-secondary/30 absolute inset-0 bg-linear-to-br opacity-0 transition-opacity duration-500 group-hover:opacity-100"
    />

    <!-- 顶部：图标和标题 -->
    <!-- Hearder -->
    <div class="flex items-baseline justify-between">
      <div
        class="flex h-10 w-10 items-center justify-center rounded-2xl transition-transform duration-300 group-hover:scale-110 group-hover:rounded-xl"
      >
        <CalendarDays class="text-foreground size-6" />
      </div>

      <div class="mb-3 flex items-center justify-end-safe gap-3">
        <h3 class="text-foreground text-lg font-semibold">
          {{ monthLabel }}
        </h3>
        <span class="text-muted-foreground text-sm">{{ yearLabel }}</span>
      </div>
    </div>

    <!-- Weekday headers -->
    <div
      class="mb-1 grid gap-x-3 text-center"
      style="grid-template-columns: repeat(7, 1fr)"
    >
      <span
        v-for="(label, idx) in weekdays"
        :key="idx"
        class="py-1 text-xs font-medium"
        :class="idx === weekdayToday ? 'text-primary' : 'text-muted-foreground'"
      >
        {{ label }}
      </span>
    </div>

    <!-- Days grid -->
    <div
      class="grid gap-x-3 text-center"
      style="grid-template-columns: repeat(7, 1fr)"
    >
      <!-- Leading blank cells for alignment -->
      <span v-for="n in startOffset" :key="'blank-' + n" />

      <!-- Day numbers -->
      <span
        v-for="day in daysInMonth"
        :key="day"
        class="mx-auto flex aspect-square w-full max-w-8 items-center justify-center rounded-lg text-sm transition-colors"
        :class="
          day === today
            ? 'bg-primary text-primary-foreground font-bold'
            : 'text-muted-foreground hover:bg-primary/10'
        "
      >
        {{ day }}
      </span>
    </div>
  </BentoCard>
</template>

<script setup lang="ts">
import BentoCard from './BentoCard.vue';
import dayjs from 'dayjs';
import { computed } from 'vue';
import { CalendarDays } from '@lucide/vue';

const now = dayjs();

const weekdays = ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'];
const weekdayToday = computed(() => dayjs().day());
const monthLabel = computed(() => now.format('MMMM'));
const yearLabel = computed(() => now.format('YYYY'));

// Day of week for the 1st of the month (0 = Sunday)
const startOffset = computed(() => now.startOf('month').day());

// Total days in current month
const daysInMonth = computed(() => now.daysInMonth());

// Current day number (1-31)
const today = computed(() => now.date());
</script>
